### ISSUE TITLE
Amplify dont build react app

### ISSUE THREAD

**Issue by bazoukiwi** [aws-amplify/amplify-hosting#1594]
Hi,
Amplify dont build my react app. The app works when launched by npm start run.
At first i had issues with binding.gyp. I then addded the file on the root folder : 

`{
  "targets": [
    {
      "target_name": "tag",
    }
  ]
}`

Amplify still dont build. Here is the log : 
`
                                 # Starting phase: preBuild
                                 # Executing command: yarn install
2021-02-22T22:20:43.529Z [INFO]: yarn install v1.22.0
2021-02-22T22:20:43.602Z [INFO]: [1/4] Resolving packages...
2021-02-22T22:20:44.455Z [WARNING]: warning aws-amplify > @aws-amplify/auth > amazon-cognito-identity-js > buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
2021-02-22T22:20:45.292Z [WARNING]: warning axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
2021-02-22T22:20:45.561Z [WARNING]: warning node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2021-02-22T22:20:45.587Z [WARNING]: warning node-gyp > request > har-validator@5.1.5: this library is no longer supported
2021-02-22T22:20:46.803Z [INFO]: [2/4] Fetching packages...
2021-02-22T22:20:53.453Z [WARNING]: warning file-loader@2.0.0: Invalid bin field for "file-loader".
2021-02-22T22:20:54.164Z [WARNING]: warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
2021-02-22T22:20:54.251Z [WARNING]: warning url-loader@1.1.2: Invalid bin field for "url-loader".
2021-02-22T22:21:04.813Z [INFO]: info fsevents@1.2.4: The platform "linux" is incompatible with this module.
2021-02-22T22:21:04.815Z [INFO]: info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
2021-02-22T22:21:04.817Z [INFO]: info fsevents@1.2.7: The platform "linux" is incompatible with this module.
2021-02-22T22:21:04.817Z [INFO]: info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
2021-02-22T22:21:04.834Z [INFO]: [3/4] Linking dependencies...
2021-02-22T22:21:04.837Z [WARNING]: warning "aws-amplify > @aws-amplify/core > @aws-sdk/client-cognito-identity > @aws-sdk/middleware-retry > react-native-get-random-values@1.6.0" has unmet peer dependency "react-native@>=0.56".
2021-02-22T22:21:04.840Z [WARNING]: warning "react-scripts > pnp-webpack-plugin > ts-pnp@1.0.0" has unmet peer dependency "typescript@*".
2021-02-22T22:21:04.843Z [WARNING]: warning " > react-tradingview-widget@1.3.2" has unmet peer dependency "prop-types@^15.6.0".
2021-02-22T22:21:19.830Z [INFO]: [4/4] Building fresh packages...
2021-02-22T22:21:22.641Z [WARNING]: error /codebuild/output/src492295330/src/tag/node_modules/libpq: Command failed.
                                    Exit code: 1
                                    Command: node-gyp rebuild
                                    Arguments:
                                    Directory: /codebuild/output/src492295330/src/tag/node_modules/libpq
                                    Output:
                                    gyp info it worked if it ends with ok
                                    gyp info using node-gyp@5.1.0
                                    gyp info using node@12.19.0 | linux | x64
                                    gyp info find Python using Python version 2.7.18 found at "/usr/bin/python"
                                    gyp http GET https://nodejs.org/download/release/v12.19.0/node-v12.19.0-headers.tar.gz
                                    gyp http 200 https://nodejs.org/download/release/v12.19.0/node-v12.19.0-headers.tar.gz
                                    gyp http GET https://nodejs.org/download/release/v12.19.0/SHASUMS256.txt
                                    gyp http 200 https://nodejs.org/download/release/v12.19.0/SHASUMS256.txt
                                    gyp info spawn /usr/bin/python
                                    gyp info spawn args [
                                    gyp info spawn args   '/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
                                    gyp info spawn args   'binding.gyp',
                                    gyp info spawn args   '-f',
                                    gyp info spawn args   'make',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/codebuild/output/src492295330/src/tag/node_modules/libpq/build/config.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
                                    gyp info spawn args   '-I',
                                    gyp info spawn args   '/root/.cache/node-gyp/12.19.0/include/node/common.gypi',
                                    gyp info spawn args   '-Dlibrary=shared_library',
                                    gyp info spawn args   '-Dvisibility=default',
                                    gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.19.0',
                                    gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp',
                                    gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.19.0/<(target_arch)/node.lib',
                                    gyp info spawn args   '-Dmodule_root_dir=/codebuild/output/src492295330/src/tag/node_modules/libpq',
                                    gyp info spawn args   '-Dnode_engine=v8',
                                    gyp info spawn args   '--depth=.',
                                    gyp info spawn args   '--no-parallel',
                                    gyp info spawn args   '--generator-output',
                                    gyp info spawn args   'build',
                                    gyp info spawn args   '-Goutput_dir=.'
                                    gyp info spawn args ]
                                    which: no pg_config in (/tmp/yarn--1614032479844-0.7511532088938635:/codebuild/output/src492295330/src/tag/node_modules/libpq/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/root/.nvm/versions/node/v12.19.0/libexec/lib/node_modules/npm/bin/node-gyp-bin:/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/bin/node-gyp-bin:/root/.nvm/versions/node/v12.19.0/bin/node_modules/npm/bin/node-gyp-bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.yarn/bin:/root/.config/yarn/global/node_modules/.bin:/root/.nvm/versions/node/v12.19.0/bin:/root/.local/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools)
                                    find: ‘/usr/pg*’: No such file or directory
                                    gyp: Call to 'which pg_config || find /usr/bin /usr/local/bin /usr/pg* /opt -executable -name pg_config -print -quit' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
                                    gyp ERR! configure error
                                    gyp ERR! stack Error: `gyp` failed with exit code: 1
                                    gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
                                    gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
                                    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
                                    gyp ERR! System Linux 4.14.214-118.339.amzn1.x86_64
                                    gyp ERR! command "/root/.nvm/versions/node/v12.19.0/bin/node" "/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
                                    gyp ERR! cwd /codebuild/output/src492295330/src/tag/node_modules/libpq
                                    gyp ERR! node -v v12.19.0
                                    gyp ERR! node-gyp -v v5.1.0
                                    gyp ERR! not ok
2021-02-22T22:21:22.641Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2021-02-22T22:21:22.676Z [ERROR]: !!! Build failed
2021-02-22T22:21:22.676Z [ERROR]: !!! Non-Zero Exit Code detected
2021-02-22T22:21:22.676Z [INFO]: # Starting environment caching...
2021-02-22T22:21:22.677Z [INFO]: # Environment caching completed
Terminating logging...
`

note: node-gyp rebuild work when used localy.
Why cant amplify use it? maybe my binding isnt set correctly? i've read the doc but cant understand what i sould put in this. I'm not here to make an addon, juste upload a small app. 
Thanks for your time

**Comment by Athena96** [comment]
Hello, can you share your appId please

**Comment by bazoukiwi** [comment]
Hello and thanks for the answer. The fact is i dont know how to display the appID.
I created my app with react-create-app, started to dev, then to push it to amplify i pushed it to github, created on the amplify UI an app linked to the git branch. 
So to do it the right way i copied my app folder and did amplify init, then published the app. It doesnt not work (403 error, blank page) but the appID is : dhzqryes3jjo
In case this can help you.
Thanks again !

**Comment by saadataz** [comment]
@bazoukiwi judging by the error 
> find: ‘/usr/pg*’: No such file or directory gyp: Call to 'which pg_config || find /usr/bin /usr/local/bin /usr/pg* /opt -executable -name pg_config -print -quit' returned exit status 1

it looks like you need to install the dependency `pg_config` or `pg` in the build container before running the `npm install` step
