### ISSUE TITLE
Persistent error "There was an issue connecting to your repo provider, click "Re-authenticate app" in Genethis verral Settings, and then try your build again."

### ISSUE THREAD

**Issue by jameshume** [aws-amplify/amplify-hosting#1674]
**Describe the bug**
I am following the AWS tutorial, finishing "Module 3: Add Authentication". The authentication example app runs fine locally but does not build.

I had a problem before this which I fixed by following the suggestion in https://github.com/aws-amplify/amplify-cli/issues/6117 and clamping the AWS CLI version used for build to be the same as my local version (4.45.2), which solved this error.

But then I got the error about re-authenticating my app. I followed the instructions, deleting the existing web hooks and the re-authenticating, but the error message persists.

The console output seems to suggest that the build process accessed my github account okay and was able to clone my test app. It also appears that it was able to update the amplify CLI version from 4.29.4, to the version I am using locally, 4.45.2.

But, the log stops there and I can't see any explicit errors:

```
2021-03-20T16:23:54.404Z [INFO]: Git SSH Key acquired
021-03-20T16:23:54.404Z [INFO]: Git SSH Key acquired
2021-03-20T16:23:54.483Z [INFO]: # Cloning repository: git@github.com:jameshume/amplifyapp.git
2021-03-20T16:23:54.491Z [INFO]: Agent pid 137
2021-03-20T16:23:54.519Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-03-20T16:23:54.796Z [INFO]: Cloning into 'amplifyapp'...
2021-03-20T16:23:55.347Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
2021-03-20T16:23:57.189Z [INFO]: # Switching to commit: 56fb35293b153e241baf7e23e00f41f401b6b205
2021-03-20T16:23:57.196Z [INFO]: Agent pid 150
2021-03-20T16:23:57.200Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-03-20T16:23:57.204Z [INFO]: Note: switching to '56fb35293b153e241baf7e23e00f41f401b6b205'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
2021-03-20T16:23:57.205Z [INFO]: HEAD is now at 56fb352 added auth
2021-03-20T16:23:57.210Z [INFO]: Successfully cleaned up Git credentials
2021-03-20T16:23:57.211Z [INFO]: # Checking for Git submodules at: /codebuild/output/src684925248/src/amplifyapp/.gitmodules
2021-03-20T16:23:57.231Z [INFO]: # Retrieving cache...
2021-03-20T16:23:59.127Z [INFO]: # Extracting cache...
ed
2021-03-20T16:24:02.904Z [INFO]: # Retrieving environment cache...
2021-03-20T16:24:02.935Z [INFO]: # Retrieved environment cache
2021-03-20T16:24:02.936Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: '4.45.2'
2021-03-20T16:24:13.611Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 4.45.2...
021-03-20T16:23:54.404Z [INFO]: Git SSH Key acquired
2021-03-20T16:23:54.483Z [INFO]: # Cloning repository: git@github.com:jameshume/amplifyapp.git
2021-03-20T16:23:54.491Z [INFO]: Agent pid 137
2021-03-20T16:23:54.519Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-03-20T16:23:54.796Z [INFO]: Cloning into 'amplifyapp'...
2021-03-20T16:23:55.347Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
2021-03-20T16:23:57.189Z [INFO]: # Switching to commit: 56fb35293b153e241baf7e23e00f41f401b6b205
2021-03-20T16:23:57.196Z [INFO]: Agent pid 150
2021-03-20T16:23:57.200Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-03-20T16:23:57.204Z [INFO]: Note: switching to '56fb35293b153e241baf7e23e00f41f401b6b205'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
2021-03-20T16:23:57.205Z [INFO]: HEAD is now at 56fb352 added auth
2021-03-20T16:23:57.210Z [INFO]: Successfully cleaned up Git credentials
2021-03-20T16:23:57.211Z [INFO]: # Checking for Git submodules at: /codebuild/output/src684925248/src/amplifyapp/.gitmodules
2021-03-20T16:23:57.231Z [INFO]: # Retrieving cache...
2021-03-20T16:23:59.127Z [INFO]: # Extracting cache...
2021-03-20T16:24:02.800Z [INFO]: # Extraction completed
2021-03-20T16:24:02.904Z [INFO]: # Retrieving environment cache...
2021-03-20T16:24:02.935Z [INFO]: # Retrieved environment cache
2021-03-20T16:24:02.936Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: '4.45.2'
2021-03-20T16:24:13.611Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 4.45.2...
2021-03-20T16:25:00.879Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
```

Not sure how to debug this further... are there any other logs I can access?

Thanks,
James

**To Reproduce**
1. Click "Redeploy this version" in my amplify console

**Expected behavior**
Expected it to build correctly

**Screenshots**
I think the description should be enough but will add screenshots if anyone thinks they will prove useful.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 10.0.19041 (Build 19041)
 - Browser Chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by monckey100** [comment]
I am also experiencing this issue, it's new. Also getting 502 errors.

**Comment by ganipcanot** [comment]
Can either or both of you share your `appId` (part of the app ARN) and/or region where you're experiencing this issue?

**Comment by monckey100** [comment]
ca-central-1  
`arn:aws:amplify:ca-central-1:108497320985:apps/d2wp73l7cepdb3`

**Comment by ganipcanot** [comment]
@monckey100 I'm seeing this in the build error logs:

```
2021-03-22T21:02:55.021Z [WARNING]: [error] Could not resolve routes
--
105 | 2021-03-22T21:02:55.023Z [WARNING]: [fatal] Request failed with status code 502
106 | at createError (node_modules/axios/lib/core/createError.js:16:15)
107 | at settle (node_modules/axios/lib/core/settle.js:17:12)
108 | at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)
109 | at IncomingMessage.emit (node:events:381:22)
110 | at IncomingMessage.emit (node:domain:470:12)
111 | at endReadableNT (node:internal/streams/readable:1307:12)
112 | at processTicksAndRejections (node:internal/process/task_queues:81:21)
113 | 2021-03-22T21:02:55.040Z [WARNING]: ╭────────────────────────────────────────────────╮
114 | │                                                │
115 | │   ✖ Nuxt Fatal Error                           │
116 | │                                                │
117 | │   Error: Request failed with status code 502   │
118 | │                                                │
119 | ╰────────────────────────────────────────────────╯
120 | 2021-03-22T21:02:55.060Z [WARNING]: npm
121 | 2021-03-22T21:02:55.060Z [WARNING]: ERR! code 1
122 | npm ERR! path /codebuild/output/src368922229/src/sparxtrading_2.0
123 | 2021-03-22T21:02:55.062Z [WARNING]: npm
124 | 2021-03-22T21:02:55.062Z [WARNING]: ERR! command failed
125 | npm ERR! command sh -c nuxt generate
126 | 2021-03-22T21:02:55.068Z [WARNING]:
127 | 2021-03-22T21:02:55.068Z [WARNING]: npm ERR! A complete log of this run can be found in:
128 | npm ERR!     /root/.npm/_logs/2021-03-22T21_02_55_062Z-debug.log
129 | 2021-03-22T21:02:55.068Z [HELP]: Outputting the npm debug log
130 | 0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'export' ]
131 | 1 info using npm@7.6.3
132 | 2 info using node@v15.12.0
133 | 3 timing config:load:defaults Completed in 1ms
134 | 4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
135 | 5 timing config:load:builtin Completed in 0ms
136 | 6 timing config:load:cli Completed in 1ms
137 | 7 timing config:load:env Completed in 1ms
138 | 8 timing config:load:file:/codebuild/output/src368922229/src/sparxtrading_2.0/.npmrc Completed in 0ms
139 | 9 timing config:load:project Completed in 0ms
140 | 10 timing config:load:file:/root/.npmrc Completed in 0ms
141 | 11 timing config:load:user Completed in 0ms
142 | 12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
143 | 13 timing config:load:global Completed in 0ms
144 | 14 timing config:load:cafile Completed in 0ms
145 | 15 timing config:load:validate Completed in 0ms
146 | 16 timing config:load:setUserAgent Completed in 0ms
147 | 17 timing config:load:setEnvs Completed in 0ms
148 | 18 timing config:load Completed in 4ms
149 | 19 verbose npm-session 248635961fae611d
150 | 20 timing npm:load Completed in 10ms
151 | 21 timing command:run Completed in 232057ms
152 | 22 verbose stack Error: command failed
153 | 22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
154 | 22 verbose stack     at ChildProcess.emit (node:events:369:20)
155 | 22 verbose stack     at maybeClose (node:internal/child_process:1067:16)
156 | 22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
157 | 23 verbose pkgid sparxtrading_2.0@1.0.0
158 | 24 verbose cwd /codebuild/output/src368922229/src/sparxtrading_2.0
159 | 25 verbose Linux 4.14.219-119.340.amzn1.x86_64
160 | 26 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "export"
161 | 27 verbose node v15.12.0
162 | 28 verbose npm  v7.6.3
163 | 29 error code 1
164 | 30 error path /codebuild/output/src368922229/src/sparxtrading_2.0
165 | 31 error command failed
166 | 32 error command sh -c nuxt generate
167 | 33 verbose exit 1
168 | 2021-03-22T21:02:55.071Z [ERROR]: !!! Build failed
169 | 2021-03-22T21:02:55.071Z [ERROR]: !!! Non-Zero Exit Code detected
```

Are you not seeing this on your end?

**Comment by sam10105** [comment]
Hey @ganipcanot, I'm also experiencing the same issue. Here is my app arn: `arn:aws:amplify:us-east-2:682088751517:apps/dk65qdzmmrw0p`

**Comment by YashMarmat** [comment]
**here's a try:**

Before pushing the code to AWS amplify try to generate the build locally 
`npm run build`
(in my case it was SVG issue, which AWS console was not detecting)

**Comment by Jay2113** [comment]
Over the past couple of years, we have made several improvements to the build logs output in the Amplify console.

Our recommendation would be to first build your application locally (to see if any errors are returned in the process) and then commit the changes to a git repository followed by deploying it on Amplify Hosting. 

I am going to close this thread but please feel free to create a new issue if you are experiencing any issues with Amplify Hosting. Thanks!
