### ISSUE TITLE
Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId, identityPoolI

### ISSUE THREAD

**Issue by wvidana** [aws-amplify/amplify-hosting#2039]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d59j1tvmglhyl

### Region

eu-west-1

### Amplify Console feature

Backend builds

### Describe the bug

It is not possible to deploy the backend with an imported Auth component, the CI/CD build fails with:
```
Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId, identityPoolId
```

Locally pushing the changes with `amplify push` causes no error. The information is in there, in some config files, is just that the deployment in the Amplify console is not reading it correctly.

I'm trying to figure out if there is something missing in the `amplifyPush.sh` script, but the one in this repository seems outdated 🤷 

### Expected behavior

The full-stack app gets deployed correctly without errors

### Reproduction steps

1. Import a cognito user pool and identity pool with `amplify import auth`
2. Push with `amplify push` to apply the changes
3. Commit your changes and wait for the CI/CD to start the build in the Amplify console
4. ...ERROR

**Comment by wvidana** [comment]
Adding env vars and using them in `amplipyPush.sh` seems to fix the issue:

Diff from https://github.com/aws-amplify/amplify-console/blob/081895f49291f3c1508c63ae68d42bc09a846ab9/scripts/amplifyPush.sh
```diff
 }"
 CATEGORIES=""
 if [[ -z ${AMPLIFY_FACEBOOK_CLIENT_ID} && -z ${AMPLIFY_GOOGLE_CLIENT_ID} && -z ${AMPLIFY_AMAZON_CLIENT_ID} ]]; then
-    CATEGORIES=""
+    if [[ -z ${AMPLIFY_USERPOOL_ID} && -z ${AMPLIFY_WEBCLIENT_ID} && -z ${AMPLIFY_NATIVECLIENT_ID} && -z ${AMPLIFY_IDENTITYPOOL_ID} ]]; then
+        CATEGORIES=""
+    else
+        AUTHCONFIG="{\
+        \"userPoolId\":\"${AMPLIFY_USERPOOL_ID}\",\
+        \"webClientId\":\"${AMPLIFY_WEBCLIENT_ID}\",\
+        \"nativeClientId\":\"${AMPLIFY_NATIVECLIENT_ID}\"\
+        \"identityPoolId\":\"${AMPLIFY_IDENTITYPOOL_ID}\"\
+        }"
+        CATEGORIES="{\
+        \"auth\":$AUTHCONFIG\
+        }"
+    fi
 else
     AUTHCONFIG="{\
     \"facebookAppIdUserPool\":\"${AMPLIFY_FACEBOOK_CLIENT_ID}\",\
```

The problem is that depending on the environment this values changes... Is there anyway of loading them from `team-profider-info.json` or just make the script load them like the `amplify push` command?

**Comment by eddiekeller** [comment]
I have the same issue but going in reverse - I created a backend via the console and am trying to `pull` it down.

https://github.com/aws-amplify/amplify-console/issues/2040

**Comment by Narrator** [comment]
@wvidana Please refer to this [comment](https://github.com/aws-amplify/amplify-console/issues/2269#issuecomment-925379232). Our docs need to be updated, but the solution is to provide the missing values via environment variables in the app's build settings.

Please see [here](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables) for all available environment variables.

**Comment by bmccann36** [comment]
I am having the exact same issue as described

**Comment by Narrator** [comment]
@bmccann36 Could you please share your app id and region?

**Comment by tjordanahp** [comment]
Testing out Auth with Amplify, the same issue.

Following the documents here: https://docs.amplify.aws/start/getting-started/installation/q/integration/vue/

When I got to the add **"Add authentication"**, then ran this command [ amplify add auth ], the build failed after a push. The build error is below.

If you want, I'll keep the App Id: d2lervtrgi1bea up. Region: us-east-1

2022-05-19T04:17:58.049Z [INFO]: [0mAmplify AppID found: d2lervtrgi1bea. Amplify App name is: ahpreports[0m
2022-05-19T04:17:58.099Z [INFO]: [0mBackend environment dev found in Amplify Console app: ahpreports[0m
2022-05-19T04:17:58.701Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2022-05-19T04:17:59.243Z [WARNING]: - Building resource auth/ahpreports
2022-05-19T04:17:59.285Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2022-05-19T04:17:59.298Z [WARNING]: ✖ There was an error initializing your environment.
2022-05-19T04:17:59.300Z [INFO]: [31mFailed to pull the backend.[39m
2022-05-19T04:17:59.302Z [INFO]: 🛑 auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId
2022-05-19T04:17:59.302Z [INFO]: **Error: auth headless is missing the following inputParams userPoolId, webClientId, nativeClientId**
                                 at ensureHeadlessParameters (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/import/index.js:877:15)
                                 at headlessImport (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/import/index.js:782:42)
                                 at importedAuthEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/import/index.js:633:49)
                                 at async updateConfigOnEnvInit (/snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/provider-utils/awscloudformation/index.js:36:76)
                                 at async /snapshot/repo/build/node_modules/@aws-amplify/amplify-category-auth/lib/index.js:272:28
2022-05-19T04:17:59.318Z [ERROR]: !!! Build failed

**Comment by tjordanahp** [comment]
Okay, so I figured it out. For my issues, I just added the variables to the "Environment variables" settings within the Amplify app settings. 

<img width="733" alt="image" src="https://user-images.githubusercontent.com/104017485/169518332-6515cb54-cb0f-4408-8168-a32940a69e76.png">
