### ISSUE TITLE
Backend Build - ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by willianjusten** [aws-amplify/amplify-hosting#2131]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1ywuiyssz1l16

### Region

us-east-2

### Amplify Console feature

Backend builds

### Describe the bug

Sometimes I'm getting an error inside the backend build step. Follow the error:

```
                                 ## Checking for associated backend environment...
                                 ## Backend environment association found
2021-08-04T13:31:35.260Z [INFO]: [0mAmplify AppID found: d1ywuiyssz1l16. Amplify App name is: zaptpublic[0m
2021-08-04T13:31:35.427Z [INFO]: [0mBackend environment dev found in Amplify Console app: zaptpublic[0m
2021-08-04T13:31:35.536Z [INFO]: [31mFailed to pull the backend.[39m
2021-08-04T13:31:35.538Z [INFO]: [31mELOOP: too many symbolic links encountered, stat '/codebuild/output/src268676352/src/zapt-public/PaxHeader'[39m
2021-08-04T13:31:35.574Z [INFO]: [0mError: ELOOP: too many symbolic links encountered, stat '/codebuild/output/src268676352/src/zapt-public/PaxHeader'[0m
                                 [0m    at Object.statSync (fs.js:1016:3)[0m
                                 [0m    at Object.statSync (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graceful-fs/polyfills.js:312:16)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/lib/project-scanner.js:10:12)[0m
                                 [0m    at scanProject (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-frontend-ios/index.js:14:25)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a30-initFrontend.ts:21:24[0m
                                 [0m    at Array.forEach (<anonymous>)[0m
                                 [0m    at Object.initFrontend (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a30-initFrontend.ts:19:34)[0m
                                 [0m    at Object.attachBackend (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:29:11)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:59:5)[0m
                                 [0m    at Object.executeAmplifyCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/index.ts:313:5)[0m
                                 [0m    at executePluginModuleCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)[0m
                                 [0m    at Object.executeCommand (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/src/index.ts:151:5)[0m
2021-08-04T13:31:35.591Z [ERROR]: !!! Build failed
2021-08-04T13:31:35.591Z [ERROR]: !!! Non-Zero Exit Code detected
2021-08-04T13:31:35.592Z [INFO]: # Starting environment caching...
2021-08-04T13:31:35.592Z [INFO]: # Uploading environment cache artifact...
2021-08-04T13:31:35.696Z [INFO]: # Environment caching completed
```

### Expected behavior

It should work with no problems since I'm not even using this backend stuff.

### Reproduction steps

1. Init the project with amplify init and answer the questions (remember it's next ssr project, so the build folder is .next)
2. Add hosting with amplify add hosting
3. Connect with Gitlab
4. Wait and see the build

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by nejcm** [comment]
I am running into the same exact problem without ssr

**Comment by kahdojay** [comment]
@willianjusten @nejcm do you have a repo we could fork and repro with? It would also be helpful to have an appId for an repro app that still exists so we can see the latest config.

**Comment by nejcm** [comment]
So we are running a react app and we managed to fix it with temporary removing the cache of node_modules on the amplify.yml.
After that the build went through for some reason.

**Comment by willianjusten** [comment]
After having many issues:

- backend having this kind of issues (I'm not even using it)
- issues with lambda function to image (some images were giving 502 error for no reason)

I just decided to give up =/

The project is closed source, so I can't share, sorry...

**Comment by hloriana** [comment]
We are unable to reproduce. If anyone else runs into this behavior, please create a new issue. Thank you!

**Comment by avvi-mane** [comment]
Still not working.
```
2022-10-12T05:43:08.011Z [WARNING]: > Build error occurred
2022-10-12T05:43:08.013Z [WARNING]: [Error: ELOOP: too many symbolic links encountered, stat '/codebuild/output/src372463070/src/first-policy/PaxHeader'] {
                                    errno: -40,
                                    code: 'ELOOP',
                                    syscall: 'stat',
                                    path: '/codebuild/output/src372463070/src/first-policy/PaxHeader'
                                    }
```
`yarn run build` works perfectly on my local machine and everywhere else.
AWS amplify has been pain with most of the next js projects I've deployed.

**Comment by avvi-mane** [comment]
> So we are running a react app and we managed to fix it with temporary removing the cache of node_modules on the amplify.yml. After that the build went through for some reason.

You saved my life ❤️
