### ISSUE TITLE
Failed to pull the backend. The "path" argument must be of type string. Received undefined.

### ISSUE THREAD

**Issue by newilu** [aws-amplify/amplify-hosting#2251]
region: eu-west-1
appId: d3r87oryjejcv2

```
2021-09-13T05:14:00.638Z [INFO]: Git SSH Key acquired
2021-09-13T05:14:00.714Z [INFO]: # Cloning repository: git@github.com:repo/repository.git
2021-09-13T05:14:00.723Z [INFO]: Agent pid 136
2021-09-13T05:14:00.747Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-09-13T05:14:00.942Z [INFO]: Cloning into 'EffectorEcommerce'...
2021-09-13T05:14:01.525Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
2021-09-13T05:14:04.480Z [INFO]: # Switching to commit: *commitHash*
021-09-13T05:14:00.638Z [INFO]: Git SSH Key acquired
2021-09-13T05:14:00.714Z [INFO]: # Cloning repository: git@github.com:repo/repository.git
2021-09-13T05:14:00.723Z [INFO]: Agent pid 136
2021-09-13T05:14:00.747Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2021-09-13T05:14:00.942Z [INFO]: Cloning into 'EffectorEcommerce'...
2021-09-13T05:14:01.525Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
2021-09-13T05:14:04.480Z [INFO]: # Switching to commit: *commitHash*
2021-09-13T05:14:04.601Z [INFO]: Agent pid 149
2021-09-13T05:14:04.602Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
                                 Note: switching to '*commitHash*'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
                                 HEAD is now at 660835d Delete myamplifypush.sh
2021-09-13T05:14:04.608Z [INFO]: Successfully cleaned up Git credentials
2021-09-13T05:14:04.609Z [INFO]: # Checking for Git submodules at: /codebuild/output/src371429899/src/EffectorEcommerce/.gitmodules
2021-09-13T05:14:04.630Z [INFO]: # Retrieving environment cache...
2021-09-13T05:14:04.682Z [INFO]: # Retrieved environment cache
2021-09-13T05:14:04.682Z [INFO]: ---- Setting Up SSM Secrets ----
2021-09-13T05:14:04.682Z [INFO]: SSM params {"Path":"/amplify/d3r87oryjejcv2/dev/","WithDecryption":true}
2021-09-13T05:14:04.730Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2021-09-13T05:14:09.825Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 5.5.0...
9.521Z [INFO]: [0mBackend environment dev found in Amplify Console app: EffectorEcommerce[0m
2021-09-13T05:16:30.334Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2021-09-13T05:16:30.757Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2021-09-13T05:16:31.257Z [WARNING]: ✖ There was an error initializing your environment.
2021-09-13T05:16:31.263Z [INFO]: [31mFailed to pull the backend.[39m
2021-09-13T05:16:31.264Z [INFO]: [31mThe "path" argument must be of type string. Received undefined[39m
2021-09-13T05:16:31.264Z [INFO]: [0mTypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined[0m
                                 [0m    at validateString (internal/validators.js:120:11)[0m
                                 [0m    at Object.join (path.js:1039:7)[0m
                                 [0m    at PathManager.constructPath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:177:34)[0m
                                 [0m    at PathManager.getResourceDirectoryPath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:124:10)[0m
                                 [0m    at PathManager.getResourceParametersFilePath (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/pathManager.ts:127:20)[0m
                                 [0m    at StateManager.setResourceParametersJson (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/src/state-manager/stateManager.ts:261:34)[0m
                                 [0m    at updateStateFiles (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:704:16)[0m
                                 [0m    at Object.headlessImport (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:1253:26)[0m
                                 [0m    at runMicrotasks (<anonymous>)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:97:5)[0m
                                 [0m    at importedAuthEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts:922:12)[0m
                                 [0m    at updateConfigOnEnvInit (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/provider-utils/awscloudformation/index.js:50:72)[0m
                                 [0m    at /root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/src/index.js:306:22[0m
2021-09-13T05:16:31.283Z [ERROR]: !!! Build failed
2021-09-13T05:16:31.283Z [ERROR]: !!! Non-Zero Exit Code detected
2021-09-13T05:16:31.283Z [INFO]: # Starting environment caching...
2021-09-13T05:16:31.283Z [INFO]: # Uploading environment cache artifact...
2021-09-13T05:16:31.385Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by newilu** [comment]
Hey, can anyone answer me?

**Comment by calavera** [comment]
This problem has been fixed in newer versions of the CLI, sorry about the trouble.
