### ISSUE TITLE
ResourceConflictException: The operation cannot be performed at this time.

### ISSUE THREAD

**Issue by jain-kushal** [aws-amplify/amplify-hosting#2391]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1rp6452ppy5t8

### Region

us-west-2

### Amplify Console feature

Backend builds, Build settings, Manual deploys

### Describe the bug

**Build fails at frontend sub-stage.**
**NextJS App with SSR**

2021-11-18T20:33:39.795Z [INFO]: Starting SSR Build...
2021-11-18T20:35:40.717Z [ERROR]: ResourceConflictException: The operation cannot be performed at this time. The resource arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:XXXXXXX-XXXXXXX is currently in the following state: 'Pending'. StateReasonCode: 'Creating'
                                  at Object.extractError (/root/.//node_modules/aws-sdk/lib/protocol/json.js:52:27)
                                  at Request.extractError (/root/.//node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)
                                  at Request.callListeners (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/aws-sdk/lib/request.js:686:14)
                                  at Request.transition (/root/.//node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/aws-sdk/lib/request.js:688:12) {
                                  code: 'ResourceConflictException',
                                  time: 2021-11-18T20:35:40.462Z,
                                  requestId: 'ff05dac1-dc03-485d-bbc0-194649bfbc5b',
                                  statusCode: 409,
                                  retryable: false,
                                  retryDelay: 21.868593834976103
                                  }
2021-11-18T20:35:40.719Z [ERROR]: [G[?25h[G[J
                                  91s › dxcsl9yl77cw6 › ResourceConflictException: The operation cannot be performed at this time. The resource arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:XXXXXXX-XXXXXXX is currently in the following state: 'Pending'. StateReasonCode: 'Creating'
                                  [G[?25h

### Expected behavior

Build to move on to next stage i.e. Deploy.

### Reproduction steps

1. Connect branch to deploy in amplify "Frontend environments".
2. Commit NextJS app with SSR.
3. Passes provision.
4. Passes at Cloning repository substage under build.
5. Passes at Backend substage under build.
6. Fails at Frontend substage with error: ResourceConflictException.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by ferdingler** [comment]
@jain-kushal can you try updating to **Next.js** `latest` on the Live Package Update section of your build settings. Here are the instructions: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#update-app-nextjs-version

**Comment by hloriana** [comment]
@jain-kushal If you are still running into this build problem after updating, feel free to re-open this issue.

**Comment by jain-kushal** [comment]
Hey @ferdingler 
I deleted the app from amplify console and now it builds successfully. But it looks like a bug for sure. Thanks!

**Comment by cebrakadabra** [comment]
@jain-kushal as mentioned by @ferdingler and as mentioned here: https://github.com/aws-amplify/amplify-console/issues/2393 once you update *NextJS* to `latest` within the Live Package Update Section of your Amplify App you can resolve this issue temporarily. The issue linked shows that a solution is been worked on. Thanks for raising, helped me resolving it as well.

**Comment by hloriana** [comment]
The fix has been pushed out for this issue. Closing.
