### ISSUE TITLE
Hooks throw error

### ISSUE THREAD

**Issue by SteeveGL** [aws-amplify/amplify-hosting#2492]
**Please describe which feature you have a question about?**
Amplify build

**Provide additional details**
Even the packages are present and works on my machine, in the build process the hook return an error:
```
internal/modules/cjs/loader.js:905
                                 throw err;
                                 ^
                                 Error: Cannot find module '@aws-sdk/client-cloudformation'
                                 Require stack:
                                 - /codebuild/output/src091757404/src/REDACTED/amplify/hooks/post-pull.js
                                 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
                                 at Function.Module._load (internal/modules/cjs/loader.js:746:27)
                                 at Module.require (internal/modules/cjs/loader.js:974:19)
                                 at require (internal/modules/cjs/helpers.js:93:18)
                                 at Object.<anonymous> (/codebuild/output/src091757404/src/REDACTED/amplify/hooks/post-pull.js:4:5)
                                 at Module._compile (internal/modules/cjs/loader.js:1085:14)
                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
                                 at Module.load (internal/modules/cjs/loader.js:950:32)
                                 at Function.Module._load (internal/modules/cjs/loader.js:790:12)
                                 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
                                 code: 'MODULE_NOT_FOUND',
                                 requireStack: [
                                 '/codebuild/output/src091757404/src/REDACTED/amplify/hooks/post-pull.js'
                                 ]
                                 }
```

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**
```
// package.json
{
  "name": "hooks",
  "description": "Command hooks can be used to run custom scripts upon Amplify CLI lifecycle events like pre-push, post-add-function, etc.",
  "version": "1.0.0",
  "dependencies": {
    "@aws-sdk/client-cloudformation": "^3.45.0",
    "@aws-sdk/client-cognito-identity-provider": "^3.45.0",
    "@aws-sdk/client-ssm": "^3.45.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "type": "module"
}
```

```
//post-pull.js
import {
  CloudFormationClient,
  DescribeStackResourceCommand,
} from "@aws-sdk/client-cloudformation";
import {
  CognitoIdentityProviderClient,
  AdminGetUserCommand,
  AdminCreateUserCommand,
  AdminSetUserPasswordCommand,
  AdminAddUserToGroupCommand,
  CreateGroupCommand,
} from "@aws-sdk/client-cognito-identity-provider";
import {
  SSMClient,
  GetParameterCommand,
  PutParameterCommand,
} from "@aws-sdk/client-ssm";
import { readFileSync } from "fs";

const parameters = JSON.parse(readFileSync(0, { encoding: "utf8" }));
console.log(parameters.data, parameters.error);

...
```

```
//amplify.yml
version: 1

backend:
  phases:
    preBuild:
      commands:
        - export PROJECT_DIR=$PWD
        - cd amplify/hooks && npm install
        - cd $PROJECT_DIR
        - ls -la amplify/hooks
        - ls -la amplify/hooks/node_modules

    build:
      commands:
        - amplifyPush --simple
...
```

```
//build log
...
2022-01-06T22:20:34.684Z [INFO]: # Done patching NPM package '@aws-amplify/cli' to version 7.6.5
2022-01-06T22:20:34.697Z [INFO]: # Retrieving cache...
2022-01-06T22:20:42.260Z [INFO]: # Extracting cache...
2022-01-06T22:20:53.009Z [INFO]: # Extraction completed
                                 # Starting phase: preBuild
                                 # Executing command: export PROJECT_DIR=/codebuild/output/src919231335/src/REDACTED
                                 # Executing command: cd amplify/hooks && npm install
2022-01-06T22:21:02.066Z [WARNING]: npm
2022-01-06T22:21:02.066Z [WARNING]: WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2022-01-06T22:21:04.429Z [WARNING]: npm
2022-01-06T22:21:04.430Z [WARNING]: WARN hooks@1.0.0 No repository field.
2022-01-06T22:21:04.431Z [INFO]: added 69 packages from 11 contributors and audited 69 packages in 2.391s
2022-01-06T22:21:04.476Z [INFO]: 2 packages are looking for funding
                                 run `npm fund` for details
2022-01-06T22:21:04.476Z [INFO]: found 0 vulnerabilities
2022-01-06T22:21:04.486Z [INFO]: # Executing command: cd /codebuild/output/src919231335/src/REDACTED
2022-01-06T22:21:04.505Z [INFO]: # Executing command: ls -la amplify/hooks
2022-01-06T22:21:04.507Z [INFO]: total 68
                                 drwxr-xr-x  3 root root  4096 Jan  6 22:21 .
                                 drwxr-xr-x  5 root root  4096 Jan  6 22:17 ..
                                 -rw-r--r--  1 root root    53 Jan  6 22:17 hooks-config.json
                                 drwxr-xr-x 10 root root  4096 Jan  6 22:21 node_modules
                                 -rw-r--r--  1 root root   515 Jan  6 22:21 package.json
                                 -rw-r--r--  1 root root 35421 Jan  6 22:21 package-lock.json
                                 -rw-r--r--  1 root root  6992 Jan  6 22:17 post-list-env.js
                                 -rw-r--r--  1 root root   412 Jan  6 22:17 README.md
2022-01-06T22:21:04.507Z [INFO]: # Executing command: ls -la amplify/hooks/node_modules
2022-01-06T22:21:04.509Z [INFO]: total 40
                                 drwxr-xr-x 10 root root 4096 Jan  6 22:21 .
                                 drwxr-xr-x  3 root root 4096 Jan  6 22:21 ..
                                 drwxr-xr-x  7 root root 4096 Jan  6 22:21 @aws-crypto
                                 drwxr-xr-x 56 root root 4096 Jan  6 22:21 @aws-sdk
                                 drwxr-xr-x  2 root root 4096 Jan  6 22:21 .bin
                                 drwxr-xr-x  3 root root 4096 Jan  6 22:21 bowser
                                 drwxr-xr-x  3 root root 4096 Jan  6 22:21 entities
                                 drwxr-xr-x  3 root root 4096 Jan  6 22:21 fast-xml-parser
                                 drwxr-xr-x  3 root root 4096 Jan  6 22:21 tslib
                                 drwxr-xr-x  3 root root 4096 Jan  6 22:21 uuid
2022-01-06T22:21:04.509Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2022-01-06T22:21:15.068Z [INFO]: [0mAmplify AppID found: dy8aury226seq. Amplify App name is: REDACTED[0m
2022-01-06T22:21:15.147Z [INFO]: [0mBackend environment prhd found in Amplify Console app: REDACTED[0m
2022-01-06T22:21:16.615Z [WARNING]: - Fetching updates to backend environment: prhd from the cloud.
2022-01-06T22:21:17.401Z [WARNING]: - Building resource api/REDACTED
2022-01-06T22:21:18.223Z [INFO]: [32mGraphQL schema compiled successfully.[39m
                                 [32mEdit your schema at /codebuild/output/src919231335/src/REDACTED/amplify/backend/api/REDACTED/schema.graphql or place .graphql files in a directory at /codebuild/output/src919231335/src/REDACTED/amplify/backend/api/REDACTED/schema[39m
2022-01-06T22:21:18.226Z [WARNING]: - Building resource api/REDACTEDStripe
2022-01-06T22:21:18.269Z [WARNING]: - Building resource auth/REDACTEDb0a6fba2
2022-01-06T22:21:18.325Z [WARNING]: ✔ Successfully pulled backend environment prhd from the cloud.
2022-01-06T22:21:18.360Z [INFO]: 
2022-01-06T22:21:18.481Z [INFO]: 
2022-01-06T22:21:18.482Z [INFO]: ----- 🪝 post-pull execution start -----
2022-01-06T22:21:18.534Z [INFO]: 🛑 internal/modules/cjs/loader.js:905
                                 throw err;
                                 ^
                                 Error: Cannot find module '@aws-sdk/client-cloudformation'
                                 Require stack:
                                 - /codebuild/output/src919231335/src/REDACTED/amplify/hooks/post-pull.js
                                 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
                                 at Function.Module._load (internal/modules/cjs/loader.js:746:27)
                                 at Module.require (internal/modules/cjs/loader.js:974:19)
                                 at require (internal/modules/cjs/helpers.js:93:18)
                                 at Object.<anonymous> (/codebuild/output/src919231335/src/REDACTED/amplify/hooks/post-pull.js:4:5)
                                 at Module._compile (internal/modules/cjs/loader.js:1085:14)
                                 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
                                 at Module.load (internal/modules/cjs/loader.js:950:32)
                                 at Function.Module._load (internal/modules/cjs/loader.js:790:12)
                                 at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
                                 code: 'MODULE_NOT_FOUND',
                                 requireStack: [
                                 '/codebuild/output/src919231335/src/REDACTED/amplify/hooks/post-pull.js'
                                 ]
                                 }
2022-01-06T22:21:18.535Z [INFO]: 🛑 post-pull hook script exited with exit code 1
                                 🛑 exiting Amplify process...
2022-01-06T22:21:18.559Z [ERROR]: !!! Build failed
2022-01-06T22:21:18.559Z [ERROR]: !!! Non-Zero Exit Code detected
2022-01-06T22:21:18.559Z [INFO]: # Starting environment caching...
2022-01-06T22:21:18.559Z [INFO]: # Uploading environment cache artifact...
2022-01-06T22:21:18.625Z [INFO]: # Environment caching completed
Terminating logging...
```

```
files in /codebuild/output/src091757404/src/REDACTED/amplify/hooks
2022-01-06T17:01:56.848Z [INFO]: # Executing command: ls -la node_modules/@aws-sdk
2022-01-06T17:01:56.851Z [INFO]: total 224
                                 drwxr-xr-x 56 root root 4096 Jan  6 17:01 .
                                 drwxr-xr-x 10 root root 4096 Jan  6 17:01 ..
                                 drwxr-xr-x  5 root root 4096 Jan  6 17:01 abort-controller
                                 drwxr-xr-x  5 root root 4096 Jan  6 17:01 client-cloudformation
                                 drwxr-xr-x  5 root root 4096 Jan  6 17:01 client-cognito-identity-provider
                                 drwxr-xr-x  5 root root 4096 Jan  6 17:01 client-ssm
                                 drwxr-xr-x  5 root root 4096 Jan  6 17:01 client-sso
                                 drwxr-xr-x  5 root root 4096 Jan  6 17:01 client-sts
...
```

**Comment by hloriana** [comment]
Hi @SteeveGL 👋🏽, thank you for raising this issue. I will investigate this and provide an update shortly.

**Comment by hloriana** [comment]
Hi @SteeveGL, can you provide the App ID and region your app is deployed in so we can further investigate?

**Comment by banut1** [comment]
Hi, did you manage to fix this? I'm encountering the same issue, it only happens for the amplify CI/CD. 
In my case, when I first connect a branch to a new environment, it works fine. But on all subsequent commits that trigger the deployment, I get 
🛑 internal/process/esm_loader.js:74
                                 internalBinding('errors').triggerUncaughtException(
                                 ^
                                 Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@aws-sdk/client-cognito-identity-provider' imported from /codebuild/output/src132381109/src/passbrains/amplify/hooks/test-users.js
                                 at new NodeError (internal/errors.js:322:7)
                                 at packageResolve (internal/modules/esm/resolve.js:687:9)
                                 at moduleResolve (internal/modules/esm/resolve.js:728:18)
                                 at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
                                 at Loader.resolve (internal/modules/esm/loader.js:89:40)
                                 at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
                                 at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
                                 at link (internal/modules/esm/module_job.js:75:36) {
                                 code: 'ERR_MODULE_NOT_FOUND'
                                 }
2022-03-01T12:57:53.332Z [INFO]: 🛑 post-push hook script exited with exit code 1
                                 🛑 exiting Amplify process...
I also noticed the s3 deployment bucket doesn't refresh the files inside the hooks folder, so editing the hooks is not taken into account.

**Comment by victorccccc** [comment]
Hi, can you try to edit `amplify/hooks/hooks-config.json` and remove  `"node_modules"` from `ignore` as a workaround?

```
{
  "ignore": ["node_modules", "build"]
}
```

Thanks

**Comment by banut1** [comment]
Hi. Thanks, this works for me for now. However, further changes to the script are still not taken into account. The deploment bucket is not updated with the new files.
I will write the scenarios that I tried, because not all worked, maybe it helps others:

1. already existing environment, deployed with hooks-config.json containing node_modules
- build 1 - **success**
- build 2 - **fail** with the error above
- removed node_modules from hooks-config.json - build 3 - **fail** with the error above

2. new environment, deployed from the start with hooks-config.json without node_modules
- build 1 - **success**
- build 2 with code changes to the hook - **success**, but the old version of the script is running

**Comment by hloriana** [comment]
Hi @banut1 we were able to reproduce this issue. You can update the hooks by running `amplify push` locally. We are tracking this as a bug.

**Comment by josefaidt** [comment]
Hey @banut1 to add on to @hloriana 's comment above we were able to reproduce using the following steps:

1. `amplify init -y`, `git init` , `gh repo create`...
2. `amplify add hosting` > CI/CD, connect to git
3. push to git, which will trigger a build
4. add a command hook (`post-pull.js`, for example)
5. push to git, which will trigger a build
6. notice hook doesn't get executed nor is it present in s3 deployment bucket
7. locally run `amplify push` 
8. observe command hooks are now uploaded

Unfortunately I was not able to find a suitable workaround for executing command hooks in the Hosting pipeline. As you noted simply changing directories and installing node modules ourselves doesn't mitigate the issue.

```yml
version: 1
backend:
  phases:
    preBuild:
      commands: []
    build:
      commands:
        - cd amplify/hooks; npm i; cd -
        - ls -al amplify/hooks/node_modules
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    build:
      commands: []
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []
```

![image](https://user-images.githubusercontent.com/5033303/161590833-cca93f0e-6df3-4e27-af86-d1c59f86c777.png)

**Comment by swaminator** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/2429410/189757935-318ff282-ff2d-4f5a-8371-97ea447743a8.png">
@SteeveGL We have addressed this issue by requiring the hooks folder to be checked into src control. Amplify CLI will no longer try and replace the hooks folder during the build.
