### ISSUE TITLE
Deploying Nextjs app on AWS: Build fails

### ISSUE THREAD

**Issue by igloopigloo** [aws-amplify/amplify-hosting#2621]
Hi,

I am trying to deploy my nextjs app on aws through github repository. But the build is failing and giving me below pasted message. In terms of aws services, I am using auth, appsync, s3 storage. The whole app is working fine on localhost but I need to deploy it to aws for the whole team. 

Can someone please tell me what am I doing wrong? I have pasted structure of my package.json. 

**My package.json looks like:
{
  "name": "data-app",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build & next export",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@aws-amplify/ui-react": "^1.2.26",
    "aws-amplify": "^4.3.14",
    "next": "12.0.10",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-markdown": "^8.0.0",
    "react-router-dom": "^6.2.2",
    "react-simplemde-editor": "^5.0.2",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.2",
    "eslint": "8.9.0",
    "eslint-config-next": "12.0.10",
    "postcss": "^8.4.6",
    "tailwindcss": "^3.0.23"
  }
}**

**Error message from build in aws amplify:**

2022-03-07T19:43:50.544Z [INFO]: WARN @aws-amplify/codegen-ui-react@1.2.0 requires a peer of react@^17.0.2 but none is installed. You must install peer dependencies yourself.
2022-03-07T19:43:50.553Z [INFO]: npm
2022-03-07T19:43:50.553Z [INFO]: WARN @aws-amplify/codegen-ui-react@1.2.0 requires a peer of react-dom@^17.0.2 but none is installed. You must install peer dependencies yourself.
2022-03-07T19:43:50.553Z [INFO]: 
2022-03-07T19:43:50.609Z [INFO]: # Done patching NPM package '@aws-amplify/cli' to version 7.6.23
2022-03-07T19:43:50.616Z [INFO]: # Retrieving cache...
2022-03-07T19:43:50.649Z [INFO]: # Extracting cache...
2022-03-07T19:43:50.659Z [INFO]: # Extraction completed
                                 # Starting phase: build
2022-03-07T19:43:56.496Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2022-03-07T19:43:57.964Z [INFO]: Amplify AppID found: d1gpeca41jkctg. Amplify App name is: demo-next-app
2022-03-07T19:43:58.120Z [INFO]: Adding backend environment main to AWS Amplify app: d1gpeca41jkctg
2022-03-07T19:43:58.180Z [WARNING]: - Initializing project in the cloud...
2022-03-07T19:44:03.587Z [INFO]: 
2022-03-07T19:44:03.589Z [INFO]: CREATE_IN_PROGRESS amplify-dataapp-main-194357 AWS::CloudFormation::Stack Mon Mar 07 2022 19:43:58 GMT+0000 (Coordinated Universal Time) User Initiated
2022-03-07T19:44:08.584Z [INFO]: 
2022-03-07T19:44:08.586Z [INFO]: CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Mon Mar 07 2022 19:44:04 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UnauthRole       AWS::IAM::Role  Mon Mar 07 2022 19:44:04 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS AuthRole         AWS::IAM::Role  Mon Mar 07 2022 19:44:04 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UnauthRole       AWS::IAM::Role  Mon Mar 07 2022 19:44:05 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Mon Mar 07 2022 19:44:05 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS AuthRole         AWS::IAM::Role  Mon Mar 07 2022 19:44:05 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2022-03-07T19:44:23.580Z [INFO]: 
2022-03-07T19:44:23.584Z [INFO]: CREATE_COMPLETE UnauthRole AWS::IAM::Role Mon Mar 07 2022 19:44:18 GMT+0000 (Coordinated Universal Time)
                                 CREATE_COMPLETE AuthRole   AWS::IAM::Role Mon Mar 07 2022 19:44:20 GMT+0000 (Coordinated Universal Time)
2022-03-07T19:44:28.593Z [INFO]: 
2022-03-07T19:44:28.594Z [INFO]: CREATE_COMPLETE DeploymentBucket AWS::S3::Bucket Mon Mar 07 2022 19:44:27 GMT+0000 (Coordinated Universal Time)
2022-03-07T19:44:33.598Z [INFO]: 
2022-03-07T19:44:33.599Z [INFO]: CREATE_COMPLETE amplify-dataapp-main-194357 AWS::CloudFormation::Stack Mon Mar 07 2022 19:44:29 GMT+0000 (Coordinated Universal Time)
2022-03-07T19:44:58.736Z [WARNING]: ✔ Successfully created initial AWS cloud resources for deployments.
2022-03-07T19:44:58.869Z [WARNING]: - Uploading files...
2022-03-07T19:44:58.936Z [WARNING]: - Uploading files...
2022-03-07T19:44:59.029Z [WARNING]: - Uploading files...
2022-03-07T19:44:59.286Z [WARNING]: - Initializing your environment: main
2022-03-07T19:44:59.286Z [WARNING]: ✔ Initialized provider successfully.
2022-03-07T19:44:59.686Z [INFO]: ⚠️  WARNING: your GraphQL API currently allows public create, read, update, and delete access to all models via an API Key. To configure PRODUCTION-READY authorization rules, review: https://docs.amplify.aws/cli/graphql/authorization-rules
2022-03-07T19:45:00.124Z [INFO]: GraphQL schema compiled successfully.
                                 Edit your schema at /codebuild/output/src812440592/src/demo-next-app/amplify/backend/api/dataapp/schema.graphql or place .graphql files in a directory at /codebuild/output/src812440592/src/demo-next-app/amplify/backend/api/dataapp/schema
2022-03-07T19:45:00.133Z [WARNING]: - Building resource api/dataapp
2022-03-07T19:45:00.251Z [INFO]: ⚠️  WARNING: your GraphQL API currently allows public create, read, update, and delete access to all models via an API Key. To configure PRODUCTION-READY authorization rules, review: https://docs.amplify.aws/cli/graphql/authorization-rules
2022-03-07T19:45:00.573Z [INFO]: GraphQL schema compiled successfully.
                                 Edit your schema at /codebuild/output/src812440592/src/demo-next-app/amplify/backend/api/dataapp/schema.graphql or place .graphql files in a directory at /codebuild/output/src812440592/src/demo-next-app/amplify/backend/api/dataapp/schema
2022-03-07T19:45:00.575Z [WARNING]: - Building resource auth/dataapp1a2515b8
2022-03-07T19:45:00.626Z [WARNING]: - Building resource storage/postimages
2022-03-07T19:45:00.726Z [WARNING]: - Uploading files...
2022-03-07T19:45:01.048Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2022-03-07T19:45:07.044Z [INFO]: 
2022-03-07T19:45:07.047Z [INFO]: UPDATE_IN_PROGRESS amplify-dataapp-main-194357 AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:01 GMT+0000 (Coordinated Universal Time) User Initiated
2022-03-07T19:45:12.094Z [INFO]: 
2022-03-07T19:45:12.095Z [INFO]: CREATE_IN_PROGRESS authdataapp1a2515b8            AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:09 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS hostingamplifyhosting          AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:09 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionRole AWS::IAM::Role             Mon Mar 07 2022 19:45:09 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS storagepostimages              AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:10 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UpdateRolesWithIDPFunctionRole AWS::IAM::Role             Mon Mar 07 2022 19:45:10 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS hostingamplifyhosting          AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:10 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS authdataapp1a2515b8            AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:10 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_IN_PROGRESS storagepostimages              AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:11 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2022-03-07T19:45:12.141Z [INFO]: 
2022-03-07T19:45:12.141Z [INFO]: CREATE_IN_PROGRESS amplify-dataapp-main-194357-storagepostimages-1X38OFDV31YO2 AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:11 GMT+0000 (Coordinated Universal Time) User Initiated
2022-03-07T19:45:12.246Z [INFO]: 
2022-03-07T19:45:12.247Z [INFO]: CREATE_IN_PROGRESS amplify-dataapp-main-194357-authdataapp1a2515b8-1QSXZDQAW1VMM AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:10 GMT+0000 (Coordinated Universal Time) User Initiated
2022-03-07T19:45:12.341Z [INFO]: 
2022-03-07T19:45:12.341Z [INFO]: CREATE_IN_PROGRESS amplify-dataapp-main-194357-hostingamplifyhosting-1OBVZY28830J9 AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:10 GMT+0000 (Coordinated Universal Time) User Initiated
2022-03-07T19:45:17.321Z [INFO]: 
2022-03-07T19:45:17.322Z [INFO]: CREATE_IN_PROGRESS AmplifyBranch AWS::Amplify::Branch Mon Mar 07 2022 19:45:15 GMT+0000 (Coordinated Universal Time)
2022-03-07T19:45:22.053Z [INFO]: 
**2022-03-07T19:45:22.055Z [INFO]: _CREATE_FAILED hostingamplifyhosting          AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:21 GMT+0000 (Coordinated Universal Time) Embedded stack arn:aws:cloudformation:us-east-1:984348161056:stack/amplify-dataapp-main-194357-hostingamplifyhosting-1OBVZY28830J9/193e6fd0-9e4f-11ec-9f3c-0ab6a86326e3 was not successfully created: The following resource(s) failed to create: [AmplifyBranch].
                                 CREATE_FAILED UpdateRolesWithIDPFunctionRole AWS::IAM::Role             Mon Mar 07 2022 19:45:21 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
2022-03-07T19:45:22.133Z [INFO]: 
2022-03-07T19:45:22.134Z [INFO]: CREATE_FAILED AmplifyBranch                                                   AWS::Amplify::Branch       Mon Mar 07 2022 19:45:18 GMT+0000 (Coordinated Universal Time) Resource handler returned message: "Invalid request provided: Failed to create branch. The branch main already exists for the app d1gpeca41jkctg (Service: Amplify, Status Code: 400, Request ID: 2b88d833-130b-42cc-9f99-0a60c17c1613, Extended Request ID: null)" (RequestToken: da4bb552-3242-556b-8791-aefc22d2e96f, HandlerErrorCode: InvalidRequest)
                                 CREATE_FAILED amplify-dataapp-main-194357-hostingamplifyhosting-1OBVZY28830J9 AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:19 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to create: [AmplifyBranch]._**
2022-03-07T19:45:22.224Z [INFO]: 
2022-03-07T19:45:22.225Z [INFO]: CREATE_IN_PROGRESS S3Bucket AWS::S3::Bucket Mon Mar 07 2022 19:45:17 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS S3Bucket AWS::S3::Bucket Mon Mar 07 2022 19:45:18 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
2022-03-07T19:45:22.329Z [INFO]: 
2022-03-07T19:45:22.330Z [INFO]: CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Mon Mar 07 2022 19:45:18 GMT+0000 (Coordinated Universal Time)
                                 CREATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Mon Mar 07 2022 19:45:20 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
                                 CREATE_COMPLETE    UserPool AWS::Cognito::UserPool Mon Mar 07 2022 19:45:21 GMT+0000 (Coordinated Universal Time)
2022-03-07T19:45:22.442Z [INFO]: 
2022-03-07T19:45:22.443Z [INFO]: CREATE_FAILED authdataapp1a2515b8 AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:21 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
                                 CREATE_FAILED storagepostimages   AWS::CloudFormation::Stack Mon Mar 07 2022 19:45:21 GMT+0000 (Coordinated Universal Time) Resource creation cancelled
2022-03-07T19:45:27.082Z [INFO]: 
   at IncomingMessage.emit (events.js:412:35)
                                 at IncomingMessage.emit (domain.js:475:12)
                                 at endReadableNT (internal/streams/readable.js:1334:12)
                                 at processTicksAndRejections (internal/process/task_queues.js:82:21) {
                                 code: 'ResourceNotReady',
                                 retryable: false,
                                 time: 2022-03-07T19:48:02.665Z,
                                 statusCode: 200,
                                 retryDelay: 30000
                                 }
2022-03-07T19:48:07.695Z [ERROR]: !!! Build failed
2022-03-07T19:48:07.696Z [ERROR]: !!! Non-Zero Exit Code detected
2022-03-07T19:48:07.696Z [INFO]: # Starting environment caching...
2022-03-07T19:48:07.696Z [INFO]: # Environment caching completed

My backend deployment gives me these information:
![image](https://user-images.githubusercontent.com/101135348/157110966-9a0d5686-93d8-444b-bcf9-afd7554580cd.png)

Can someone please help me with this? Or just guide me from where to start? I will really appreciate any direction, any guidance.

Thanks,
IP

**Comment by igloopigloo** [comment]
Hi,

I am updating my question. Sorry for any inconvenience. But I found what was the issue and why I was getting backend error. My configuration was not correct, so I rectified that. But my build is still failing and I am getting frontend error.

**Please see below pasted error:**. As you can see from the error, it suggests building the app. I tried that too, but it didn't help.

My appid is d2jqfqeg91useg. My region is 'us-east-1'.

data-app@ build /codebuild/output/src755519296/src/demo-next-app
                                 > next build & next export
2022-03-07T20:37:08.752Z [INFO]: Attention: Next.js now collects completely anonymous telemetry regarding usage.
2022-03-07T20:37:08.752Z [INFO]: This information is used to shape Next.js' roadmap and prioritize features.
                                 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
                                 https://nextjs.org/telemetry
2022-03-07T20:37:08.888Z [INFO]: info  - using build directory: /codebuild/output/src755519296/src/demo-next-app/.next
2022-03-07T20:37:08.890Z [WARNING]: **_Error: Could not find a production build in the '/codebuild/output/src755519296/src/demo-next-app/.next' directory. Try building your app with 'next build' before starting the static export. https://nextjs.org/docs/messages/next-export-no-build-id
                                    at /codebuild/output/src755519296/src/demo-next-app/node_modules/next/dist/export/index.js:158:19
                                    at async Span.traceAsyncFn (/codebuild/output/src755519296/src/demo-next-app/node_modules/next/dist/trace/trace.js:75:20)_**
2022-03-07T20:37:08.906Z [WARNING]: npm
2022-03-07T20:37:08.906Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
2022-03-07T20:37:08.911Z [WARNING]: npm
2022-03-07T20:37:08.911Z [WARNING]: ERR! data-app@ build: `next build & next export`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the data-app@ build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-03-07T20:37:08.919Z [WARNING]: 
2022-03-07T20:37:08.919Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2022-03-07T20_37_08_911Z-debug.log
2022-03-07T20:37:08.919Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [
                                 1 verbose cli   '/root/.nvm/versions/node/v14.18.1/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v14.18.1/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build'
                                 1 verbose cli ]
                                 2 info using npm@6.14.15
                                 3 info using node@v14.18.1
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle data-app@~prebuild: data-app@
                                 6 info lifecycle data-app@~build: data-app@
                                 7 verbose lifecycle data-app@~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle data-app@~build: PATH: /root/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src755519296/src/demo-next-app/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.nvm/versions/node/v14.18.1/bin:/root/.local/bin:/root/.local/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
                                 9 verbose lifecycle data-app@~build: CWD: /codebuild/output/src755519296/src/demo-next-app
                                 10 silly lifecycle data-app@~build: Args: [ '-c', 'next build & next export' ]
                                 11 silly lifecycle data-app@~build: Returned: code: 1  signal: null
                                 12 info lifecycle data-app@~build: Failed to exec build script
                                 13 verbose stack Error: data-app@ build: `next build & next export`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:400:28)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:400:28)
                                 13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
                                 14 verbose pkgid data-app@
                                 15 verbose cwd /codebuild/output/src755519296/src/demo-next-app
                                 16 verbose Linux 4.14.252-195.483.amzn2.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v14.18.1/bin/node" "/root/.nvm/versions/node/v14.18.1/bin/npm" "run" "build"
                                 18 verbose node v14.18.1
                                 19 verbose npm  v6.14.15
                                 20 error code ELIFECYCLE
                                 21 error errno 1
                                 22 error data-app@ build: `next build & next export`
                                 22 error Exit status 1
                                 23 error Failed at the data-app@ build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2022-03-07T20:37:08.923Z [ERROR]: !!! Build failed
2022-03-07T20:37:08.923Z [ERROR]: !!! Non-Zero Exit Code detected
2022-03-07T20:37:08.923Z [INFO]: # Starting environment caching...
2022-03-07T20:37:08.924Z [INFO]: # Environment caching completed
Terminating logging...
2022-03-07T20:37:11.548Z [INFO]: info  - Checking validity of types...
                                 ./pages/about.js
                                 10:13  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
                                 ./pages/contact.js
                                 124:11  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
                                 ./pages/create-post.js
                                 72:17  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
                                 72:17  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
                                 ./pages/create-posta.js
                                 130:21  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
                                 130:21  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
                                 ./pages/edit-post/[id].js
                                 90:9  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
                                 90:9  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
                                 ./pages/edit-posta/[id].js
                                 92:9  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
                                 92:9  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
                                 ./pages/my-postsa.js
                                 45:6  Warning: React Hook useEffect has a missing dependency: 'fetchPosts'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
                                 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
                                 info  - Creating an optimized production build...

**Comment by igloopigloo** [comment]
npm run build gives me following error:
Error: Could not find a production build in the 'C:\Users\sh55451\Documents\UGA\brookdodo\data-app\.next' directory. Try building your app with 'next build' before starting the static export. https://nextjs.org/docs/messages/next-export-no-build-id
    at C:\Users\sh55451\Documents\UGA\brookdodo\data-app\node_modules\next\dist\export\index.js:158:19
    at async Span.traceAsyncFn (C:\Users\sh55451\Documents\UGA\brookdodo\data-app\node_modules\next\dist\trace\trace.js:75:20)

**Comment by hloriana** [comment]
Hi @igloopigloo 👋🏽 we are looking into this, will update with more information shortly

**Comment by hloriana** [comment]
There's a typo in your package.json. 
Replace `"build": "next build & next export",` with `"build": "next build && next export",` (logical AND)

**Comment by igloopigloo** [comment]
Hi,

That did fixed the issue, but now when I am deploying it to aws, it is throwing backend error. Please see below pasted message. I googled the error and did following steps:
npm cache clean --force
delete node_modules and package-lock.json
npm install
npm start
npm run dev

Again the whole thing is working fine on localhost but deployment is failing
The error is:
2022-03-09T18:50:17.846Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
2022-03-09T18:50:17.849Z [WARNING]: npm
2022-03-09T18:50:17.849Z [WARNING]: ERR! data-app@ build: `next build && next export`
                                    npm ERR! Exit status 1
                                    npm ERR!
                                    npm ERR! Failed at the data-app@ build script.
                                    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-03-09T18:50:17.854Z [WARNING]: 
2022-03-09T18:50:17.854Z [WARNING]: npm ERR! A complete log of this run can be found in:
                                    npm ERR!     /root/.npm/_logs/2022-03-09T18_50_17_849Z-debug.log
2022-03-09T18:50:17.854Z [HELP]: Outputting the npm debug log
                                 0 info it worked if it ends with ok
                                 1 verbose cli [
                                 1 verbose cli   '/root/.nvm/versions/node/v14.18.1/bin/node',
                                 1 verbose cli   '/root/.nvm/versions/node/v14.18.1/bin/npm',
                                 1 verbose cli   'run',
                                 1 verbose cli   'build'
                                 1 verbose cli ]
                                 2 info using npm@6.14.15
                                 3 info using node@v14.18.1
                                 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
                                 5 info lifecycle data-app@~prebuild: data-app@
                                 6 info lifecycle data-app@~build: data-app@
                                 7 verbose lifecycle data-app@~build: unsafe-perm in lifecycle true
                                 8 verbose lifecycle data-app@~build: PATH: /root/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/codebuild/output/src736534747/src/demo-next-app/node_modules/.bin:/usr/local/rvm/gems/ruby-2.4.6/bin:/usr/local/rvm/gems/ruby-2.4.6@global/bin:/usr/local/rvm/rubies/ruby-2.4.6/bin:/usr/local/rvm/bin:/root/.nvm/versions/node/v14.18.1/bin:/root/.local/bin:/root/.local/bin:/root/.local/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
                                 9 verbose lifecycle data-app@~build: CWD: /codebuild/output/src736534747/src/demo-next-app
                                 10 silly lifecycle data-app@~build: Args: [ '-c', 'next build && next export' ]
                                 11 silly lifecycle data-app@~build: Returned: code: 1  signal: null
                                 12 info lifecycle data-app@~build: Failed to exec build script
                                 13 verbose stack Error: data-app@ build: `next build && next export`
                                 13 verbose stack Exit status 1
                                 13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
                                 13 verbose stack     at EventEmitter.emit (events.js:400:28)
                                 13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
                                 13 verbose stack     at ChildProcess.emit (events.js:400:28)
                                 13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
                                 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
                                 14 verbose pkgid data-app@
                                 15 verbose cwd /codebuild/output/src736534747/src/demo-next-app
                                 16 verbose Linux 4.14.252-195.483.amzn2.x86_64
                                 17 verbose argv "/root/.nvm/versions/node/v14.18.1/bin/node" "/root/.nvm/versions/node/v14.18.1/bin/npm" "run" "build"
                                 18 verbose node v14.18.1
                                 19 verbose npm  v6.14.15
                                 **_20 error code ELIFECYCLE_**
                                 **_21 error errno 1
                                 22 error data-app@ build: `next build && next export`
                                 22 error Exit status 1_**
                                 23 error Failed at the data-app@ build script.
                                 23 error This is probably not a problem with npm. There is likely additional logging output above.
                                 24 verbose exit [ 1, true ]
2022-03-09T18:50:17.858Z [ERROR]: !!! Build failed
2022-03-09T18:50:17.858Z [ERROR]: !!! Non-Zero Exit Code detected
2022-03-09T18:50:17.858Z [INFO]: # Starting environment caching...
2022-03-09T18:50:17.859Z [INFO]: # Environment caching completed

Can you please help me out.

Thanks

**Comment by hloriana** [comment]
You said your app runs locally but can you ensure that it builds locally as well. If it cannot build locally then the issue is most likely with the configuration of the app.

**Comment by hloriana** [comment]
Please
