### ISSUE TITLE
Building backend with a Lambda Shared Layer

### ISSUE THREAD

**Issue by bmw46033** [aws-amplify/amplify-hosting#2640]
**Please describe which feature you have a question about?**
Lambda Layers and Auto Build

**Provide additional details**
I created and added a lambda layer.  With amplify push, all works swimingly.  When I try to deploy, however, I appear to get an error looking for a file in the node_modules of my layer. Do I need to adjust the build settings to install the node modules for this layer?

Also, what I am concerned about is the log below looks like it tries to repeat several times and ultimately throw the copy file error.  So, I am thinking the issues is with my Lambda Layer that failed after 3 attempts.

**What AWS Services are you utilizing?**
Amplify Functions with Lambda Layers

**Provide additional details e.g. code snippets**
Build settings:
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install -g npm@latest
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

Produces this build output:

2022-03-10T21:06:21.404Z [INFO]: # Cloning repository: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/FourKeypsV2
2022-03-10T21:06:21.922Z [INFO]: Cloning into 'FourKeypsV2'...
2022-03-10T21:06:31.018Z [INFO]: remote:
2022-03-10T21:06:32.224Z [INFO]: remote: Counting objects: 0
2022-03-10T21:06:32.333Z [INFO]: remote: Counting objects: 675
2022-03-10T21:06:32.364Z [INFO]: remote: Counting objects: 675
remote: Counting objects: 675, done.
2022-03-10T21:06:34.715Z [INFO]: Receiving objects:   0% (1/675)
2022-03-10T21:06:34.717Z [INFO]: Receiving objects:   1% (7/675)
Receiving objects:   2% (14/675)
Receiving objects:   3% (21/675)
Receiving objects:   4% (27/675)
Receiving objects:   5% (34/675)
Receiving objects:   6% (41/675)
Receiving objects:   7% (48/675)
Receiving objects:   8% (54/675)
2022-03-10T21:06:34.720Z [INFO]: Receiving objects:   9% (61/675)
Receiving objects:  10% (68/675)
Receiving objects:  11% (75/675)
Receiving objects:  12% (81/675)
Receiving objects:  13% (88/675)
Receiving objects:  14% (95/675)
Receiving objects:  15% (102/675)
Receiving objects:  16% (108/675)
2022-03-10T21:06:34.720Z [INFO]: Receiving objects:  17% (115/675)
2022-03-10T21:06:34.728Z [INFO]: Receiving objects:  18% (122/675)
2022-03-10T21:06:34.729Z [INFO]: Receiving objects:  19% (129/675)
Receiving objects:  20% (135/675)
Receiving objects:  21% (142/675)
Receiving objects:  22% (149/675)
Receiving objects:  23% (156/675)
Receiving objects:  24% (162/675)
Receiving objects:  25% (169/675)
Receiving objects:  26% (176/675)
Receiving objects:  27% (183/675)
2022-03-10T21:06:34.729Z [INFO]: Receiving objects:  28% (189/675)
2022-03-10T21:06:34.738Z [INFO]: Receiving objects:  29% (196/675)
2022-03-10T21:06:34.738Z [INFO]: Receiving objects:  30% (203/675)
Receiving objects:  31% (210/675)
Receiving objects:  32% (216/675)
Receiving objects:  33% (223/675)
Receiving objects:  34% (230/675)
Receiving objects:  35% (237/675)
2022-03-10T21:06:34.738Z [INFO]: Receiving objects:  36% (243/675)
Receiving objects:  37% (250/675)
Receiving objects:  38% (257/675)
2022-03-10T21:06:34.738Z [INFO]: Receiving objects:  39% (264/675)
2022-03-10T21:06:34.740Z [INFO]: Receiving objects:  40% (270/675)
2022-03-10T21:06:34.740Z [INFO]: Receiving objects:  41% (277/675)
2022-03-10T21:06:34.741Z [INFO]: Receiving objects:  42% (284/675)
2022-03-10T21:06:34.744Z [INFO]: Receiving objects:  43% (291/675)
2022-03-10T21:06:34.761Z [INFO]: Receiving objects:  44% (297/675)
2022-03-10T21:06:34.785Z [INFO]: Receiving objects:  45% (304/675)
2022-03-10T21:06:34.788Z [INFO]: Receiving objects:  46% (311/675)
2022-03-10T21:06:34.790Z [INFO]: Receiving objects:  47% (318/675)
2022-03-10T21:06:34.791Z [INFO]: Receiving objects:  48% (324/675)
2022-03-10T21:06:34.793Z [INFO]: Receiving objects:  49% (331/675)
2022-03-10T21:06:34.794Z [INFO]: Receiving objects:  50% (338/675)
2022-03-10T21:06:34.796Z [INFO]: Receiving objects:  51% (345/675)
2022-03-10T21:06:34.834Z [INFO]: Receiving objects:  52% (351/675)
2022-03-10T21:06:34.836Z [INFO]: Receiving objects:  53% (358/675)
2022-03-10T21:06:34.837Z [INFO]: Receiving objects:  54% (365/675)
2022-03-10T21:06:34.838Z [INFO]: Receiving objects:  55% (372/675)
2022-03-10T21:06:34.840Z [INFO]: Receiving objects:  56% (378/675)
2022-03-10T21:06:34.842Z [INFO]: Receiving objects:  57% (385/675)
2022-03-10T21:06:34.842Z [INFO]: Receiving objects:  58% (392/675)
2022-03-10T21:06:34.844Z [INFO]: Receiving objects:  59% (399/675)
2022-03-10T21:06:34.845Z [INFO]: Receiving objects:  60% (405/675)
2022-03-10T21:06:34.846Z [INFO]: Receiving objects:  61% (412/675)
2022-03-10T21:06:34.846Z [INFO]: Receiving objects:  62% (419/675)
2022-03-10T21:06:34.849Z [INFO]: Receiving objects:  63% (426/675)
2022-03-10T21:06:34.849Z [INFO]: Receiving objects:  64% (432/675)
2022-03-10T21:06:34.850Z [INFO]: Receiving objects:  65% (439/675)
2022-03-10T21:06:34.851Z [INFO]: Receiving objects:  66% (446/675)
2022-03-10T21:06:34.851Z [INFO]: Receiving objects:  67% (453/675)
2022-03-10T21:06:34.853Z [INFO]: Receiving objects:  68% (459/675)
2022-03-10T21:06:34.853Z [INFO]: Receiving objects:  69% (466/675)
2022-03-10T21:06:34.855Z [INFO]: Receiving objects:  70% (473/675)
2022-03-10T21:06:34.855Z [INFO]: Receiving objects:  71% (480/675)
Receiving objects:  72% (486/675)
2022-03-10T21:06:34.858Z [INFO]: Receiving objects:  73% (493/675)
2022-03-10T21:06:34.858Z [INFO]: Receiving objects:  74% (500/675)
2022-03-10T21:06:34.860Z [INFO]: Receiving objects:  75% (507/675)
2022-03-10T21:06:34.860Z [INFO]: Receiving objects:  76% (513/675)
Receiving objects:  77% (520/675)
2022-03-10T21:06:34.861Z [INFO]: Receiving objects:  78% (527/675)
2022-03-10T21:06:34.862Z [INFO]: Receiving objects:  79% (534/675)
2022-03-10T21:06:34.864Z [INFO]: Receiving objects:  80% (540/675)
2022-03-10T21:06:34.865Z [INFO]: Receiving objects:  81% (547/675)
Receiving objects:  82% (554/675)
2022-03-10T21:06:34.874Z [INFO]: Receiving objects:  83% (561/675)
2022-03-10T21:06:34.874Z [INFO]: Receiving objects:  84% (567/675)
Receiving objects:  85% (574/675)
2022-03-10T21:06:34.875Z [INFO]: Receiving objects:  86% (581/675)
Receiving objects:  87% (588/675)
2022-03-10T21:06:34.875Z [INFO]: Receiving objects:  88% (594/675)
2022-03-10T21:06:34.875Z [INFO]: Receiving objects:  89% (601/675)
2022-03-10T21:06:34.878Z [INFO]: Receiving objects:  90% (608/675)
2022-03-10T21:06:34.878Z [INFO]: Receiving objects:  91% (615/675)
Receiving objects:  92% (621/675)
Receiving objects:  93% (628/675)
2022-03-10T21:06:34.883Z [INFO]: Receiving objects:  94% (635/675)
2022-03-10T21:06:34.883Z [INFO]: Receiving objects:  95% (642/675)
Receiving objects:  96% (648/675)
Receiving objects:  97% (655/675)
2022-03-10T21:06:34.883Z [INFO]: Receiving objects:  98% (662/675)
Receiving objects:  99% (669/675)
Receiving objects: 100% (675/675)
Receiving objects: 100% (675/675), 1.21 MiB | 7.20 MiB/s, done.
2022-03-10T21:06:34.883Z [INFO]: Resolving deltas:   0% (0/293)
Resolving deltas:   1% (3/293)
2022-03-10T21:06:34.884Z [INFO]: Resolving deltas:   2% (6/293)
Resolving deltas:   3% (9/293)
Resolving deltas:   4% (12/293)
Resolving deltas:   5% (15/293)
Resolving deltas:   6% (18/293)
Resolving deltas:   7% (21/293)
Resolving deltas:   8% (24/293)
Resolving deltas:   9% (27/293)
Resolving deltas:  10% (30/293)
2022-03-10T21:06:34.884Z [INFO]: Resolving deltas:  11% (33/293)
Resolving deltas:  12% (36/293)
Resolving deltas:  13% (39/293)
Resolving deltas:  14% (42/293)
Resolving deltas:  15% (44/293)
Resolving deltas:  16% (47/293)
Resolving deltas:  17% (50/293)
Resolving deltas:  18% (53/293)
Resolving deltas:  19% (56/293)
Resolving deltas:  20% (59/293)
2022-03-10T21:06:34.884Z [INFO]: Resolving deltas:  21% (62/293)
Resolving deltas:  22% (65/293)
Resolving deltas:  23% (68/293)
Resolving deltas:  24% (71/293)
Resolving deltas:  25% (74/293)
Resolving deltas:  26% (77/293)
Resolving deltas:  27% (80/293)
Resolving deltas:  28% (83/293)
Resolving deltas:  29% (85/293)
Resolving deltas:  30% (88/293)
Resolving deltas:  31% (91/293)
Resolving deltas:  32% (94/293)
Resolving deltas:  33% (97/293)
Resolving deltas:  34% (100/293)
2022-03-10T21:06:34.884Z [INFO]: Resolving deltas:  35% (103/293)
Resolving deltas:  36% (106/293)
Resolving deltas:  37% (109/293)
Resolving deltas:  38% (112/293)
Resolving deltas:  39% (115/293)
Resolving deltas:  40% (118/293)
Resolving deltas:  41% (121/293)
Resolving deltas:  42% (124/293)
Resolving deltas:  43% (126/293)
Resolving deltas:  44% (129/293)
Resolving deltas:  45% (132/293)
Resolving deltas:  46% (135/293)
2022-03-10T21:06:34.892Z [INFO]: Resolving deltas:  47% (138/293)
Resolving deltas:  48% (141/293)
Resolving deltas:  49% (144/293)
Resolving deltas:  50% (147/293)
Resolving deltas:  51% (150/293)
Resolving deltas:  52% (153/293)
Resolving deltas:  53% (156/293)
Resolving deltas:  54% (159/293)
Resolving deltas:  55% (162/293)
Resolving deltas:  56% (165/293)
Resolving deltas:  57% (168/293)
Resolving deltas:  58% (170/293)
Resolving deltas:  59% (173/293)
Resolving deltas:  60% (176/293)
Resolving deltas:  61% (179/293)
Resolving deltas:  62% (182/293)
Resolving deltas:  63% (185/293)
Resolving deltas:  64% (188/293)
Resolving deltas:  65% (191/293)
Resolving deltas:  66% (194/293)
Resolving deltas:  67% (197/293)
Resolving deltas:  68% (200/293)
Resolving deltas:  69% (203/293)
Resolving deltas:  70% (206/293)
Resolving deltas:  71% (209/293)
Resolving deltas:  72% (211/293)
Resolving deltas:  73% (214/293)
Resolving deltas:  74% (217/293)
Resolving deltas:  75% (220/293)
Resolving deltas:  76% (223/293)
Resolving deltas:  77% (226/293)
Resolving deltas:  78% (229/293)
Resolving deltas:  79% (232/293)
Resolving deltas:  80% (235/293)
Resolving deltas:  81% (238/293)
Resolving deltas:  82% (241/293)
Resolving deltas:  83% (244/293)
Resolving deltas:  84% (247/293)
Resolving deltas:  85% (250/293)
Resolving deltas:  86% (252/293)
Resolving deltas:  87% (255/293)
Resolving deltas:  88% (258/293)
Resolving deltas:  89% (261/293)
Resolving deltas:  90% (264/293)
Resolving deltas:  91% (267/293)
Resolving deltas:  92% (270/293)
Resolving deltas:  93% (273/293)
Resolving deltas:  94% (276/293)
Resolving deltas:  95% (279/293)
Resolving deltas:  96% (282/293)
Resolving deltas:  97% (285/293)
2022-03-10T21:06:34.900Z [INFO]: Resolving deltas:  98% (288/293)
2022-03-10T21:06:34.911Z [INFO]: Resolving deltas:  99% (291/293)
2022-03-10T21:06:34.918Z [INFO]: Resolving deltas: 100% (293/293)
2022-03-10T21:06:34.918Z [INFO]: Resolving deltas: 100% (293/293), done.
2022-03-10T21:06:35.003Z [INFO]: # Switching to commit: fb82534631104b224c9a0839c5f019dbf0a933b0
2022-03-10T21:06:35.019Z [INFO]: Note: switching to 'fb82534631104b224c9a0839c5f019dbf0a933b0'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
                                 HEAD is now at fb82534 purchase statement
2022-03-10T21:06:35.049Z [INFO]: Successfully cleaned up Git credentials
2022-03-10T21:06:35.049Z [INFO]: # Checking for Git submodules at: /codebuild/output/src601873443/src/FourKeypsV2/.gitmodules
2022-03-10T21:06:35.073Z [INFO]: # Retrieving environment cache...
2022-03-10T21:06:35.347Z [INFO]: # Retrieved environment cache
2022-03-10T21:06:35.348Z [INFO]: ---- Setting Up SSM Secrets ----
2022-03-10T21:06:35.348Z [INFO]: SSM params {"Path":"/amplify/d34ze1bai06tnh/dev/","WithDecryption":true}
2022-03-10T21:06:42.376Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 6.3.1 to 7.6.23...
022-03-10T21:06:21.404Z [INFO]: # Cloning repository: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/FourKeypsV2
2022-03-10T21:06:21.922Z [INFO]: Cloning into 'FourKeypsV2'...
2022-03-10T21:06:31.018Z [INFO]: remote:
2022-03-10T21:06:32.224Z [INFO]: remote: Counting objects: 0
2022-03-10T21:06:32.333Z [INFO]: remote: Counting objects: 675
2022-03-10T21:06:32.364Z [INFO]: remote: Counting objects: 675
remote: Counting objects: 675, done.
2022-03-10T21:06:34.715Z [INFO]: Receiving objects:   0% (1/675)
2022-03-10T21:06:34.717Z [INFO]: Receiving objects:   1% (7/675)
Receiving objects:   2% (14/675)
Receiving objects:   3% (21/675)
Receiving objects:   4% (27/675)
Receiving objects:   5% (34/675)
Receiving objects:   6% (41/675)
Receiving objects:   7% (48/675)
Receiving objects:   8% (54/675)
2022-03-10T21:06:34.720Z [INFO]: Receiving objects:   9% (61/675)
Receiving objects:  10% (68/675)
Receiving objects:  11% (75/675)
Receiving objects:  12% (81/675)
Receiving objects:  13% (88/675)
Receiving objects:  14% (95/675)
Receiving objects:  15% (102/675)
Receiving objects:  16% (108/675)
2022-03-10T21:06:34.720Z [INFO]: Receiving objects:  17% (115/675)
2022-03-10T21:06:34.728Z [INFO]: Receiving objects:  18% (122/675)
2022-03-10T21:06:34.729Z [INFO]: Receiving objects:  19% (129/675)
Receiving objects:  20% (135/675)
Receiving objects:  21% (142/675)
Receiving objects:  22% (149/675)
Receiving objects:  23% (156/675)
Receiving objects:  24% (162/675)
Receiving objects:  25% (169/675)
Receiving objects:  26% (176/675)
Receiving objects:  27% (183/675)
2022-03-10T21:06:34.729Z [INFO]: Receiving objects:  28% (189/675)
2022-03-10T21:06:34.738Z [INFO]: Receiving objects:  29% (196/675)
2022-03-10T21:06:34.738Z [INFO]: Receiving objects:  30% (203/675)
Receiving objects:  31% (210/675)
Receiving objects:  32% (216/675)
Receiving objects:  33% (223/675)
Receiving objects:  34% (230/675)
Receiving objects:  35% (237/675)
2022-03-10T21:06:34.738Z [INFO]: Receiving objects:  36% (243/675)
Receiving objects:  37% (250/675)
Receiving objects:  38% (257/675)
2022-03-10T21:06:34.738Z [INFO]: Receiving objects:  39% (264/675)
2022-03-10T21:06:34.740Z [INFO]: Receiving objects:  40% (270/675)
2022-03-10T21:06:34.740Z [INFO]: Receiving objects:  41% (277/675)
2022-03-10T21:06:34.741Z [INFO]: Receiving objects:  42% (284/675)
2022-03-10T21:06:34.744Z [INFO]: Receiving objects:  43% (291/675)
2022-03-10T21:06:34.761Z [INFO]: Receiving objects:  44% (297/675)
2022-03-10T21:06:34.785Z [INFO]: Receiving objects:  45% (304/675)
2022-03-10T21:06:34.788Z [INFO]: Receiving objects:  46% (311/675)
2022-03-10T21:06:34.790Z [INFO]: Receiving objects:  47% (318/675)
2022-03-10T21:06:34.791Z [INFO]: Receiving objects:  48% (324/675)
2022-03-10T21:06:34.793Z [INFO]: Receiving objects:  49% (331/675)
2022-03-10T21:06:34.794Z [INFO]: Receiving objects:  50% (338/675)
2022-03-10T21:06:34.796Z [INFO]: Receiving objects:  51% (345/675)
2022-03-10T21:06:34.834Z [INFO]: Receiving objects:  52% (351/675)
2022-03-10T21:06:34.836Z [INFO]: Receiving objects:  53% (358/675)
2022-03-10T21:06:34.837Z [INFO]: Receiving objects:  54% (365/675)
2022-03-10T21:06:34.838Z [INFO]: Receiving objects:  55% (372/675)
2022-03-10T21:06:34.840Z [INFO]: Receiving objects:  56% (378/675)
2022-03-10T21:06:34.842Z [INFO]: Receiving objects:  57% (385/675)
2022-03-10T21:06:34.842Z [INFO]: Receiving objects:  58% (392/675)
2022-03-10T21:06:34.844Z [INFO]: Receiving objects:  59% (399/675)
2022-03-10T21:06:34.845Z [INFO]: Receiving objects:  60% (405/675)
2022-03-10T21:06:34.846Z [INFO]: Receiving objects:  61% (412/675)
2022-03-10T21:06:34.846Z [INFO]: Receiving objects:  62% (419/675)
2022-03-10T21:06:34.849Z [INFO]: Receiving objects:  63% (426/675)
2022-03-10T21:06:34.849Z [INFO]: Receiving objects:  64% (432/675)
2022-03-10T21:06:34.850Z [INFO]: Receiving objects:  65% (439/675)
2022-03-10T21:06:34.851Z [INFO]: Receiving objects:  66% (446/675)
2022-03-10T21:06:34.851Z [INFO]: Receiving objects:  67% (453/675)
2022-03-10T21:06:34.853Z [INFO]: Receiving objects:  68% (459/675)
2022-03-10T21:06:34.853Z [INFO]: Receiving objects:  69% (466/675)
2022-03-10T21:06:34.855Z [INFO]: Receiving objects:  70% (473/675)
2022-03-10T21:06:34.855Z [INFO]: Receiving objects:  71% (480/675)
Receiving objects:  72% (486/675)
2022-03-10T21:06:34.858Z [INFO]: Receiving objects:  73% (493/675)
2022-03-10T21:06:34.858Z [INFO]: Receiving objects:  74% (500/675)
2022-03-10T21:06:34.860Z [INFO]: Receiving objects:  75% (507/675)
2022-03-10T21:06:34.860Z [INFO]: Receiving objects:  76% (513/675)
Receiving objects:  77% (520/675)
2022-03-10T21:06:34.861Z [INFO]: Receiving objects:  78% (527/675)
2022-03-10T21:06:34.862Z [INFO]: Receiving objects:  79% (534/675)
2022-03-10T21:06:34.864Z [INFO]: Receiving objects:  80% (540/675)
2022-03-10T21:06:34.865Z [INFO]: Receiving objects:  81% (547/675)
Receiving objects:  82% (554/675)
2022-03-10T21:06:34.874Z [INFO]: Receiving objects:  83% (561/675)
2022-03-10T21:06:34.874Z [INFO]: Receiving objects:  84% (567/675)
Receiving objects:  85% (574/675)
2022-03-10T21:06:34.875Z [INFO]: Receiving objects:  86% (581/675)
Receiving objects:  87% (588/675)
2022-03-10T21:06:34.875Z [INFO]: Receiving objects:  88% (594/675)
2022-03-10T21:06:34.875Z [INFO]: Receiving objects:  89% (601/675)
2022-03-10T21:06:34.878Z [INFO]: Receiving objects:  90% (608/675)
2022-03-10T21:06:34.878Z [INFO]: Receiving objects:  91% (615/675)
Receiving objects:  92% (621/675)
Receiving objects:  93% (628/675)
2022-03-10T21:06:34.883Z [INFO]: Receiving objects:  94% (635/675)
2022-03-10T21:06:34.883Z [INFO]: Receiving objects:  95% (642/675)
Receiving objects:  96% (648/675)
Receiving objects:  97% (655/675)
2022-03-10T21:06:34.883Z [INFO]: Receiving objects:  98% (662/675)
Receiving objects:  99% (669/675)
Receiving objects: 100% (675/675)
Receiving objects: 100% (675/675), 1.21 MiB | 7.20 MiB/s, done.
2022-03-10T21:06:34.883Z [INFO]: Resolving deltas:   0% (0/293)
Resolving deltas:   1% (3/293)
2022-03-10T21:06:34.884Z [INFO]: Resolving deltas:   2% (6/293)
Resolving deltas:   3% (9/293)
Resolving deltas:   4% (12/293)
Resolving deltas:   5% (15/293)
Resolving deltas:   6% (18/293)
Resolving deltas:   7% (21/293)
Resolving deltas:   8% (24/293)
Resolving deltas:   9% (27/293)
Resolving deltas:  10% (30/293)
2022-03-10T21:06:34.884Z [INFO]: Resolving deltas:  11% (33/293)
Resolving deltas:  12% (36/293)
Resolving deltas:  13% (39/293)
Resolving deltas:  14% (42/293)
Resolving deltas:  15% (44/293)
Resolving deltas:  16% (47/293)
Resolving deltas:  17% (50/293)
Resolving deltas:  18% (53/293)
Resolving deltas:  19% (56/293)
Resolving deltas:  20% (59/293)
2022-03-10T21:06:34.884Z [INFO]: Resolving deltas:  21% (62/293)
Resolving deltas:  22% (65/293)
Resolving deltas:  23% (68/293)
Resolving deltas:  24% (71/293)
Resolving deltas:  25% (74/293)
Resolving deltas:  26% (77/293)
Resolving deltas:  27% (80/293)
Resolving deltas:  28% (83/293)
Resolving deltas:  29% (85/293)
Resolving deltas:  30% (88/293)
Resolving deltas:  31% (91/293)
Resolving deltas:  32% (94/293)
Resolving deltas:  33% (97/293)
Resolving deltas:  34% (100/293)
2022-03-10T21:06:34.884Z [INFO]: Resolving deltas:  35% (103/293)
Resolving deltas:  36% (106/293)
Resolving deltas:  37% (109/293)
Resolving deltas:  38% (112/293)
Resolving deltas:  39% (115/293)
Resolving deltas:  40% (118/293)
Resolving deltas:  41% (121/293)
Resolving deltas:  42% (124/293)
Resolving deltas:  43% (126/293)
Resolving deltas:  44% (129/293)
Resolving deltas:  45% (132/293)
Resolving deltas:  46% (135/293)
2022-03-10T21:06:34.892Z [INFO]: Resolving deltas:  47% (138/293)
Resolving deltas:  48% (141/293)
Resolving deltas:  49% (144/293)
Resolving deltas:  50% (147/293)
Resolving deltas:  51% (150/293)
Resolving deltas:  52% (153/293)
Resolving deltas:  53% (156/293)
Resolving deltas:  54% (159/293)
Resolving deltas:  55% (162/293)
Resolving deltas:  56% (165/293)
Resolving deltas:  57% (168/293)
Resolving deltas:  58% (170/293)
Resolving deltas:  59% (173/293)
Resolving deltas:  60% (176/293)
Resolving deltas:  61% (179/293)
Resolving deltas:  62% (182/293)
Resolving deltas:  63% (185/293)
Resolving deltas:  64% (188/293)
Resolving deltas:  65% (191/293)
Resolving deltas:  66% (194/293)
Resolving deltas:  67% (197/293)
Resolving deltas:  68% (200/293)
Resolving deltas:  69% (203/293)
Resolving deltas:  70% (206/293)
Resolving deltas:  71% (209/293)
Resolving deltas:  72% (211/293)
Resolving deltas:  73% (214/293)
Resolving deltas:  74% (217/293)
Resolving deltas:  75% (220/293)
Resolving deltas:  76% (223/293)
Resolving deltas:  77% (226/293)
Resolving deltas:  78% (229/293)
Resolving deltas:  79% (232/293)
Resolving deltas:  80% (235/293)
Resolving deltas:  81% (238/293)
Resolving deltas:  82% (241/293)
Resolving deltas:  83% (244/293)
Resolving deltas:  84% (247/293)
Resolving deltas:  85% (250/293)
Resolving deltas:  86% (252/293)
Resolving deltas:  87% (255/293)
Resolving deltas:  88% (258/293)
Resolving deltas:  89% (261/293)
Resolving deltas:  90% (264/293)
Resolving deltas:  91% (267/293)
Resolving deltas:  92% (270/293)
Resolving deltas:  93% (273/293)
Resolving deltas:  94% (276/293)
Resolving deltas:  95% (279/293)
Resolving deltas:  96% (282/293)
Resolving deltas:  97% (285/293)
2022-03-10T21:06:34.900Z [INFO]: Resolving deltas:  98% (288/293)
2022-03-10T21:06:34.911Z [INFO]: Resolving deltas:  99% (291/293)
2022-03-10T21:06:34.918Z [INFO]: Resolving deltas: 100% (293/293)
2022-03-10T21:06:34.918Z [INFO]: Resolving deltas: 100% (293/293), done.
2022-03-10T21:06:35.003Z [INFO]: # Switching to commit: fb82534631104b224c9a0839c5f019dbf0a933b0
2022-03-10T21:06:35.019Z [INFO]: Note: switching to 'fb82534631104b224c9a0839c5f019dbf0a933b0'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
                                 HEAD is now at fb82534 purchase statement
2022-03-10T21:06:35.049Z [INFO]: Successfully cleaned up Git credentials
2022-03-10T21:06:35.049Z [INFO]: # Checking for Git submodules at: /codebuild/output/src601873443/src/FourKeypsV2/.gitmodules
2022-03-10T21:06:35.073Z [INFO]: # Retrieving environment cache...
2022-03-10T21:06:35.347Z [INFO]: # Retrieved environment cache
2022-03-10T21:06:35.348Z [INFO]: ---- Setting Up SSM Secrets ----
2022-03-10T21:06:35.348Z [INFO]: SSM params {"Path":"/amplify/d34ze1bai06tnh/dev/","WithDecryption":true}
2022-03-10T21:06:42.376Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 6.3.1 to 7.6.23...
2022-03-10T21:07:29.661Z [INFO]: npm
fs-extra/lib/copy-sync/copy-sync.js:113:23)
                                 at mkDirAndCopy (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
                                 at onDir (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
                                 at getStats (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
                                 at startCopy (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
                                 at copyDirItem (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
                                 at /root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
                                 at Array.forEach (<anonymous>)
                                 at copyDir (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
                                 at mkDirAndCopy (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:108:3)
                                 at onDir (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:99:25)
                                 at getStats (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
                                 at startCopy (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
                                 at copyDirItem (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
                                 at /root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
                                 at Array.forEach (<anonymous>)
                                 at copyDir (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
                                 at onDir (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
                                 at getStats (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
                                 at startCopy (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
                                 at handleFilterAndCopy (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
                                 at Object.copySync (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
                                 at downloadBackend (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/attach-backend.js:369:8)
                                 at Object.run (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/attach-backend.js:78:3)
                                 at Object.attachBackend (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.ts:62:3)
                                 at queryProvider (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a10-queryProvider.ts:12:3)
                                 at attachBackend (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:20:5)
                                 at Object.run (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:63:5)
                                 at Object.executeAmplifyCommand (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
                                 at executePluginModuleCommand (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:178:3)
                                 at executeCommand (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:30:5)
                                 at Object.run (/root/.nvm/versions/node/v14.18.1/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)
2022-03-10T21:11:37.625Z [ERROR]: !!! Build failed
2022-03-10T21:11:37.626Z [ERROR]: !!! Non-Zero Exit Code detected
2022-03-10T21:11:37.626Z [INFO]: # Starting environment caching...
2022-03-10T21:11:37.627Z [INFO]: # Uploading environment cache artifact...
2022-03-10T21:11:37.695Z [INFO]: # Environment caching completed
Terminating logging...

**Comment by hloriana** [comment]
Hello, apologies for the delay in response. If you're still running into this behavior please create a new issue with the [bug report template](https://github.com/aws-amplify/amplify-hosting/issues/new?assignees=&labels=&template=1.bug_report.yaml) (please provide the app ID) so that we may better assist you.
