### ISSUE TITLE
Next.js Rewrites object with `fallback` option causes 503 ERROR

### ISSUE THREAD

**Issue by sleukhin** [aws-amplify/amplify-hosting#2701]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3kyx257i4bn04

### Region

us-east-1

### Amplify Hosting feature

Not applicable

### Describe the bug

There is 503 ERROR while attempting to access pages on the Next.js application with [Next.js Rewrites rules](https://nextjs.org/docs/api-reference/next.config.js/rewrites) and the `fallback` option.

Next.js Rewrites/Redirects feature is good to have for incremental adoption Nextjs application.

**Details:**
I'm getting the error when options `beforeFiles`, `afterFiles` or `fallback` are used:
```
module.exports = {
  async rewrites() {
    return {
      beforeFiles: [],
      afterFiles: [],
      fallback: [],
    };
  },
};
```

There is no issue with the simple syntax:
```
module.exports = {
  async rewrites() {
    return [];
  },
};
```

**Error in browser**
```
503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution is invalid or doesn't have the required permissions. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: -----
```

**Error in Lambda function**
```
ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "rewrites is not iterable",
    "stack": [
        "TypeError: rewrites is not iterable",
        "    at getRewritePath (/var/task/default-handler-0a0dc009.js:1366:27)",
        "    at handlePageReq (/var/task/default-handler-0a0dc009.js:1300:35)",
        "    at routeDefault (/var/task/default-handler-0a0dc009.js:1808:16)",
        "    at async handleDefault (/var/task/default-handler-0a0dc009.js:1884:19)",
        "    at async handleOriginRequest (/var/task/default-handler-0a0dc009.js:103067:19)",
        "    at async Runtime.handler (/var/task/default-handler-0a0dc009.js:102994:20)"
    ]
}
```

### Expected behavior

All features/syntaxes of [Next.js Rewrites rules](https://nextjs.org/docs/api-reference/next.config.js/rewrites) are working properly.

If the syntax with `beforeFiles`, `afterFiles`, `fallback` is not supported just for now, please add this information to [unsupported features](https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html) and mark this issue as a feature request.

### Reproduction steps

1. Create a Next.js Application with only one `/` page for simplicity
2. Add Rewrites to `next.config.js`
```
module.exports = {
  async rewrites() {
    return {
      fallback: [
        {
          source: '/:path*',
          destination: `https://nextjs.org/:path*`,
        },
      ],
    };
  },
};
```
3. Deploy the app with Amplify
4. Try to navigate to the `/blog` page.

**Comment by hloriana** [comment]
Hi @sleukhin 👋🏽 I was able to reproduce this behavior. Currently investigating if we support this and if theres a workaround.

**Comment by lwang-79** [comment]
Hi team,

Do you have any update on this issue? I got the same error when configuring with fallback. Is there a work around for the rewrite fallback feature with Amplify hosting?

**Comment by maheshauti96** [comment]
We have a Nextjs app where we fallback some pages to php.
php asset do not load if we just add a redirect for a single URL.
to achieve this we need Amplify to support Nextjs Fallback.
please add its support or share workaround asap

**Comment by nathanoertel** [comment]
Similar situation as @maheshauti96 , would love to know if anyone has found a workaround for this or if this is not supported.

**Comment by aslaker** [comment]
Biiiiig ++ on this.  We need fallback support as we are incrementally adopting NextJS.  This will likely cause us to drop Amplify all together and go with another solution.

**Comment by msalmanshahid** [comment]
Any update on this please?

**Comment by rkingonnw** [comment]
+1

**Comment by aslaker** [comment]
+3
