### ISSUE TITLE
pipenv install fails for no apparent reason (same commit worked last week)

### ISSUE THREAD

**Issue by wvidana** [aws-amplify/amplify-hosting#2725]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

`XXXremovedXXX`

### Region

eu-west-1

### Amplify Hosting feature

Backend builds

### Describe the bug

`pipenv` is failing, but only on the Amplify CI/CD build, if I do a push locally it works perfectly. No new changes introduced, the same commit was successful a week before.

Here the error
```
Failed to install some dependency or packages.  The following have failed installation and attempted retry: [Requirement(_name='src', vcs=None, req=FileRequirement(setup_path=None, path='./src', editable=True, extras=None, _uri_scheme='path', uri='file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src', link=<Link file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src>, pyproject_requires=(), pyproject_backend=None, pyproject_path=None, subdirectory=None, _setup_info=SetupInfo(name='src', base_dir='/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src', _version='1.0', _requirements=frozenset(), build_requires=('wheel', 'setuptools'), build_backend='setuptools.build_meta:__legacy__', setup_requires=(), python_requires=None, _extras_requirements=(), setup_cfg=PosixPath('/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src/setup.cfg'), setup_py=PosixPath('/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src/setup.py'), pyproject=PosixPath('/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src/pyproject.toml'), ireq=<InstallRequirement object: src==1.0@ file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src from file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src editable=True>, extra_kwargs={'build_dir': '/tmp/reqlib-build91vsty2o', 'src_dir': '/tmp/reqlib-srctppbc9nu', 'download_dir': '/root/.cache/pipenv/pkgs', 'wheel_download_dir': '/root/.cache/pipenv/wheels'}, metadata=None, stack=<contextlib.ExitStack object at 0x7f46b1994b50>, _finalizer=<finalize object at 0x7f46b5f54600; for 'SetupInfo' at 0x7f46b5963720>), _has_hashed_name=False, _parsed_line=<Line (editable=True, name=src, path=/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src, uri=file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src, extras=(), markers=None, vcs=None, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, name='src', req=Requirement.parse('src@ file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src')), markers=None, _specifiers='', index=None, editable=True, hashes=frozenset(), extras=(), abstract_dep=None, _line_instance=<Line (editable=True, name=src, path=/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src, uri=file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src, extras=(), markers=None, vcs=None, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, _ireq=None), Requirement(_name='src', vcs=None, req=FileRequirement(setup_path=None, path='./src', editable=True, extras=None, _uri_scheme='path', uri='file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src', link=<Link file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src>, pyproject_requires=(), pyproject_backend=None, pyproject_path=None, subdirectory=None, _setup_info=SetupInfo(name='src', base_dir='/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src', _version='1.0', _requirements=frozenset(), build_requires=('wheel', 'setuptools'), build_backend='setuptools.build_meta:__legacy__', setup_requires=(), python_requires=None, _extras_requirements=(), setup_cfg=PosixPath('/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src/setup.cfg'), setup_py=PosixPath('/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src/setup.py'), pyproject=PosixPath('/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src/pyproject.toml'), ireq=<InstallRequirement object: src==1.0@ file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src from file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src editable=True>, extra_kwargs={'build_dir': '/tmp/reqlib-build91vsty2o', 'src_dir': '/tmp/reqlib-srctppbc9nu', 'download_dir': '/root/.cache/pipenv/pkgs', 'wheel_download_dir': '/root/.cache/pipenv/wheels'}, metadata=None, stack=<contextlib.ExitStack object at 0x7f46b1994b50>, _finalizer=<finalize object at 0x7f46b5f54600; for 'SetupInfo' at 0x7f46b5963720>), _has_hashed_name=False, _parsed_line=<Line (editable=True, name=src, path=/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src, uri=file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src, extras=(), markers=None, vcs=None, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, name='src', req=Requirement.parse('src@ file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src')), markers=None, _specifiers='', index=None, editable=True, hashes=frozenset(), extras=(), abstract_dep=None, _line_instance=<Line (editable=True, name=src, path=/codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src, uri=file:///codebuild/output/src240005547/src/myapp-amplify/amplify/backend/function/myappUpdateSharedMedias/src, extras=(), markers=None, vcs=None, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=None)>, _ireq=None)]
```

The error from amplifyPush:
```
[INFO]: Error: Command failed with exit code 1: pipenv install
                                 at makeError (/root/.nvm/versions/node/v14.19.0/lib/node_modules/@aws-amplify/cli/node_modules/execa/lib/error.js:60:11)
                                 at handlePromise (/root/.nvm/versions/node/v14.19.0/lib/node_modules/@aws-amplify/cli/node_modules/execa/index.js:118:26)
                                 at runMicrotasks (<anonymous>)
                                 at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                 at Object.pythonBuild [as build] (/root/.nvm/versions/node/v14.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-python-function-runtime-provider/src/util/buildUtils.ts:8:5)
                                 at buildFunction (/root/.nvm/versions/node/v14.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/src/provider-utils/awscloudformation/utils/buildFunction.ts:41:16)
                                 at prepareResource (/root/.nvm/versions/node/v14.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:580:33)
                                 at async Promise.all (index 7)
                                 at prepareBuildableResources (/root/.nvm/versions/node/v14.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:576:10)
                                 at Object.run (/root/.nvm/versions/node/v14.19.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:148:5) {
                                 shortMessage: 'Command failed with exit code 1: pipenv install',
                                 command: 'pipenv install',
                                 escapedCommand: 'pipenv install',
                                 exitCode: 1,
                                 signal: undefined,
                                 signalDescription: undefined,
                                 stdout: undefined,
                                 stderr: undefined,
                                 failed: true,
                                 timedOut: false,
                                 isCanceled: false,
                                 killed: false
                                 }
```

### Expected behavior

`pipenv` should install packages correctly

### Reproduction steps

1. Have an amplify project with Python 3.8 functions
2. Setup CI/CD on the Amplify console
3. ... `pipenv` fails?

### Build Settings

```yaml
version: 1
env:
  variables:
    VERSION_AMPLIFY: 6.4.0
backend:
  phases:
    preBuild:
      commands:
        - npm i -g @aws-amplify/cli@${VERSION_AMPLIFY}
    build:
      commands:
        - echo '{}' > amplify/.config/local-env-info.json
        - amplify -v
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
        - /usr/local/bin/pip3.8 install --user pipenv
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
```

**Comment by hloriana** [comment]
Hi @wvidana and @cdezz can you please provide an App ID so we can investigate the build errors?

**Comment by acn-monilsinghal** [comment]
Same issue here as well App ID - ddivbg1xep66s

**Comment by cdezz** [comment]
> Hi @wvidana and @cdezz can you please provide an App ID so we can investigate the build errors?

Hi @hloriana, my App Id is d3h7ft6bt64jis.

**Comment by wvidana** [comment]
Also, I did some testing in a fresh app, using same amplify CLI version... seems to work fine. So there has to be something in there, maybe a feature flag, or some other generated config. I'm still investigating so I'm unsure what's the issue yet. Does the console do container caching or some other caching for the build environment? Maybe the virtualenv folder gets re-used? It would be useful if the Dockerfile in this repo gets updated so we can debug using the same image locally

**Comment by wvidana** [comment]
Hey @hloriana the issue seems to be from whatever new version of `amplifyPush` AWS is using. The old script (no updates for 2 years) from this repo seems to fix the problem https://github.com/aws-amplify/amplify-hosting/blob/d79d8b814f5b93b0f7c605369c355b90a696f44c/scripts/amplifyPush.sh

Can you please update this repo with the recent script and image? This would help us greatly for future issues

**Comment by cdezz** [comment]
Hi @hloriana do you have any update on this bug?

**Comment by wvidana** [comment]
I'm not entirely sure that my workaround works... I think the old script doesn't work correctly, on my STAGE environment the lambda functions were not updated, and they did have changes in the code as well as the `Pipfile` file

**Comment by falken42** [comment]
We also ran into this issue as well over the weekend.  Whatever changed in the `amplifyPush` script that's called from the build settings / `amplify.yml` results in the same `pipenv install` failure when trying to update dependencies, and we're unable to deploy any previous builds that worked fine in the past.

We did try @wvidana 's suggestion with replacing the default called `amplifyPush` script with the one referenced from two years ago, and while the execution does actually succeed, CloudFormation appears to never be called from it and the AWS environment isn't actually updated.

For now, our only workaround is to do a manual `amplify push` from a local development environment.

**Comment by hloriana** [comment]
Hi everyone, if you're using the latest version of the CLI, try downgrading to an earlier version like 7.5.5

**Comment by hloriana** [comment]
Transferring to CLI team for visibility.

**Comment by wvidana** [comment]
Thanks @hloriana on the update, we are actually using version `6.4.0` since we are not ready for the transformer v2 upgrade yet. Any chance you can update the `amplifyPush.sh` script in the repo? It would be great if we can try to customize a temporary fix in the meantime, or an actual contribution if the fix is right :)

**Comment by wvidana** [comment]
It seems that a recent `pipenv` change was at fault. I haven't run more tests locally, but locking to a previous version with `amplify.yml` did the trick.

```diff
    build:
      commands:
        - echo '{}' > amplify/.config/local-env-info.json
        - amplify -v
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
-      - /usr/local/bin/pip3.8 install --user pipenv
+      - /usr/local/bin/pip3.8 install --user pipenv==2022.4.8
        - pipenv --version
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
```

**Comment by hloriana** [comment]
@wvidana Thank you for this update. I'll sync with team on updating the amplifyPush.sh in the repo and keep you posted.

**Comment by smcalilly** [comment]
i'm having a similar problem, except my pipenv error is saying that my modules are wrong even though i deployed the alleged bad modules less than a month ago. it happens when i commit and push to code commit and the amplify ci/cd deploys. very frustrating, my code change was like two lines and had nothing to do with this.
