### ISSUE TITLE
The request multipart/form-data is truncated unexpectedly if its size exceeds 1mb in Next Js api hosted on Amplify.

### ISSUE THREAD

**Issue by apetrov-monivolt** [aws-amplify/amplify-hosting#2762]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3rm9tzrpvwvtt

### Region

eu-west-2

### Amplify Hosting feature

Not applicable

### Describe the bug

The request multipart/form-data is truncated unexpectedly if its size exceeds 1mb in Next Js api (/api/file-test.ts) hosted on Amplify.

This results in an error when parsing the body. Here is example of error when parsing is done via 'multiparty' but it is similar when another body parser is used.(e.g. busboy):

```
ERROR BadRequestError: stream ended unexpectedly
at Form.<anonymous> (/var/task/chunks/6485.js:795:24)
at Form.emit (events.js:412:35)
at finish (internal/streams/writable.js:657:10)
at finishMaybe (internal/streams/writable.js:644:9)
at afterWrite (internal/streams/writable.js:473:3)
at onwrite (internal/streams/writable.js:446:7)
at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

Everything is ok when request is less then 1 mb. Everything is ok when it is run outside of amplify (e.g. localhost).

> pages/file-test.tsx - form that will be submitted:

```
import type { NextPage } from 'next';
import { useCallback, useRef } from 'react';
import request from '../lib/request';

const TestFile: NextPage = () => {
  const ref = useRef(null);
  const onSave = useCallback((event) => {
    event.preventDefault();
    request('/api/file-test', {
      method: 'POST',
      // @ts-ignore
      body: new FormData(ref.current),
    })
  }, []);
  return (
    <div>
      MULTIPARTY
      <br/>
      <form onSubmit={onSave} ref={ref}>
        <input type="file" name="file1" />
        <input type="file" name="file2" />
        <input type="file" name="file3" />
        <hr/>
        <button type="submit">submit</button>
      </form>
    </div>
  );
}

export default TestFile;
```

> /lib/request.ts:

```
export default async function request(url: string, props: any = { headers: {} }) {
  const params = {
    ...props,
    headers: {
      ...(props.headers || {}),
    }
  };

  const response = await fetch(`${url}`, params);
  return await response.json();
}
```

> pages/api/file-test.ts - api that process request and should return files metadata:

```
import type { NextApiRequest, NextApiResponse } from 'next';
import { Response } from '../../types';
import multiparty from 'multiparty';

type Res = Response<any>;

export default async function myHandler(
  req: NextApiRequest,
  res: NextApiResponse<Res>
) {
  if (req.method === 'POST') {

    try {

      const multipartyForm = new multiparty.Form({ autoFields: true, autoFiles: true });
      const parsedForm = await new Promise((resolve, reject) => {
        // @ts-ignore
        multipartyForm.parse(req, function (err, fields, files) {
          if (err) reject(err);

          resolve({ fields, files });
        });
      });
      // @ts-ignore
      res.status(200).json(parsedForm);
    } catch (err) {
      console.error(err);
      // @ts-ignore
      res.status(500).json({message: err.message});
    }
  } else {
    res.status(405).end();
  }
}


export const config = {
  api: {
    bodyParser: false
  }
}
```

> package.json:
```
{
  "name": "testproject",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@emotion/react": "^11.9.0",
    "@emotion/styled": "^11.8.1",
    "@fontsource/frank-ruhl-libre": "^4.5.7",
    "@fontsource/poppins": "^4.5.8",
    "@mui/icons-material": "^5.6.2",
    "@mui/material": "^5.6.3",
    "@prismicio/client": "^6.4.3",
    "async-busboy": "^1.1.0",
    "axios": "^0.27.2",
    "cookies": "^0.8.0",
    "countries-json": "^1.0.1",
    "formdata-node": "^4.3.2",
    "formidable": "2.0.1",
    "formik": "^2.2.9",
    "got": "^11.8.2",
    "mime-types": "^2.1.35",
    "multiparty": "^4.2.3",
    "next": "^11.1.4",
    "next-auth": "4.0.0-beta.3",
    "next-connect": "^0.12.2",
    "node-fetch": "^3.2.4",
    "prismic-reactjs": "^1.3.4",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-intersection-observer": "^8.33.1",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@types/async-busboy": "^1.1.1",
    "@types/cookies": "^0.7.7",
    "@types/formidable": "^2.0.5",
    "@types/mime-types": "^2.1.1",
    "@types/multiparty": "^0.0.33",
    "@types/node": "17.0.23",
    "@types/react": "17.0.43",
    "@types/react-dom": "17.0.14",
    "eslint": "^8.12.0",
    "eslint-config-next": "12.1.2",
    "typescript": "4.6.3"
  }
}
```

### Expected behavior

Multipart/form-data request is not truncated and can be parsed correctly.

### Reproduction steps

1. create next js project
2. Add files from "Describe the bug" section
3. Host next js project with ssr on Amplify
4. open <domain>/file-test
5. add files larger then 1 mb and submit form

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by hloriana** [comment]
Hi @apetrov-monivolt 👋🏽  thanks for raising this issues. According to our [docs](https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#image-size-limit):

> This is caused by a Lambda@Edge limit that restricts the size of a response that is generated by a Lambda function, including headers and body, to 1 MB.
