### ISSUE TITLE
amplify push can't find java 11 on local machine even after msi install (win10)

### ISSUE THREAD

**Issue by Gcodesmith** [aws-amplify/amplify-hosting#2949]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Hosting feature

Backend builds

### Describe the bug

I am trying to add a hello world api and function for my amplify app. I am using Java 
I understand that I need to install Java 11+ and Gradle 5+ locally before doing a amplify push.

Ref: https://docs.amplify.aws/cli/function/#function-templates

I have done that using the msi provided here: 
https://amzn.to/2UUljp9

when I run 'amplify push' locally using CMD, I see this error
-----------------------
? Are you sure you want to continue? Yes
Update JDK to >=11. Download link: https://amzn.to/2UUljp9
× An error occurred when pushing the resources to the cloud
🛑 An error occurred during the push operation: /
Missing required dependencies to package helloAmplify

when I run 'amplify function build' locally using CMD, I see this error
-----------------------
? Are you sure you want to continue building the resources? Yes
Update JDK to >=11. Download link: https://amzn.to/2UUljp9
Error: Missing required dependencies to package helloAmplify
    at buildFunction (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\provider-utils\awscloudformation\utils\buildFunction.js:13:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\commands\function\build.js:22:43)
    at async Object.executeAmplifyCommand (C:\snapshot\repo\build\node_modules\amplify-category-function\lib\index.js:264:5)
    at async executePluginModuleCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:142:5)
    at async executeCommand (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\execution-manager.js:40:9)
    at async Object.run (C:\snapshot\repo\build\node_modules\@aws-amplify\cli-internal\lib\index.js:165:13)
There was an error building the function resources

java -version output
-----------------------
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
openjdk version "11.0.16.1" 2022-08-12 LTS
OpenJDK Runtime Environment Corretto-11.0.16.9.1 (build 11.0.16.1+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.16.9.1 (build 11.0.16.1+9-LTS, mixed mode)

*Environment Variables*

_JAVA_HOME_
--------------------
C:\Program Files\Amazon Corretto\jdk11.0.16_9

_PATH_
---------------------
C:\Program Files\Amazon Corretto\jdk11.0.16_9\bin

_SYS_
---------------------
Win 10
amplify cli 9.2.1
---------------------

_How do I convince amplify that I have indeed installed Java 11 on my pc?_

### Expected behavior

'amplify push' should succeed without any error since Gradle 7.5 and Java 11 are present on my machine.

### Reproduction steps

1. Create an new amplify project and 
2. then install Java 11 and Gradle 7.5
3. After that try to provision a new Java backend function  

### Additional information

No additional info

**Comment by Gcodesmith** [comment]
**I fixed this issue by remove JAVA_TOOL_OPTIONS from my environment variables.**
I guess it works because maybe Amplify does a string search on the output of java -version to determine the current java version.
Adding JAVA_TOOL_OPTIONS changed the first line of the output and what the checking logic was expecting.

**After this issue was resolved, I ran into another issue with the Amplify generated Gradle build file. (I am using Gradle 7.5)**
changing 'compile' to 'implementation' solved it.
ref: https://stackoverflow.com/questions/23796404/could-not-find-method-compile-for-arguments-gradle

**Finally, I am using a custom image build for my amplify because Java is not support on Amazon Linux 2 at the moment.**
ref:
https://github.com/aws-amplify/amplify-hosting/issues/1368
https://github.com/aws-amplify/amplify-hosting/issues/2776

Hope this info helps anyone using Java as the lang. for their back-end lambdas with Amplify.
