### ISSUE TITLE
Amplify REST API Python error when deploying due to 3.7 in aws build

### ISSUE THREAD

**Issue by entest-hai** [aws-amplify/amplify-hosting#2983]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d8nzd3pgncdfk

### Region

us-east-1

### Amplify Hosting feature

Backend builds, Build settings

### Describe the bug

In local, it can works well. However, it is error when deploying using Amplify hosting CI/CD flow. My app requires python 3.8 for Amplify REST API Python, however, the build image in aws using python 3.7. 

```bash 
 ## Checking for associated backend environment...
                                 ## Backend environment association found
2022-09-12T12:50:25.533Z [INFO]: [0mAmplify AppID found: d8nzd3pgncdfk. Amplify App name is: kendrademo[0m
2022-09-12T12:50:25.592Z [INFO]: [0mBackend environment dev found in Amplify Console app: kendrademo[0m
2022-09-12T12:50:26.094Z [WARNING]: - Fetching updates to backend environment: dev from the cloud.
2022-09-12T12:50:26.635Z [WARNING]: - Building resource api/api1ed17962
2022-09-12T12:50:26.652Z [WARNING]: ✔ Successfully pulled backend environment dev from the cloud.
2022-09-12T12:50:26.665Z [INFO]: ✅
2022-09-12T12:50:27.906Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2022-09-12T12:50:28.711Z [WARNING]: - Initializing your environment: dev
2022-09-12T12:50:29.223Z [WARNING]: - Building resource api/api1ed17962
2022-09-12T12:50:29.239Z [WARNING]: ✔ Initialized provider successfully.
2022-09-12T12:50:29.623Z [INFO]: [31mpython3 found but version Python 3.7.10 is less than the minimum required version.[39m
                                 [31mYou must have python >= 3.8 installed and available on your PATH as "python3" or "python". It can be installed from https://www.python.org/downloads[39m
                                 [31mYou must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".[39m
                                 [31mYou must have virtualenv installed and available on your PATH as "venv". It can be installed by running "pip3 install venv".[39m
2022-09-12T12:50:29.624Z [WARNING]: ✖ There was an error initializing your environment.
2022-09-12T12:50:29.627Z [INFO]: [0mError: Missing required dependencies to package kendrademoda6c4ec6[0m
                                 [0m    at buildFunction (/snapshot/repo/build/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/utils/buildFunction.js:13:15)[0m
                                 [0m    at processTicksAndRejections (internal/process/task_queues.js:95:5)[0m
                                 [0m    at async prepareResource (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:559:33)[0m
                                 [0m    at async Promise.all (index 0)[0m
                                 [0m    at async prepareBuildableResources (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:555:3)[0m
                                 [0m    at async Object.run (/snapshot/repo/build/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:217:5)[0m
2022-09-12T12:50:29.642Z [ERROR]: !!! Build failed
2022-09-12T12:50:29.642Z [ERROR]: !!! Non-Zero Exit Code detected
2022-09-12T12:50:29.642Z [INFO]: # Starting environment caching...
2022-09-12T12:50:29.643Z [INFO]: # Environment caching completed
Terminating logging...
```

### Expected behavior

The aws build image should support python 3.8 so it can works for Amplify Rest Api python 

### Reproduction steps

Follow this official document to add an rest api in python and deploy by amplify CI/CD 

https://docs.amplify.aws/cli/function/ 

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci --force
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
```

**Comment by ashvinnihalani** [comment]
Isn't this a major issue? This pretty much blocks us from deploying any updates to our website 

Using a custom build image with Python 3.8 doesn't solve the issue. 

`2022-10-24T00:56:38.000Z [INFO]: [31mYou must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".[39m
                                 [31mYou must have virtualenv installed and available on your PATH as "venv". It can be installed by running "pip3 install venv".[39m
2022-10-24T00:56:38.003Z [INFO]: 🛑 Missing required dependencies to package webappAPIcarManufacturers
                                 Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2022-10-24T00:56:38.004Z [WARNING]: ✖ There was an error initializing your environment.
2022-10-24T00:56:38.006Z [INFO]: [31mYou must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".[39m
                                 [31mYou must have virtualenv installed and available on your PATH as "venv". It can be installed by running "pip3 install venv".[39m
2022-10-24T00:56:38.007Z [INFO]: [31mYou must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".[39m
                                 [31mYou must have virtualenv installed and available on your PATH as "venv". It can be installed by running "pip3 install venv".[39m
2022-10-24T00:56:38.007Z [INFO]: [31mYou must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".[39m
                                 [31mYou must have virtualenv installed and available on your PATH as "venv". It can be installed by running "pip3 install venv".[39m
2022-10-24T00:56:38.008Z [INFO]: [31mYou must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".[39m
                                 [31mYou must have virtualenv installed and available on your PATH as "venv". It can be installed by running "pip3 install venv".[39m`

**Comment by ashvinnihalani** [comment]
Further details. This only started appearing when we began using the AWS Amplify API library

**Comment by ashvinnihalani** [comment]
Additional Details/Clarifications. It seems like the React Library is not the problem. Rather any Lambda Function that uses Python encounters this error. This basically breaks the entire API functionality of Amplify if you want to use Python. 

I guess the solution is to build the API Gateway/Lambda suite outside of Amplify.

**Comment by scottbw** [comment]
We can't use Amplify if Lambda backends can't go above Python 3.7.10. Can we get a response please on this please?

**Comment by lcastillo84** [comment]
any update on this? having the same issue

**Comment by berengamble** [comment]
Same issue here.. Please can someone let us know how to build Python >3.10 backends?

**Comment by apocheau** [comment]
In the cloudformation-template.json file of your lambda, you can set the runtime to 3.8:
`"Runtime": "python3.8",`

**Comment by jayarerita** [comment]
@apocheau Changing the runtime from 3.8 to 3.7, the version supplied by the build image does not seem to work. 

 ```
 "Resources": {
    "LambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Metadata": {
        "aws:asset:path": "./src",
        "aws:asset:property": "Code"
      },
      "Properties": {
        ...
        "Runtime": "python3.7",
      },
    },
  },
}
```

It produces the same error on build.

```
2023-05-05T19:17:17.861Z [INFO]: [31mpython3 found but version Python 3.7.15 is less than the minimum required version.[39m
                                 [31mYou must have python >= 3.8 installed and available on your PATH as "python3" or "python". It can be installed from https://www.python.org/downloads[39m
                                 [31mYou must have pipenv installed and available on your PATH as "pipenv". It can be installed by running "pip3 install --user pipenv".[39m
                                 [31mYou must have virtualenv installed and available on your PATH as "venv". It can be installed by running "pip3 install venv".[39m
2023-05-05T19:17:17.861Z [WARNING]: ✖ There was an error initializing your environment.
2023-05-05T19:17:17.861Z [INFO]: 🛑 Missing required dependencies to package xxx
2023-05-05T19:17:17.862Z [INFO]: Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/
2023-05-05T19:17:17.868Z [INFO]: 
2023-05-05T19:17:17.868Z [INFO]: Session Identifier: xxx
2023-05-05T19:17:17.890Z [ERROR]: !!! Build failed
2023-05-05T19:17:17.891Z [ERROR]: !!! Non-Zero Exit Code detected
```

I am able to use the amplify cli to `amplify push` the lambda function successfully.

**Comment by breencp** [comment]
I was able to resolve this problem by adding the "update-alternatives" command to my amplify.yml file: 
```
backend:
  phases:
    build:
      commands:
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.9 15
        - /usr/local/bin/python3.9 -m pip install --upgrade pip
        - /usr/local/bin/pip3.9 install --user pipenv
        - amplifyPush --simple
```

And changing the python_version in my Pipfile:
`[requires]
python_version = "3.9"
`

**Comment by tmb5cg** [comment]
wow i'm so glad i found this. was going insane. thank you all. and i consider myself to sorta understand how everything works (relatively), this is such a niche specific thing, and suddenly i had an "aha" moment and said... maybe i'm actually not doing something wrong and this is something else! 

anyways glad i stayed level headed otherwise i don't think I would've gotten to the bottom of this
