### ISSUE TITLE
Amplify build Fail with Next since today

### ISSUE THREAD

**Issue by multivoltage** [aws-amplify/amplify-hosting#2997]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2skhgz4a0rx0t

### Region

eu-west-1

### Amplify Hosting feature

Build settings

### Describe the bug

I use amplify with next 11 and node 12 since 6 months.
Last good deploy was 3 days ago.
Today all commit produce:

```
2022-09-20T14:50:54.730Z [ERROR]: NoSuchBucket: The specified bucket does not exist
                                  at Request.extractError (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/services/s3.js:711:35)
                                  at Request.callListeners (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                  at Request.emit (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/request.js:686:14)
                                  at Request.transition (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/request.js:688:12)
                                  at Request.callListeners (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                  at Request.emit (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/request.js:686:14)
                                  at Request.transition (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/request.js:688:12)
                                  at Request.callListeners (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                  at callNextListener (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
                                  at IncomingMessage.onEnd (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/event_listeners.js:335:13)
                                  at IncomingMessage.emit (events.js:412:35)
                                  at IncomingMessage.emit (domain.js:475:12)
                                  at endReadableNT (internal/streams/readable.js:1333:12)
                                  at processTicksAndRejections (internal/process/task_queues.js:82:21) {
                                  code: 'NoSuchBucket',
                                  region: null,
                                  time: 2022-09-20T14:50:54.601Z,
                                  requestId: '6TCJVFS3E1JXWWFK',
                                  extendedRequestId: 'J/gnSejXYAVn4g7RkgMErH3zypYjpNXOHImmmI6Xx5SzSpYeEyKvDs7qV+4Rk0KUg+kbjkhDOjs=',
                                  cfId: undefined,
                                  statusCode: 404,
                                  retryable: false,
                                  retryDelay: 5.652999337724407
                                  }
```

### Expected behavior

Build without errors

### Reproduction steps

Deploy a React app with the following dependency:

`"next": "11.1.4"`

### Build Settings

```yaml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by edenriquez** [comment]
I'm seeing the same behavior in my account using amplify, we have 200+ applications and the impact of this is huge, the 3 errors I've identified in my apps are:

1-  NoSuchBucket: The specified bucket does not exist
2- Cannot find any generated SSR resources to deploy
3 - New Cloudfront distributions created without reason

**Comment by multivoltage** [comment]
Since how many days did you see this error?
1 - Maybe. But in the amplify dashboard where can I see this bucket? 
2  and 3. Probably I have to spend days to learn how I can move inside aws panels.

**Comment by edenriquez** [comment]
1- you don't, the way I've figured out the bucket name is by taking the cloudfront id from amplify cli console, find it in cloudfront panel and look at the origin tab there is the s3 bucket name, I don't think the issue is the bucket but the creation of new distributions and the internal metadata that amplify app has to identify the bucket supposed to be linked with the app.

**Comment by multivoltage** [comment]
I think is related with [this](https://github.com/aws-amplify/amplify-hosting/issues/2987)
In fact some deploy (I change only a basic js file) produce a "green" deploy but the site did not reflect the change :)

**Comment by raframil** [comment]
> I think is related with [this](https://github.com/aws-amplify/amplify-hosting/issues/2987) In fact some deploy (I change only a basic js file) produce a "green" deploy but the site did not reflect the change :)

Same problem here, started today

**Comment by arundna** [comment]
@raframil @multivoltage @edenriquez - We're actively investigating this under priority and have been able to reproduce this on our end as well. We'll keep you posted with an update shortly.

**Comment by ferdingler** [comment]
https://github.com/aws-amplify/amplify-hosting/issues/2996

**Comment by gggiii** [comment]
https://github.com/aws-amplify/amplify-hosting/issues/2996#issuecomment-1252904135

**Comment by multivoltage** [comment]
@arundna You can close. After second deploy on staging I think problem is fixes
