### ISSUE TITLE
Backend Deployments consistently failing and timing out with "Stack already exists" error

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-hosting#3017]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2d6ty1wlg8jch

### Region

us-east-1

### Describe the bug

amplify push on my machine to the same env works fine. Pushing via amplify console however fails. This all started today. We do deployments almost every day. 

```
2022-10-03T23:33:59.544Z [INFO]: # Start initializing Amplify environment: prod
                                 # Initializing new Amplify environment: prod (amplify init)
2022-10-03T23:34:00.763Z [INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39m
2022-10-03T23:34:01.490Z [INFO]: [0mAmplify AppID found: d2d6ty1wlg8jch. Amplify App name is: ess-app[0m
2022-10-03T23:34:01.610Z [INFO]: [31m[39m
                                 [31mAn error occurred when creating the CloudFormation stack[39m
2022-10-03T23:34:01.614Z [INFO]: 🛑 Stack [amplify-ess-app-prod-150238] already exists
2022-10-03T23:34:01.615Z [INFO]: Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
2022-10-04T00:01:07.911Z [INFO]: ExpiredToken: The security token included in the request is expired
                                 at Request.extractError (/snapshot/repo/build/node_modules/aws-sdk/lib/protocol/query.js:50:29)
                                 at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
                                 at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:688:12)
                                 at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:686:14)
                                 at Request.transition (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /snapshot/repo/build/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/snapshot/repo/build/node_modules/aws-sdk/lib/request.js:688:12)
                                 at Request.callListeners (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at callNextListener (/snapshot/repo/build/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
                                 at IncomingMessage.onEnd (/snapshot/repo/build/node_modules/aws-sdk/lib/event_listeners.js:335:13)
                                 at IncomingMessage.emit (events.js:412:35)
                                 at IncomingMessage.emit (domain.js:475:12)
                                 at endReadableNT (internal/streams/readable.js:1334:12)
                                 at processTicksAndRejections (internal/process/task_queues.js:82:21) {
                                 code: 'ExpiredToken',
                                 time: 2022-10-04T00:01:07.908Z,
                                 requestId: '31503f63-7e0a-426e-8866-e895ba534aaa',
                                 statusCode: 403,
                                 retryable: true
                                 }
```

### Expected behavior

backend deployment just works

### Reproduction steps

Unknown, but deployment consistently failing for me for this env and I'm not sure how to fix.

**Comment by hisham** [comment]
Looks like this is amplify-cli bug (https://github.com/aws-amplify/amplify-cli/issues/11120). Closing this issue.
