### ISSUE TITLE
Sharp used in API to resize images is triggering Frontend build issues with Webpack

### ISSUE THREAD

**Issue by antoniogiordano** [aws-amplify/amplify-hosting#3140]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d33swajq50o1jx

### AWS Region

eu-west-1

### Amplify Hosting feature

Frontend builds

### Describe the bug

I added sharp to my package json file and I'm using it in endpoints to create thumbnails, but the Frontend build fails.
(Frontend code is not importing the sharp library, so I don't understand why this happens, it's not even used in SSR pages but only in API calls.

### Expected behavior

The build shouldn't fail, since sharp is installed.

### Reproduction steps

1. Create a new NextJS project
2. Install sharp with `npm i sharp -S -E`
3. Create an API that uses sharp
4. Try to deploy the project and it should fail in build phase

### Build Settings

NextJS 12
NodeJS 14.18.1

### Log output

<details>

```
# Put your logs below this line
                                                                 # Starting phase: preBuild
                                 # Executing command: npm ci
2022-11-24T12:51:06.552Z [WARNING]: npm
2022-11-24T12:51:06.552Z [WARNING]: WARN prepare removing existing node_modules/ before installation
2022-11-24T12:51:36.456Z [INFO]: > sharp@0.31.2 install /codebuild/output/src829370821/src/novacoop-nextjs/node_modules/sharp
                                 > (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
2022-11-24T12:51:37.023Z [INFO]: sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.13.3/libvips-8.13.3-linux-x64.tar.br
2022-11-24T12:51:37.794Z [INFO]: sharp: Integrity check passed for linux-x64
2022-11-24T12:51:38.304Z [INFO]: > @fortawesome/fontawesome-common-types@6.2.0 postinstall /codebuild/output/src829370821/src/novacoop-nextjs/node_modules/@fortawesome/fontawesome-common-types
                                 > node attribution.js
2022-11-24T12:51:38.344Z [INFO]: Font Awesome Free 6.2.0 by @fontawesome - https://fontawesome.com
                                 License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
                                 Copyright 2022 Fonticons, Inc.
2022-11-24T12:51:38.349Z [INFO]: > @fortawesome/free-solid-svg-icons@6.2.0 postinstall /codebuild/output/src829370821/src/novacoop-nextjs/node_modules/@fortawesome/free-solid-svg-icons
                                 > node attribution.js
2022-11-24T12:51:38.389Z [INFO]: Font Awesome Free 6.2.0 by @fontawesome - https://fontawesome.com
                                 License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
                                 Copyright 2022 Fonticons, Inc.
2022-11-24T12:51:38.394Z [INFO]: > @fortawesome/fontawesome-svg-core@6.2.0 postinstall /codebuild/output/src829370821/src/novacoop-nextjs/node_modules/@fortawesome/fontawesome-svg-core
                                 > node attribution.js
2022-11-24T12:51:38.435Z [INFO]: Font Awesome Free 6.2.0 by @fontawesome - https://fontawesome.com
                                 License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
                                 Copyright 2022 Fonticons, Inc.
2022-11-24T12:51:38.685Z [INFO]: > husky@4.2.5 install /codebuild/output/src829370821/src/novacoop-nextjs/node_modules/husky
                                 > node husky install
2022-11-24T12:51:38.748Z [INFO]: husky > Setting up git hooks
2022-11-24T12:51:38.774Z [INFO]: CI detected, skipping Git hooks installation.
                                 husky > Done
2022-11-24T12:51:38.779Z [INFO]: > husky@4.2.5 postinstall /codebuild/output/src829370821/src/novacoop-nextjs/node_modules/husky
                                 > opencollective-postinstall || exit 0
2022-11-24T12:51:38.824Z [INFO]: [96m[1mThank you for using husky![96m[1m
2022-11-24T12:51:38.824Z [INFO]: [0m[96mIf you rely on this package, please consider supporting our open collective:[22m[39m
                                 > [94mhttps://opencollective.com/husky/donate[0m
2022-11-24T12:51:38.852Z [INFO]: > core-js-pure@3.23.3 postinstall /codebuild/output/src829370821/src/novacoop-nextjs/node_modules/core-js-pure
                                 > node -e "try{require('./postinstall')}catch(e){}"
2022-11-24T12:51:38.902Z [INFO]: [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
                                 [96mThe project needs your help! Please consider supporting of core-js:[0m
                                 [96m>[94m https://opencollective.com/core-js [0m
                                 [96m>[94m https://patreon.com/zloirock [0m
                                 [96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
                                 [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2022-11-24T12:51:38.958Z [INFO]: > novacoop-nextjs@undefined postinstall /codebuild/output/src829370821/src/novacoop-nextjs
                                 > npx patch-package
2022-11-24T12:51:42.068Z [WARNING]: npx: installed 50 in 3.055s
2022-11-24T12:51:42.148Z [INFO]: patch-package 6.5.0
2022-11-24T12:51:42.148Z [INFO]: Applying patches...
2022-11-24T12:51:42.152Z [INFO]: iron-session@6.2.1 ✔
2022-11-24T12:51:42.203Z [INFO]: added 1038 packages in 35.665s
2022-11-24T12:51:42.219Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2022-11-24T12:51:42.219Z [INFO]: # Executing command: npm run build
2022-11-24T12:51:42.377Z [INFO]: > novacoop-nextjs@ build /codebuild/output/src829370821/src/novacoop-nextjs
                                 > next build
2022-11-24T12:51:42.602Z [INFO]: info  - Loaded env from /codebuild/output/src829370821/src/novacoop-nextjs/.env
2022-11-24T12:51:42.747Z [INFO]: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
2022-11-24T12:51:42.769Z [INFO]: Attention: Next.js now collects completely anonymous telemetry regarding usage.
2022-11-24T12:51:42.769Z [INFO]: This information is used to shape Next.js' roadmap and prioritize features.
                                 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
                                 https://nextjs.org/telemetry
2022-11-24T12:51:42.868Z [INFO]: info  - Linting and checking validity of types...
2022-11-24T12:52:07.363Z [INFO]: info  - Creating an optimized production build...
2022-11-24T12:52:07.456Z [INFO]: info  - Downloading WASM swc package...
2022-11-24T12:52:09.070Z [INFO]: info  - Using experimental wasm build of next-swc
2022-11-24T12:52:09.140Z [WARNING]: warn  - Attempted to load @next/swc-linux-x64-gnu, but an error occurred: libssl.so.1.1: cannot open shared object file: No such file or directory
2022-11-24T12:52:09.141Z [WARNING]: warn  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
                                    warn  - Attempted to load @next/swc-linux-x64-musl, but an error occurred: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
2022-11-24T12:53:16.803Z [INFO]: info  - Compiled successfully
2022-11-24T12:53:16.805Z [INFO]: info  - Collecting page data...
2022-11-24T12:53:24.763Z [INFO]: info  - Generating static pages (0/3)
2022-11-24T12:53:24.804Z [INFO]: info  - Generating static pages (3/3)
2022-11-24T12:53:25.316Z [INFO]: info  - Finalizing page optimization...
2022-11-24T12:53:25.318Z [INFO]: 
2022-11-24T12:53:25.325Z [INFO]: Page                                                      Size     First Load JS
                                 ┌   /_app                                                 0 B            83.1 kB
                                 ├ λ /[[...slugs]]                                         2.76 kB         310 kB
                                 ├ ○ /404                                                  195 B          83.3 kB
                                 ├ ○ /admin                                                2.23 kB        85.3 kB
                                 ├ λ /api/[[...path]]                                      0 B            83.1 kB
                                 ├ λ /api/articles                                         0 B            83.1 kB
                                 ├ λ /api/articles/[articleId]                             0 B            83.1 kB
                                 ├ λ /api/medias                                           0 B            83.1 kB
                                 ├ λ /api/pages                                            0 B            83.1 kB
                                 ├ λ /api/pages/[pageId]                                   0 B            83.1 kB
                                 ├ λ /api/pressReleaseCategories                           0 B            83.1 kB
                                 ├ λ /api/pressReleaseCategories/[pressReleaseCategoryId]  0 B            83.1 kB
                                 ├ λ /api/pressReleases                                    0 B            83.1 kB
                                 ├ λ /api/pressReleases/[pressReleaseId]                   0 B            83.1 kB
                                 ├ λ /api/s3SignedUrls                                     0 B            83.1 kB
                                 ├ λ /api/sessions                                         0 B            83.1 kB
                                 ├ λ /api/sessions/me                                      0 B            83.1 kB
                                 ├ λ /api/static-contents                                  0 B            83.1 kB
                                 ├ λ /api/stores                                           0 B            83.1 kB
                                 ├ λ /api/stores/[storeId]                                 0 B            83.1 kB
                                 ├ λ /api/users                                            0 B            83.1 kB
                                 ├ λ /api/userSessions                                     0 B            83.1 kB
                                 ├ λ /api/userSessions/me                                  0 B            83.1 kB
                                 ├ λ /api/visualComposerComponents                         0 B            83.1 kB
                                 ├ λ /area-stampa                                          2.73 kB         310 kB
                                 ├ λ /area-stampa/[pressReleaseCategorySlug]               2.75 kB         310 kB
                                 ├ λ /news                                                 5.99 kB         199 kB
                                 ├ λ /news/[articleSlug]                                   4.29 kB         312 kB
                                 └ λ /punti-vendita/[slug]                                 14.4 kB         195 kB
                                 + First Load JS shared by all                             83.1 kB
                                 ├ chunks/framework-0ba0ddd33199226d.js                  45.3 kB
                                 ├ chunks/main-71b86861fa5b68ec.js                       34.7 kB
                                 ├ chunks/pages/_app-daa016d5f7759285.js                 554 B
                                 ├ chunks/webpack-a8df2157ec642eb9.js                    2.55 kB
                                 └ css/c6b57b1e62736f1c.css                              686 B
2022-11-24T12:53:25.326Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
2022-11-24T12:53:25.546Z [INFO]: Starting SSR Build...
2022-11-24T12:56:06.121Z [ERROR]: Error: Command failed with exit code 1: node_modules/.bin/next build
                                  warn  - The `target` config is deprecated and will be removed in a future version.
                                  See more info here https://nextjs.org/docs/messages/deprecated-target-config
                                  warn  - Attempted to load @next/swc-linux-x64-gnu, but an error occurred: libssl.so.1.1: cannot open shared object file: No such file or directory
                                  warn  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
                                  warn  - Attempted to load @next/swc-linux-x64-musl, but an error occurred: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
                                  Failed to compile.
                                  ./node_modules/sharp/build/Release/sharp-linux-x64.node
                                  Module parse failed: Unexpected character '' (1:0)
                                  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
                                  (Source code omitted for this binary file)
                                  Import trace for requested module:
                                  ./node_modules/sharp/build/Release/ sync ^\.\/sharp\-.*\.node$
                                  ./node_modules/sharp/lib/sharp.js
                                  ./node_modules/sharp/lib/constructor.js
                                  ./node_modules/sharp/lib/index.js
                                  ./endpoints/post-medias/handler.ts
                                  ./endpoints/post-medias/index.ts
                                  ./endpoints/ lazy ^\.\/.*\-.*\/index\.ts$ namespace object
                                  ./pages/api/[[...path]].ts
                                  ./node_modules/next/dist/build/webpack/loaders/next--loader/index.js?absolute404Path=&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolutePagePath=private-next-pages%2Fapi%2F%5B%5B...path%5D%5D.ts&assetPrefix=&basePath=&buildId=Mh3Tt_EkPpRBriQy2QEfD&canonicalBase=&distDir=private-dot-next&generateEtags=true&i18n=&loadedEnvFiles=W3sicGF0aCI6Ii5lbnYiLCJjb250ZW50cyI6IlJFR0lPTl9BV1NfQkFDS0VORD1ldS13ZXN0LTFcbkFDQ0VTU19LRVlfSURfQVdTX0JBQ0tFTkQ9QUtJQTJPU0hQM05ZWko1NlFPRVZcblNFQ1JFVF9BQ0NFU1NfS0VZX0FXU19CQUNLRU5EPTFRRUw0SHYyTk04RWFhOHBGMmx5L3dGbXBiQWpGcjBzQ2RGNkNmdmxcblxuTkVYVF9QVUJMSUNfQVdTX1JFR0lPTj1ldS13ZXN0LTFcbk5FWFRfUFVCTElDX0FQSV9CQVNFX1VSTD0vYXBpXG5ORVhUX1BVQkxJQ19HT09HTEVfTUFQU19BUElfS0VZPUFJemFTeUJiZ1N6VGhyVXlHNTJtby1tZHp6NVg3VEVxOTltZ3B4c1xuIn1d&page=%2Fapi%2F%5B%5B...path%5D%5D&poweredByHeader=true&previewProps=%7B%22previewModeId%22%3A%22b4d41432f8540153cb39c2d993fb6870%22%2C%22previewModeSigningKey%22%3A%22f2ec7804e296c57b33d210578d78c6aa9eec7fc87cf126c236d0122ab9d17fd0%22%2C%22previewModeEncryptionKey%22%3A%226f9ffb6669aaa4a100de9ded0afebb63798d6c0815e7581aee996253267ca447%22%7D&runtimeConfig=!
                                  > webpack config.resolve.alias was incorrectly overridden. https://nextjs.org/docs/messages/invalid-resolve-alias
                                  info  - Loaded env from /codebuild/output/src829370821/src/novacoop-nextjs/.env
                                  info  - Linting and checking validity of types...
                                  info  - Creating an optimized production build...
                                  info  - Using experimental wasm build of next-swc
                                  at makeError (/root/.//node_modules/execa/lib/error.js:60:11)
                                  at handlePromise (/root/.//node_modules/execa/index.js:118:26)
                                  at runMicrotasks (<anonymous>)
                                  at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                  at async Builder.build (/root/.//node_modules/@sls-next/lambda-at-edge/dist/build.js:377:13)
                                  at async NextjsComponent.build (/root/.//node_modules/@sls-next/-component/dist/component.js:165:13)
                                  at async NextjsComponent.default (/root/.//node_modules/@sls-next/-component/dist/component.js:22:13)
                                  at async fn (/root/.npm/_npx/3820/lib/node_modules//node_modules/@/template/utils.js:280:41)
                                  at async Promise.all (index 0)
                                  at async executeGraph (/root/.npm/_npx/3820/lib/node_modules//node_modules/@/template/utils.js:294:3)
                                  at async Template.default (/root/.npm/_npx/3820/lib/node_modules//node_modules/@/template/.js:67:38)
                                  at async Object.runComponents (/root/.npm/_npx/3820/lib/node_modules//node_modules/@/cli/src/index.js:222:17) {
                                  shortMessage: 'Command failed with exit code 1: node_modules/.bin/next build',
                                  command: 'node_modules/.bin/next build',
                                  escapedCommand: '"node_modules/.bin/next" build',
                                  exitCode: 1,
                                  signal: undefined,
                                  signalDescription: undefined,
                                  stdout: 'info  - Loaded env from /codebuild/output/src829370821/src/novacoop-nextjs/.env\n' +
                                  'info  - Linting and checking validity of types...\n' +
                                  'info  - Creating an optimized production build...\n' +
                                  'info  - Using experimental wasm build of next-swc',
                                  stderr: 'warn  - The `target` config is deprecated and will be removed in a future version.\n' +
                                  'See more info here https://nextjs.org/docs/messages/deprecated-target-config\n' +
                                  'warn  - Attempted to load @next/swc-linux-x64-gnu, but an error occurred: libssl.so.1.1: cannot open shared object file: No such file or directory\n' +
                                  'warn  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed\n' +
                                  'warn  - Attempted to load @next/swc-linux-x64-musl, but an error occurred: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory\n' +
                                  'Failed to compile.\n' +
                                  '\n' +
                                  './node_modules/sharp/build/Release/sharp-linux-x64.node\n' +
                                  "Module parse failed: Unexpected character '\x7F' (1:0)\n" +
                                  'You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n' +
                                  '(Source code omitted for this binary file)\n' +
                                  '\n' +
                                  'Import trace for requested module:\n' +
                                  './node_modules/sharp/build/Release/ sync ^\\.\\/sharp\\-.*\\.node$\n' +
                                  './node_modules/sharp/lib/sharp.js\n' +
                                  './node_modules/sharp/lib/constructor.js\n' +
                                  './node_modules/sharp/lib/index.js\n' +
                                  './endpoints/post-medias/handler.ts\n' +
                                  './endpoints/post-medias/index.ts\n' +
                                  './endpoints/ lazy ^\\.\\/.*\\-.*\\/index\\.ts$ namespace object\n' +
                                  './pages/api/[[...path]].ts\n' +
                                  './node_modules/next/dist/build/webpack/loaders/next--loader/index.js?absolute404Path=&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolutePagePath=private-next-pages%2Fapi%2F%5B%5B...path%5D%5D.ts&assetPrefix=&basePath=&buildId=Mh3Tt_EkPpRBriQy2QEfD&canonicalBase=&distDir=private-dot-next&generateEtags=true&i18n=&loadedEnvFiles=W3sicGF0aCI6Ii5lbnYiLCJjb250ZW50cyI6IlJFR0lPTl9BV1NfQkFDS0VORD1ldS13ZXN0LTFcbkFDQ0VTU19LRVlfSURfQVdTX0JBQ0tFTkQ9QUtJQTJPU0hQM05ZWko1NlFPRVZcblNFQ1JFVF9BQ0NFU1NfS0VZX0FXU19CQUNLRU5EPTFRRUw0SHYyTk04RWFhOHBGMmx5L3dGbXBiQWpGcjBzQ2RGNkNmdmxcblxuTkVYVF9QVUJMSUNfQVdTX1JFR0lPTj1ldS13ZXN0LTFcbk5FWFRfUFVCTElDX0FQSV9CQVNFX1VSTD0vYXBpXG5ORVhUX1BVQkxJQ19HT09HTEVfTUFQU19BUElfS0VZPUFJemFTeUJiZ1N6VGhyVXlHNTJtby1tZHp6NVg3VEVxOTltZ3B4c1xuIn1d&page=%2Fapi%2F%5B%5B...path%5D%5D&poweredByHeader=true&previewProps=%7B%22previewModeId%22%3A%22b4d41432f8540153cb39c2d993fb6870%22%2C%22previewModeSigningKey%22%3A%22f2ec7804e296c57b33d210578d78c6aa9eec7fc87cf126c236d0122ab9d17fd0%22%2C%22previewModeEncryptionKey%22%3A%226f9ffb6669aaa4a100de9ded0afebb63798d6c0815e7581aee996253267ca447%22%7D&runtimeConfig=!\n' +
                                  '\n' +
                                  '\n' +
                                  '> webpack config.resolve.alias was incorrectly overridden. https://nextjs.org/docs/messages/invalid-resolve-alias',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
                                  killed: false
                                  }
2022-11-24T12:56:06.124Z [ERROR]: [G[?25h[G[J
                                  125s › d33swajq50o1jx › Error: Command failed with exit code 1: node_modules/.bin/next build
                                  warn  - The `target` config is deprecated and will be removed in a future version.
                                  See more info here https://nextjs.org/docs/messages/deprecated-target-config
                                  warn  - Attempted to load @next/swc-linux-x64-gnu, but an error occurred: libssl.so.1.1: cannot open shared object file: No such file or directory
                                  warn  - Attempted to load @next/swc-linux-x64-gnux32, but it was not installed
                                  warn  - Attempted to load @next/swc-linux-x64-musl, but an error occurred: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
                                  Failed to compile.
                                  ./node_modules/sharp/build/Release/sharp-linux-x64.node
                                  Module parse failed: Unexpected character '' (1:0)
                                  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
                                  (Source code omitted for this binary file)
                                  Import trace for requested module:
                                  ./node_modules/sharp/build/Release/ sync ^\.\/sharp\-.*\.node$
                                  ./node_modules/sharp/lib/sharp.js
                                  ./node_modules/sharp/lib/constructor.js
                                  ./node_modules/sharp/lib/index.js
                                  ./endpoints/post-medias/handler.ts
                                  ./endpoints/post-medias/index.ts
                                  ./endpoints/ lazy ^\.\/.*\-.*\/index\.ts$ namespace object
                                  ./pages/api/[[...path]].ts
                                  ./node_modules/next/dist/build/webpack/loaders/next--loader/index.js?absolute404Path=&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolutePagePath=private-next-pages%2Fapi%2F%5B%5B...path%5D%5D.ts&assetPrefix=&basePath=&buildId=Mh3Tt_EkPpRBriQy2QEfD&canonicalBase=&distDir=private-dot-next&generateEtags=true&i18n=&loadedEnvFiles=W3sicGF0aCI6Ii5lbnYiLCJjb250ZW50cyI6IlJFR0lPTl9BV1NfQkFDS0VORD1ldS13ZXN0LTFcbkFDQ0VTU19LRVlfSURfQVdTX0JBQ0tFTkQ9QUtJQTJPU0hQM05ZWko1NlFPRVZcblNFQ1JFVF9BQ0NFU1NfS0VZX0FXU19CQUNLRU5EPTFRRUw0SHYyTk04RWFhOHBGMmx5L3dGbXBiQWpGcjBzQ2RGNkNmdmxcblxuTkVYVF9QVUJMSUNfQVdTX1JFR0lPTj1ldS13ZXN0LTFcbk5FWFRfUFVCTElDX0FQSV9CQVNFX1VSTD0vYXBpXG5ORVhUX1BVQkxJQ19HT09HTEVfTUFQU19BUElfS0VZPUFJemFTeUJiZ1N6VGhyVXlHNTJtby1tZHp6NVg3VEVxOTltZ3B4c1xuIn1d&page=%2Fapi%2F%5B%5B...path%5D%5D&poweredByHeader=true&previewProps=%7B%22previewModeId%22%3A%22b4d41432f8540153cb39c2d993fb6870%22%2C%22previewModeSigningKey%22%3A%22f2ec7804e296c57b33d210578d78c6aa9eec7fc87cf126c236d0122ab9d17fd0%22%2C%22previewModeEncryptionKey%22%3A%226f9ffb6669aaa4a100de9ded0afebb63798d6c0815e7581aee996253267ca447%22%7D&runtimeConfig=!
                                  > webpack config.resolve.alias was incorrectly overridden. https://nextjs.org/docs/messages/invalid-resolve-alias
                                  info  - Loaded env from /codebuild/output/src829370821/src/novacoop-nextjs/.env
                                  info  - Linting and checking validity of types...
                                  info  - Creating an optimized production build...
                                  info  - Using experimental wasm build of next-swc
                                  [G[?25h
Terminating logging...

```

</details>

**Comment by antoniogiordano** [comment]
Solved with:
`
  webpack: (config) => {
    config.module.rules.push({
      test: /\.node$/,
      use: "node-loader",
    });

    return config;
  },
`
in the next.config.js.
