### ISSUE TITLE
Next12->13 SSR builds started to fail: "target" property is no longer supported in next.config.js.

### ISSUE THREAD

**Issue by x000r** [aws-amplify/amplify-hosting#3187]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2f94bw3hjxy2q

### AWS Region

ap-northeast-1

### Amplify Hosting feature

Frontend builds

### Describe the bug

SSR builds started to fail after we've migrated from Nextjs 12 to 13. Used the official migration manual from here [https://nextjs.org/docs/upgrading#migrating-shared-features](url)

`yarn add next@latest react@latest react-dom@latest eslint-config-next@latest`

Everything builds locally (node 16.16.0) without any issues, at the same time, when trying to build on Amplify we get the following error:
```
2022-12-08T11:46:20.484Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
2022-12-08T11:46:20.736Z [INFO]: Done in 96.07s.
2022-12-08T11:46:20.740Z [INFO]: Starting SSR Build...
2022-12-08T11:47:49.302Z [ERROR]: Error: Command failed with exit code 1: node_modules/.bin/next build
                                  warn  - Invalid next.config.js options detected:
                                  - The root value has an unexpected property, target, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
                                  See more info here: https://nextjs.org/docs/messages/invalid-next-config
                                  > Build error occurred
                                  Error: The "target" property is no longer supported in next.config.js.
```
#### `next.config.js`:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  basePath: '',
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: ['placekitten.com', 'dummyimage.com', 'docs.amplify.aws']
  },
}

module.exports = nextConfig
```
there's no such key `target`.

### Expected behavior

Build completes successfully just like it did back when we were using Next12.

### Reproduction steps

1. Upgrade from Next12 to 13 by running `yarn add next@latest react@latest react-dom@latest eslint-config-next@latest`
2. Try to build on Amplify

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    #paths:
     # - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line
2022-12-08T11:46:20.484Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
2022-12-08T11:46:20.736Z [INFO]: Done in 96.07s.
2022-12-08T11:46:20.740Z [INFO]: Starting SSR Build...
2022-12-08T11:47:49.302Z [ERROR]: Error: Command failed with exit code 1: node_modules/.bin/next build
                                  warn  - Invalid next.config.js options detected:
                                  - The root value has an unexpected property, target, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
                                  See more info here: https://nextjs.org/docs/messages/invalid-next-config
                                  > Build error occurred
                                  Error: The "target" property is no longer supported in next.config.js.
                                  See more info here https://nextjs.org/docs/messages/deprecated-target-config
                                  at Object.loadConfig [as default] (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/server/config.js:96:19)
                                  at async Span.traceAsyncFn (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/trace/trace.js:79:20)
                                  at async /codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/build/index.js:69:28
                                  at async Span.traceAsyncFn (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/trace/trace.js:79:20)
                                  at async Object.build [as default] (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/build/index.js:65:29)
                                  at makeError (/root/.//node_modules/execa/lib/error.js:60:11)
                                  at handlePromise (/root/.//node_modules/execa/index.js:118:26)
                                  at processTicksAndRejections (node:internal/process/task_queues:96:5)
                                  at async Builder.build (/root/.//node_modules/@sls-next/lambda-at-edge/dist/build.js:377:13)
                                  at async NextjsComponent.build (/root/.//node_modules/@sls-next/-component/dist/component.js:165:13)
                                  at async NextjsComponent.default (/root/.//node_modules/@sls-next/-component/dist/component.js:22:13)
                                  at async fn (/root/.npm/_npx/780a6c1398234b48/node_modules/@/template/utils.js:280:41)
                                  at async Promise.all (index 0)
                                  at async executeGraph (/root/.npm/_npx/780a6c1398234b48/node_modules/@/template/utils.js:294:3)
                                  at async Template.default (/root/.npm/_npx/780a6c1398234b48/node_modules/@/template/.js:67:38)
                                  at async Object.runComponents (/root/.npm/_npx/780a6c1398234b48/node_modules/@/cli/src/index.js:222:17) {
                                  shortMessage: 'Command failed with exit code 1: node_modules/.bin/next build',
                                  command: 'node_modules/.bin/next build',
                                  escapedCommand: '"node_modules/.bin/next" build',
                                  exitCode: 1,
                                  signal: undefined,
                                  signalDescription: undefined,
                                  stdout: '',
                                  stderr: 'warn  - Invalid next.config.js options detected: \n' +
                                  '  - The root value has an unexpected property, target, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).\n' +
                                  '\n' +
                                  'See more info here: https://nextjs.org/docs/messages/invalid-next-config\n' +
                                  '\n' +
                                  '> Build error occurred\n' +
                                  'Error: The "target" property is no longer supported in next.config.js.\n' +
                                  'See more info here https://nextjs.org/docs/messages/deprecated-target-config\n' +
                                  '    at Object.loadConfig [as default] (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/server/config.js:96:19)\n' +
                                  '    at async Span.traceAsyncFn (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/trace/trace.js:79:20)\n' +
                                  '    at async /codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/build/index.js:69:28\n' +
                                  '    at async Span.traceAsyncFn (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/trace/trace.js:79:20)\n' +
                                  '    at async Object.build [as default] (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/build/index.js:65:29)',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
                                  killed: false
                                  }
2022-12-08T11:47:49.305Z [ERROR]: [G[?25h[G[J
                                  39s › d2f94bw3hjxy2q › Error: Command failed with exit code 1: node_modules/.bin/next build
                                  warn  - Invalid next.config.js options detected:
                                  - The root value has an unexpected property, target, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
                                  See more info here: https://nextjs.org/docs/messages/invalid-next-config
                                  > Build error occurred
                                  Error: The "target" property is no longer supported in next.config.js.
                                  See more info here https://nextjs.org/docs/messages/deprecated-target-config
                                  at Object.loadConfig [as default] (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/server/config.js:96:19)
                                  at async Span.traceAsyncFn (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/trace/trace.js:79:20)
                                  at async /codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/build/index.js:69:28
                                  at async Span.traceAsyncFn (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/trace/trace.js:79:20)
                                  at async Object.build [as default] (/codebuild/output/src514663002/src/[redacted]/node_modules/next/dist/build/index.js:65:29)
                                  [G[?25h
Terminating logging...

```

</details>

#### Things we've tried so far

- delete `node_modules` and run `yarn` once again
- disable build cache (commented out `cache` section in `amplify.yaml`)
- added `--frozen-lockfile`
- checked for any additional warnings in console during build time

#### Build settings
![image](https://user-images.githubusercontent.com/27699335/206453011-a5c42993-5ec2-4e05-a61d-a606b18108f5.png)

**Comment by hloriana** [comment]
Hi @x000r 👋🏽 we recently added support for Next.js 13 which features faster build times and fully managed resources. Currently, your application is attempting to deploy using Amplify's Classic support for Next.js 11 which will fail with your Next.js 13 application. Please use this guide to migrate your application to Amplify Hosting Compute: https://docs.aws.amazon.com/amplify/latest/userguide/update-app-nextjs-version.html.

Also, there is a chance that the rewrite rule targeting the CloudFront distribution created with Classic support will remain after migrating. Please be sure to manually delete that rule so that requests to your application will be served by the new CloudFront distribution which is managed by Amplify Hosting.

**Comment by x000r** [comment]
@hloriana thanks for the quick response, I will try following the migration guidea and see if it works.

**Comment by x000r** [comment]
Migration solved the issue, everything is building fine. Thank you. I will close the issue.
