### ISSUE TITLE
cypress testing is not executed in the deploy

### ISSUE THREAD

**Issue by vpode** [aws-amplify/amplify-hosting#3235]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

/d2wao2oyvt6nan

### AWS Region

us-east-1

### Amplify Hosting feature

E2E Cypress tests, Frontend builds

### Describe the bug

We have an angular front-end hosted in aws amplify. 
Recently we tried to add cypress e2e testing.

(using "ng add @cypress/schematic " in the proyect)

We create 3 tests inside the folder : "/cypress/e2e"

We followed this guide: 

https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html

And deployed the app in amplify (using a git commit).

But, this doesnt work:

![amplify-compilation](https://user-images.githubusercontent.com/1775512/212174650-019418a4-b729-4585-a575-33877f4be97c.png)

The compilation ends, but with no testing "stage". We read under it: "Test is still pending or has been cancelled for this build."

### Expected behavior

We expect to see a execution of the e2e test and a "verify" tab with the results.

### Reproduction steps

1.  adding the suggested cypress configuration in the amplify.yml
2.  deploying the app.

### Build Settings

```yaml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist/cmsmedios-ux
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - npm ci
        - npm install wait-on
        - npm install pm2
        - npm install mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
        - npx pm2 start npm -- start
        - 'npx wait-on --timeout 60 http://localhost:3000'
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - npx pm2 kill
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```

### Log output

<details>

```
# Put your logs below this line

Provision:
-----------------

# Use the standard Amazon Linux base, provided by ECR/KaOS
# It points to the standard shared Amazon Linux image, with a versioned tag.
FROM amazonlinux:2

# https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
LABEL maintainer="Amazon AWS"

# Framework Versions
ENV VERSION_NODE_8=8.12.0
ENV VERSION_NODE_10=10.16.0
ENV VERSION_NODE_12=12
ENV VERSION_NODE_14=14
ENV VERSION_NODE_16=16
ENV VERSION_NODE_17=17
ENV VERSION_NODE_DEFAULT=$VERSION_NODE_14
ENV VERSION_RUBY_2_4=2.4.6
ENV VERSION_RUBY_2_6=2.6.3
ENV VERSION_BUNDLER=2.0.1
ENV VERSION_RUBY_DEFAULT=$VERSION_RUBY_2_4
ENV VERSION_HUGO=0.75.1
ENV VERSION_YARN=1.22.0
ENV VERSION_AMPLIFY=6.3.1

# UTF-8 Environment
ENV LANGUAGE en_US:en
ENV LANG=en_US.UTF-8
ENV LC_ALL en_US.UTF-8

## Install OS packages
RUN touch ~/.bashrc
RUN yum -y update && \
    yum -y install \
        alsa-lib-devel \
        autoconf \
        automake \
        bzip2 \
        bison \
        bzr \
        cmake \
        expect \
        fontconfig \
        git \
        gcc-c++ \
        GConf2-devel \
        gtk2-devel \
        gtk3-devel \
        libnotify-devel \
        libpng \
        libpng-devel \
        libffi-devel \
        libtool \
        libX11 \
        libXext \
        libxml2 \
        libxml2-devel \
        libXScrnSaver \
        libxslt \
        libxslt-devel \
        libyaml \
        libyaml-devel \
        make \
        nss-devel \
        openssl-devel \
        openssh-clients \
        patch \
        procps \
        python3 \
        python3-devel \
        readline-devel \
        sqlite-devel \
        tar \
        tree \
        unzip \
        wget \
        which \
        xorg-x11-server-Xvfb \
        zip \
        zlib \
        zlib-devel \
    yum clean all && \
    rm -rf /var/cache/yum

## Install Hugo
RUN wget https://github.com/gohugoio/hugo/releases/download/v${VERSION_HUGO}/hugo_${VERSION_HUGO}_Linux-64bit.tar.gz && \
    tar -xf hugo_${VERSION_HUGO}_Linux-64bit.tar.gz hugo -C / && \
    mv /hugo /usr/bin/hugo && \
    rm -rf hugo_${VERSION_HUGO}_Linux-64bit.tar.gz

## Install dotnet sdk and host 3.1
RUN rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
RUN yum -y install dotnet-host-3.1.4
RUN yum -y install dotnet-sdk-3.1
 
## Install amazon dotnet tools
RUN dotnet tool install -g Amazon.Lambda.Tools
RUN dotnet tool install -g Amazon.Lambda.TestTool-3.1

## Install python3.8
RUN wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
RUN tar xvf Python-3.8.0.tgz
WORKDIR Python-3.8.0
RUN ./configure --enable-optimizations --prefix=/usr/local
RUN make altinstall

## Install python3.9
RUN wget https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tgz
RUN tar xvf Python-3.9.0.tgz
WORKDIR Python-3.9.0
RUN ./configure --enable-optimizations --prefix=/usr/local
RUN make altinstall

## Install Node
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
RUN /bin/bash -c ". ~/.nvm/nvm.sh &&     nvm install $VERSION_NODE_8 && nvm use $VERSION_NODE_8 && \
	nvm install $VERSION_NODE_10 && nvm use $VERSION_NODE_10 && \
	npm install -g yarn@${VERSION_YARN} sm grunt-cli bower vuepress gatsby-cli && \
	nvm install $VERSION_NODE_12 && nvm use $VERSION_NODE_12 && \
	npm install -g yarn@${VERSION_YARN} sm grunt-cli bower vuepress gatsby-cli && \
	nvm install $VERSION_NODE_14 && nvm use $VERSION_NODE_14 && \
	npm install -g yarn@${VERSION_YARN} sm grunt-cli bower vuepress gatsby-cli && \
	nvm install $VERSION_NODE_16 && nvm use $VERSION_NODE_16 && chown -R root:root /root/.nvm &&  \
	npm install -g yarn@${VERSION_YARN} sm grunt-cli bower vuepress gatsby-cli && \
	nvm install $VERSION_NODE_17 && nvm use $VERSION_NODE_17 && chown -R root:root /root/.nvm && \
    npm install -g yarn@${VERSION_YARN} sm grunt-cli bower vuepress gatsby-cli && \
	nvm alias default ${VERSION_NODE_DEFAULT} && nvm cache clear"

# Handle yarn for any `nvm install` in the future
RUN echo "yarn@${VERSION_YARN}" > /root/.nvm/default-packages

## Install Ruby 2.4.x and 2.6.x
## https://github.com/rvm/rvm/issues/5096 | https://rvm.io/rvm/security#install-our-keys - The old keyserver is no longer available
RUN curl -sSL https://rvm.io/mpapis.asc | gpg --import - && curl -sSL https://rvm.io/pkuczynski.asc | gpg --import - && 	curl -sL https://get.rvm.io | bash -s -- --with-gems="bundler"

ENV PATH /usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN /bin/bash --login -c "\
	rvm install $VERSION_RUBY_2_4 && rvm use $VERSION_RUBY_2_4 && gem install bundler -v $VERSION_BUNDLER && gem install jekyll && \
	rvm install $VERSION_RUBY_2_6 && rvm use $VERSION_RUBY_2_6 && gem install bundler -v $VERSION_BUNDLER && gem install -N jekyll && \
	rvm cleanup all"

## Install awscli
RUN /bin/bash -c "pip3.8 install awscli && rm -rf /var/cache/apk/*"
RUN /bin/bash -c "pip3.9 install awscli && rm -rf /var/cache/apk/*"

## Install SAM CLI
RUN /bin/bash -c "pip3.8 install aws-sam-cli"
RUN /bin/bash -c "pip3.9 install aws-sam-cli"

## Installing Cypress
RUN /bin/bash -c ". ~/.nvm/nvm.sh && \
    nvm use ${VERSION_NODE_DEFAULT} && \
    npm install -g --unsafe-perm=true --allow-root cypress"

## Install AWS Amplify CLI for all node versions
RUN /bin/bash -c ". ~/.nvm/nvm.sh && nvm use ${VERSION_NODE_8} && \
    npm config set user 0 && npm config set unsafe-perm true && \
	npm install -g @aws-amplify/cli@${VERSION_AMPLIFY}"
RUN /bin/bash -c ". ~/.nvm/nvm.sh && nvm use ${VERSION_NODE_10} && \
    npm config set user 0 && npm config set unsafe-perm true && \
	npm install -g @aws-amplify/cli@${VERSION_AMPLIFY}"
RUN /bin/bash -c ". ~/.nvm/nvm.sh && nvm use ${VERSION_NODE_12} && \
    npm config set user 0 && npm config set unsafe-perm true && \
	npm install -g @aws-amplify/cli@${VERSION_AMPLIFY}"
RUN /bin/bash -c ". ~/.nvm/nvm.sh && nvm use ${VERSION_NODE_14} && \
    npm config set user 0 && npm config set unsafe-perm true && \
	npm install -g @aws-amplify/cli@${VERSION_AMPLIFY}"
RUN /bin/bash -c ". ~/.nvm/nvm.sh && nvm use ${VERSION_NODE_16} && \
    npm config set user 0 && npm config set unsafe-perm true && \
	npm install -g @aws-amplify/cli@${VERSION_AMPLIFY}"
RUN /bin/bash -c ". ~/.nvm/nvm.sh && nvm use ${VERSION_NODE_17}  && \
    npm config set user 0 && npm config set unsafe-perm true && \
	npm install -g @aws-amplify/cli@${VERSION_AMPLIFY}"

## Environment Setup
RUN echo export PATH="/usr/local/rvm/gems/ruby-${VERSION_RUBY_DEFAULT}/bin:\
/usr/local/rvm/gems/ruby-${VERSION_RUBY_DEFAULT}@global/bin:\
/usr/local/rvm/rubies/ruby-${VERSION_RUBY_DEFAULT}/bin:\
/usr/local/rvm/bin:\
/root/.nvm/versions/node/${VERSION_NODE_DEFAULT}/bin:\
$(python3 -m site --user-base)/bin:\
$(python3.8 -m site --user-base)/bin:\
$(python3.9 -m site --user-base)/bin:\
$PATH" >> ~/.bashrc && \
    echo export GEM_PATH="/usr/local/rvm/gems/ruby-${VERSION_RUBY_DEFAULT}" >> ~/.bashrc && \
     echo "nvm use ${VERSION_NODE_DEFAULT} 1> /dev/null" >> ~/.bashrc && \
     echo "export PATH=$PATH:/root/.dotnet/tools" >> ~/.bashrc

ENTRYPOINT [ "bash", "-c" ]

================
Clonning repository:
---------------------------

2023-01-12T19:19:22.444Z [INFO]: # Cloning repository: git@github.com:*****.git
2023-01-12T19:19:27.696Z [INFO]: 
2023-01-12T19:19:27.819Z [INFO]: Cloning into 'cmsmedios-ux'...
2023-01-12T19:19:27.820Z [INFO]: # Switching to commit: d3b5c70e514759af94d399c34ab8c352986948cd
2023-01-12T19:19:27.892Z [INFO]: Note: switching to 'd3b5c70e514759af94d399c34ab8c352986948cd'.
                                 You are in 'detached HEAD' state. You can look around, make experimental
                                 changes and commit them, and you can discard any commits you make in this
                                 state without impacting any branches by switching back to a branch.
                                 If you want to create a new branch to retain commits you create, you may
                                 do so (now or later) by using -c with the switch command. Example:
                                 git switch -c <new-branch-name>
                                 Or undo this operation with:
                                 git switch -
                                 Turn off this advice by setting config variable advice.detachedHead to false
                                 HEAD is now at d3b5c70e Merge pull request #2228 from hmarsili/roma-mdf
2023-01-12T19:19:27.934Z [INFO]: Successfully cleaned up Git credentials
2023-01-12T19:19:27.934Z [INFO]: # Checking for Git submodules at: /codebuild/output/src335772648/src/cmsmedios-ux/.gitmodules
2023-01-12T19:19:27.949Z [INFO]: # Retrieving environment cache...
2023-01-12T19:19:28.462Z [INFO]: # Retrieved environment cache
2023-01-12T19:19:28.462Z [INFO]: ---- Setting Up SSM Secrets ----
2023-01-12T19:19:28.462Z [INFO]: SSM params {"Path":"/amplify/d2wao2oyvt6nan/2FA/","WithDecryption":true}
2023-01-12T19:19:28.498Z [WARNING]: !Failed to set up process.env.secrets
2023-01-12T19:19:40.506Z [INFO]: # Node version 14 is available for installation
2023-01-12T19:19:40.605Z [INFO]: # Installing Node version 14
2023-01-12T19:19:48.057Z [INFO]: # Now using Node version 14
2023-01-12T19:19:48.141Z [INFO]: # Retrieving cache...
2023-01-12T19:19:56.604Z [INFO]: # Extracting cache...
2023-01-12T19:20:05.500Z [INFO]: # Extraction completed
2023-01-12T19:20:05.663Z [INFO]: # Retrieved cache

==========================
Front end:
--------------------



2023-01-12T19:20:08.401Z [INFO]: # Starting phase: preBuild
                                 # Executing command: npm install
2023-01-12T19:20:31.576Z [WARNING]: npm notice created a lockfile as package-lock.json. You should commit this file.
2023-01-12T19:20:31.587Z [WARNING]: npm
2023-01-12T19:20:31.587Z [WARNING]: WARN @angular/elements@13.2.3 requires a peer of @angular/core@13.2.3 but none is installed. You must install peer dependencies yourself.
2023-01-12T19:20:31.595Z [WARNING]: npm
2023-01-12T19:20:31.595Z [WARNING]: WARN angular-cropperjs@1.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
2023-01-12T19:20:31.604Z [WARNING]: npm WARN angular-cropperjs@1.0.2 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
2023-01-12T19:20:31.610Z [WARNING]: npm
2023-01-12T19:20:31.610Z [WARNING]: WARN bootstrap@4.1.1 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
2023-01-12T19:20:31.617Z [WARNING]: npm WARN
2023-01-12T19:20:31.617Z [WARNING]: codelyzer@5.2.2 requires a peer of @angular/compiler@>=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0 but none is installed. You must install peer dependencies yourself.
2023-01-12T19:20:31.626Z [WARNING]: npm WARN
2023-01-12T19:20:31.626Z [WARNING]: codelyzer@5.2.2 requires a peer of @angular/core@>=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0 but none is installed. You must install peer dependencies yourself.
2023-01-12T19:20:31.626Z [WARNING]: 
2023-01-12T19:20:31.627Z [INFO]: added 2 packages from 2 contributors, updated 2 packages and audited 1250 packages in 22.905s
2023-01-12T19:20:32.023Z [INFO]: 100 packages are looking for funding
                                 run `npm fund` for details
2023-01-12T19:20:32.023Z [INFO]: found 49 vulnerabilities (3 low, 6 moderate, 35 high, 5 critical)
                                 run `npm audit fix` to fix them, or `npm audit` for details
2023-01-12T19:20:32.063Z [INFO]: # Executing command: npm ci
2023-01-12T19:20:32.406Z [WARNING]: npm
2023-01-12T19:20:32.407Z [WARNING]: WARN
2023-01-12T19:20:32.407Z [WARNING]: prepare removing existing node_modules/ before installation
2023-01-12T19:20:57.631Z [INFO]: > nice-napi@1.0.2 install /codebuild/output/src335772648/src/cmsmedios-ux/node_modules/nice-napi
                                 > node-gyp-build
2023-01-12T19:20:57.781Z [INFO]: > esbuild@0.14.11 postinstall /codebuild/output/src335772648/src/cmsmedios-ux/node_modules/esbuild
                                 > node install.js
2023-01-12T19:20:57.852Z [INFO]: > core-js@3.19.3 postinstall /codebuild/output/src335772648/src/cmsmedios-ux/node_modules/core-js
                                 > node -e "try{require('./postinstall')}catch(e){}"
2023-01-12T19:20:57.901Z [INFO]: [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
                                 [96mThe project needs your help! Please consider supporting of core-js:[0m
                                 [96m>[94m https://opencollective.com/core-js [0m
                                 [96m>[94m https://patreon.com/zloirock [0m
                                 [96m>[94m https://paypal.me/zloirock [0m
                                 [96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
                                 [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2023-01-12T19:20:58.122Z [INFO]: > cypress@12.3.0 postinstall /codebuild/output/src335772648/src/cmsmedios-ux/node_modules/cypress
                                 > node index.js --exec install
2023-01-12T19:20:58.621Z [INFO]: Installing Cypress (version: 12.3.0)
2023-01-12T19:20:58.621Z [INFO]: 
2023-01-12T19:20:58.624Z [INFO]: [STARTED] Task without title.
2023-01-12T19:21:00.958Z [INFO]: [SUCCESS] Task without title.
2023-01-12T19:21:00.960Z [INFO]: [STARTED] Task without title.
2023-01-12T19:21:06.362Z [INFO]: [SUCCESS] Task without title.
2023-01-12T19:21:06.366Z [INFO]: [STARTED] Task without title.
2023-01-12T19:21:06.381Z [INFO]: [SUCCESS] Task without title.
2023-01-12T19:21:07.383Z [INFO]: You can now open Cypress by running: node_modules/.bin/cypress open
2023-01-12T19:21:07.383Z [INFO]: https://on.cypress.io/installing-cypress
2023-01-12T19:21:07.552Z [INFO]: > @angular/cli@13.1.4 postinstall /codebuild/output/src335772648/src/cmsmedios-ux/node_modules/@angular/cli
                                 > node ./bin/postinstall/script.js
2023-01-12T19:21:07.925Z [INFO]: added 1246 packages in 35.534s
2023-01-12T19:21:07.946Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
                                 # Executing command: npm run build
2023-01-12T19:21:08.125Z [INFO]: > cmsmedios-ux@0.0.0 build /codebuild/output/src335772648/src/cmsmedios-ux
                                 > npm run config -- --environment=prod && ng build --aot --configuration production
2023-01-12T19:21:08.302Z [INFO]: > cmsmedios-ux@0.0.0 config /codebuild/output/src335772648/src/cmsmedios-ux
                                 > ts-node ./scripts/setenv.ts "--environment=prod"
2023-01-12T19:21:09.885Z [INFO]: SE ESCRIBIÓ VARIABLES PARA:  ./src/environments/environment.prod.ts
2023-01-12T19:21:12.361Z [WARNING]: - Generating browser application bundles (phase: setup)...
2023-01-12T19:21:14.201Z [WARNING]: [33mWarning:[0m Entry point '@ckeditor/ckeditor5-angular' contains deep imports into '/codebuild/output/src335772648/src/cmsmedios-ux/node_modules/@ckeditor/ckeditor5-watchdog/src/editorwatchdog'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
2023-01-12T19:21:14.202Z [WARNING]: Processing legacy "View Engine" libraries:
2023-01-12T19:21:14.708Z [WARNING]: - @ngx-translate/core [es2015/esm2015] (git+https://github.com/ngx-translate/core.git)
2023-01-12T19:21:15.372Z [WARNING]: - ngx-toastr [es2015/esm2015] (scttcper/ngx-toastr)
2023-01-12T19:21:16.278Z [WARNING]: - ngx-loaders-css [es2015/esm2015] (https://github.com/t7yang/ngx-loaders-css.git)
2023-01-12T19:21:16.983Z [WARNING]: - @ngx-translate/http-loader [es2015/esm2015] (git+https://github.com/ngx-translate/http-loader.git)
2023-01-12T19:21:17.456Z [WARNING]: - ngx-select-ex [es2015/esm2015] (git+ssh://git@github.com:optimistex/ngx-select-ex.git)
2023-01-12T19:21:18.252Z [WARNING]: - @techiediaries/ngx-qrcode [es2015/esm2015] (https://github.com/techiediaries/ngx-qrcode)
2023-01-12T19:21:18.539Z [WARNING]: - ng2-charts [es2015/esm2015] (git+https://github.com/valor-software/ng2-charts.git)
2023-01-12T19:21:18.556Z [WARNING]: - @ckeditor/ckeditor5-angular [es2015/esm2015] (https://github.com/ckeditor/ckeditor5-angular.git)
2023-01-12T19:21:18.591Z [WARNING]: - angular-cropperjs [es2015/esm2015] (https://github.com/matheusdavidson/angular-cropperjs)
2023-01-12T19:21:19.239Z [WARNING]: Encourage the library authors to publish an Ivy distribution.
2023-01-12T19:23:49.934Z [WARNING]: ✔ Browser application bundle generation complete.
2023-01-12T19:23:49.941Z [WARNING]: ✔ Browser application bundle generation complete.
2023-01-12T19:23:49.947Z [WARNING]: - Copying assets...
2023-01-12T19:23:49.983Z [WARNING]: ✔ Copying assets complete.
2023-01-12T19:23:49.983Z [WARNING]: - Generating index html...
2023-01-12T19:23:50.729Z [WARNING]: - Generating index html...
2023-01-12T19:23:50.729Z [WARNING]: 1 rules skipped due to selector errors:
                                    .custom-file-input:lang(en)~.custom-file-label -> unmatched pseudo-class :lang
2023-01-12T19:23:50.730Z [WARNING]: ✔ Index html generation complete.
2023-01-12T19:23:50.730Z [WARNING]: - Generating service worker...
2023-01-12T19:23:50.818Z [WARNING]: ✔ Service worker generation complete.
2023-01-12T19:23:50.825Z [INFO]: Initial Chunk Files           | Names                                                                |  Raw Size | Estimated Transfer Size
                                 main.a8daac597a362de9.js      | main                                                                 |   5.29 MB |                 1.03 MB
                                 styles.65de2da46e6fa215.css   | styles                                                               | 615.52 kB |                66.83 kB
                                 scripts.386f624b4d4f2be1.js   | scripts                                                              |  91.84 kB |                29.64 kB
                                 polyfills.d26b32b9cb8a4a54.js | polyfills                                                            |  36.23 kB |                11.48 kB
                                 runtime.33f7b58a692c98ef.js   | runtime                                                              |   3.52 kB |                 1.69 kB
                                 | Initial Total                                                        |   6.01 MB |                 1.13 MB
                                 Lazy Chunk Files              | Names                                                                |  Raw Size | Estimated Transfer Size
                                 107.2396a80a724f6d57.js       | admin-admin-module                                                   |   2.05 MB |               196.98 kB
                                 263.d0fa6def4602f07e.js       | components-pages-post-post-module                                    | 723.50 kB |                65.13 kB
                                 222.60c7f1716cbd80fb.js       | components-pages-change-password-change-password-module              | 675.39 kB |                57.48 kB
                                 259.ddf81d0de2542254.js       | components-pages-login-login-module                                  | 675.14 kB |                57.56 kB
                                 772.ced7370da495e109.js       | components-pages-recover-password-recover-password-module            | 674.09 kB |                56.92 kB
                                 152.5b54360ca056d552.js       | components-pages-password-locked-password-locked-module              | 673.87 kB |                56.79 kB
                                 912.598e9ed1fbc769de.js       | security-security-module                                             | 671.84 kB |                56.34 kB
                                 79.47bb9907e5a89a93.js        | admin-components-pages-new-post-new-post-module                      | 597.50 kB |                87.70 kB
                                 938.4c3b3c7e8cf4b985.js       | components-pages-post-post-module                                    | 207.42 kB |                38.24 kB
                                 258.2ddd4ff2e5e543cb.js       | components-pages-images-images-module                                | 124.00 kB |                24.04 kB
                                 537.26bcf3db81b646fd.js       | components-pages-videos-videos-module                                |  93.54 kB |                19.03 kB
                                 654.2d04869337041540.js       | security-components-pages-mdf-authenticator-mdf-authenticator-module |  69.13 kB |                17.62 kB
                                 101.d979421154fa08f3.js       | components-two-factory-two-factory-module                            |  45.71 kB |                 7.74 kB
                                 575.1df46179b843d726.js       | components-pages-tags-tags-module                                    |  44.11 kB |                 9.02 kB
                                 82.ad142f83908be267.js        | components-pages-contributions-contributions-module                  |  44.01 kB |                 8.86 kB
                                 503.8d947a5bdc36550c.js       | components-pages-polls-polls-module                                  |  43.06 kB |                 9.96 kB
                                 289.60923503e0216b0d.js       | admin-components-pages-new-post-new-post-module                      |  37.08 kB |                 8.14 kB
                                 317.c0650ce472cbc2bf.js       | components-pages-zones-zone-module                                   |  32.88 kB |                 7.40 kB
                                 956.aca88131eef00e69.js       | components-pages-contributions-contributions-module                  |  32.31 kB |                 7.06 kB
                                 883.98cc9c25664ee757.js       | components-pages-profile-profile-module                              |  26.15 kB |                 6.42 kB
                                 296.5e714e36a1489c4b.js       | components-pages-recipes-recipes-module                              |  22.50 kB |                 5.67 kB
                                 200.558dd79e7c024921.js       | components-pages-people-people-module                                |  17.14 kB |                 4.64 kB
                                 268.dafd4fa6779ba313.js       | components-pages-tags-tags-module                                    |  16.66 kB |                 4.59 kB
                                 232.74e9810eef73eb57.js       | components-pages-trivias-trivias-module                              |  13.48 kB |                 3.83 kB
                                 732.cc053d7cd17882df.js       | components-pages-post-post-module                                    |  12.40 kB |                 3.29 kB
                                 common.2c9e7c52c41cf7d4.js    | common                                                               |   5.18 kB |                 1.51 kB
                                 110.b85237208b12c45c.js       | components-pages-forgot-password-forgot-password-module              |   4.88 kB |                 1.63 kB
                                 901.14a74ba300709bdc.js       | components-pages-forgot-user-forgot-user-module                      |   4.78 kB |                 1.64 kB
                                 23.e498e2b576645df7.js        | admin-components-pages-edit-video-edit-video-module                  | 654 bytes |               338 bytes
                                 593.fbad782df1cb8e9b.js       | admin-components-pages-edit-image-edit-image-module                  | 641 bytes |               327 bytes
                                 241.c49ad6d35fc73c61.js       | admin-components-pages-new-poll-new-poll-module                      | 624 bytes |               315 bytes
                                 Build at: 2023-01-12T19:23:50.821Z - Hash: 5320e6cb8ebf061a - Time: 158320ms
2023-01-12T19:23:50.918Z [INFO]: # Completed phase: build
2023-01-12T19:23:50.921Z [INFO]: ## Build completed successfully
2023-01-12T19:23:50.922Z [INFO]: # Starting caching...
2023-01-12T19:23:50.935Z [INFO]: # Creating cache artifact...
2023-01-12T19:24:07.820Z [INFO]: # Created cache artifact
2023-01-12T19:24:07.951Z [INFO]: # Uploading cache artifact...
2023-01-12T19:24:12.301Z [INFO]: # Uploaded cache artifact
2023-01-12T19:24:12.463Z [INFO]: # Caching completed
2023-01-12T19:24:12.470Z [INFO]: # No custom headers found.
2023-01-12T19:24:12.519Z [INFO]: # Starting build artifact upload process...
2023-01-12T19:24:13.209Z [INFO]: # Uploading build artifact '__artifacts.zip'...
2023-01-12T19:24:13.249Z [INFO]: # Uploading build artifact '__artifactsHash.zip'...
2023-01-12T19:24:13.452Z [INFO]: # Build artifact upload completed
2023-01-12T19:24:13.452Z [INFO]: # Starting environment caching...
2023-01-12T19:24:13.452Z [INFO]: # Uploading environment cache artifact...
2023-01-12T19:24:13.535Z [INFO]: # Uploaded environment cache artifact
2023-01-12T19:24:13.536Z [INFO]: # Environment caching completed
Terminating logging...


=======================
Deploy:
-------------------------------------
2023-01-12T19:24:19 [INFO]: Beginning deployment for application d2wao2oyvt6nan, branch:2FA, buildId 0000000128
2023-01-12T19:24:19 [INFO]: Got archive: 6636260 bytes
2023-01-12T19:24:21 [INFO]: Deployment complete



</details>


### Additional information

_No response_

**Comment by hloriana** [comment]
Hi @vpode, apologies for the delay here. There is an amplify.yml file in the root of your repository and it doesn't include a test phase. The amplify.yml file is going to take precedence over the build commands that are defined in the console. This is why you have successful builds without the test phase completing. 

To resolve this, you should either remove the amplify.yml file in your repository or update the file with the desired test phase.

**Comment by vpode** [comment]
Hi @hloriana, 
Thanks for your answer.
I deleted the repository file and now the error message is different. A message box indicates "One or more tests have failed". I copy the error from the log:

2023-02-17T19:48:25.487Z [INFO]: # Executing command: npx wait-on --timeout 60 http://localhost:3000
2023-02-17T19:48:25.850Z [WARNING]: Error: Timed out waiting for: http://localhost:3000
                                    at /codebuild/output/src951633968/src/cmsmedios-ux/node_modules/wait-on/lib/wait-on.js:132:31
                                    at doInnerSub (/codebuild/output/src951633968/src/cmsmedios-ux/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:31)
                                    at outerNext (/codebuild/output/src951633968/src/cmsmedios-ux/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
                                    at OperatorSubscriber._this._next (/codebuild/output/src951633968/src/cmsmedios-ux/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
                                    at OperatorSubscriber.Subscriber.next (/codebuild/output/src951633968/src/cmsmedios-ux/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
                                    at AsyncAction.work (/codebuild/output/src951633968/src/cmsmedios-ux/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/observable/timer.js:28:28)
                                    at AsyncAction._execute (/codebuild/output/src951633968/src/cmsmedios-ux/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:79:18)
                                    at AsyncAction.execute (/codebuild/output/src951633968/src/cmsmedios-ux/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:67:26)
                                    at AsyncScheduler.flush (/codebuild/output/src951633968/src/cmsmedios-ux/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncScheduler.js:38:33)
                                    at listOnTimeout (internal/timers.js:557:17)
2023-02-17T19:48:25.855Z [ERROR]: !!! Test execution failed, one or more tests are not passing

**Comment by Jay2113** [comment]
Hi @vpode 👋 , thanks for reaching out. I observed that the latest build (164) on your Amplify app `d2wao2oyvt6nan` has succeeded. If you are running into issues with Cypress tests, I'll recommend reviewing their [troubleshooting guide](https://docs.cypress.io/guides/references/troubleshooting) and also any related issues on their [GitHub repository](https://github.com/cypress-io/cypress/issues).
