### ISSUE TITLE
Does importing DynamoDB Storage changes Amplify App's permission?

### ISSUE THREAD

**Issue by williamrjribeiro** [aws-amplify/amplify-hosting#3251]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

PRIVATE

### AWS Region

us-east-1

### Amplify Hosting feature

SSR

### Question

I have deployed a NextJS `v12.3.1` successfully with Amplify. Its API routes need to read/write data from a DynamoDB Table in the same account and region as the NextJS app. The table already exists and is managed by another team.

I have done the steps mentioned [in these docs](https://docs.amplify.aws/cli/storage/import/): import, push, and update env vars.

I'm using Dynamoose `v3.1.0` for interacting with the table. It offers 2 ways of configuring the credentials: [hard coded](https://dynamoosejs.com/getting_started/Configure#dynamoose-specific) and [IAM Role](https://dynamoosejs.com/getting_started/Configure#iam-role).

Unfortunately, none of the configuration approaches is working for me. 

When `accessKeyId` & `secretAccessKey` are hard-coded, the API call throws:

```
CredentialsProviderError: Could not load credentials from any providers

at /var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11
at /var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async coalesceProvider (/var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
at async SignatureV4.credentialProvider (/var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:33:24)
at async SignatureV4.signRequest (/var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:86:29)
at async /var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:16:18
at async StandardRetryStrategy.retry (/var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
at async /var/task/node_modules/@aws-sdk/client-dynamodb/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
at async main (/var/task/node_modules/dynamoose/dist/aws/ddb/internal.js:6:20)

```

Since this approach didn't work, _why the IAM Role didn't work either_!? 

**Shouldn't _wherever the API code is running_ have the proper permissions to read/write from the imported table?**

Can you suggest an alternative to get this to work?
Thanks.

**Comment by williamrjribeiro** [comment]
Hello. I downloaded the build artifacts from the Amplify Console

![amplify-build-artifacts](https://user-images.githubusercontent.com/1503499/214184554-cdea2ad6-8357-402d-9f20-eb0d9eac1a8a.png)

And noticed that it contains the following `run.sh`:

```bash
#!/bin/bash
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
mkdir -p /tmp/app
cp -r /var/task/.next /tmp/app
cp -f /var/task/server.js /tmp/app/server.js
ln -sf /var/task/.env /tmp/app/.env
ln -sf /var/task/next.config.js /tmp/app/next.config.js
ln -sf /var/task/node_modules /tmp/app/node_modules
ln -sf /var/task/package.json /tmp/app/package.json
ln -sf /var/task/public /tmp/app/public
ln -sf /var/task/src /tmp/app/src
node /tmp/app/server.js
```

It _unsets_ some important ENV VARs used by `aws-sdk` to [authenticate service requests](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/loading-node-credentials-environment.html).

Could this be the root cause? Amplify Console does not let me set any env var with `AWS_` prefix...
