### ISSUE TITLE
on root user i can t use aws amplify with error "List apps call failed Network Failure"

### ISSUE THREAD

**Issue by spacemen100** [aws-amplify/amplify-hosting#3346]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

eu-west-3

### Amplify Hosting feature

Access control

### Describe the bug

![aws amazon](https://user-images.githubusercontent.com/91408506/222826729-60a72f20-46f8-44bb-8f0e-777c5941c24b.png)

### Expected behavior

amplify accessible

### Reproduction steps

root user
select amplify

### Build Settings

```yaml
yes
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

![aws amazon](https://user-images.githubusercontent.com/91408506/222826927-6080fcaa-8030-446e-92ae-84292f10e1b4.png)

**Comment by spacemen100** [comment]
Failed to load resource: the server responded with a status of 403 ()
eu-west-3.ccs.amazonaws.com/GetCallerDashboard:1          Failed to load resource: the server responded with a status of 403 ()
ec2.eu-west-3.amazonaws.com/:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
unified.js:127 There was an error with DescribeAccountAttributesCommand:  Error: AuthFailure: AWS was not able to validate the provided access credentials
    at oHe (unified.js:127:71504)
    at async jUe (unified.js:145:71580)
oHe @ unified.js:127
eu-west-3.prod.p13n.console.aws.dev/GetCallerAttributes:1          Failed to load resource: the server responded with a status of 403 ()
eu-west-3.prod.p13n.console.aws.dev/GetCallerAttributes:1          Failed to load resource: the server responded with a status of 403 ()
eu-west-3.prod.p13n.console.aws.dev/GetCallerAttributes:1          Failed to load resource: the server responded with a status of 403 ()
eu-west-3.prod.p13n.console.aws.dev/GetCallerAttributes:1          Failed to load resource: the server responded with a status of 403 ()
securityhub.eu-west-3.amazonaws.com/accounts:1          Failed to load resource: the server responded with a status of 403 ()
/console/home?nc2=h_ct&region=eu-west-3&src=header-signin#:1 Access to fetch at 'https://servicecatalog-appregistry.eu-west-3.amazonaws.com/applications?maxResults=100' from origin 'https://eu-west-3.console.aws.amazon.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
servicecatalog-appregistry.eu-west-3.amazonaws.com/applications?maxResults=100:1          Failed to load resource: net::ERR_FAILED
unified.js:127 Metric key should be less than 32 characters:  apitime_service-catalog-appregistry_LA
(anonymous) @ unified.js:127
ram.eu-west-3.amazonaws.com/listresources:1          Failed to load resource: the server responded with a status of 403 ()
2module.js:92 Error code: undefined TypeError: Failed to fetch
Dz @ module.js:92
ce.us-east-1.amazonaws.com/:1          Failed to load resource: the server responded with a status of 400 ()
ce.us-east-1.amazonaws.com/:1          Failed to load resource: the server responded with a status of 400 ()
health.us-east-1.amazonaws.com/:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
health.us-east-1.amazonaws.com/:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
health.us-east-1.amazonaws.com/:1          Failed to load resource: the server responded with a status of 400 (Bad Request)
support.us-east-1.amazonaws.com/:1          Failed to load resource: the server responded with a status of 400 ()
health.us-east-2.amazonaws.com/:1          Failed to load resource: the server responded with a status of 400 ()
health.us-east-2.amazonaws.com/:1          Failed to load resource: the server responded with a status of 400 ()
health.us-east-2.amazonaws.com/:1          Failed to load resource: the server responded with a status of 400 ()
/console/home?nc2=h_…rc=header-signin#:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
