### ISSUE TITLE
Pipenv not finding correct Python path blocks backend build

### ISSUE THREAD

**Issue by ranyakhemiri** [aws-amplify/amplify-hosting#3559]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3n9bwzts4ju01

### AWS Region

us-east-1

### Amplify Hosting feature

Backend builds

## Issue Description

I am encountering an error while trying to push local changes using the `amplify push` command after adding a Python lambda with the `amplify function add` command. The issue seems to be related to the Python version.

### Steps to Reproduce

1. Run `amplify function add` command to any previously working Amplify project.
2. Make sure Python is 3.10 or below.
3. Update the environmental variables to reflect the new Python version.
4. Try to push local changes using `amplify push` command.

### Expected Behavior

The local changes should be pushed successfully.

### Actual Behavior

Encountering the following error during the `amplify push` command:
```` 
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
[ ] Locking...INFO:root:running egg_info
INFO:root:creating C:\Users\rkhemiri\plant-disease-detection\plantdisease\amplify\backend\function\invokeSGMEndpoint\src\reqlib-metadata\src.egg-info
INFO:root:writing C:/Users/rkhemiri/plant-disease-detection/plantdisease/amplify/backend/function/invokeSGMEndpoint/src/reqlib-metadata\src.egg-info\PKG-INFO
INFO:root:writing dependency_links to C:/Users/rkhemiri/plant-disease-detection/plantdisease/amplify/backend/function/invokeSGMEndpoint/src/reqlib-metadata\src.egg-info\dependency_links.txt
INFO:root:writing top-level names to C:/Users/rkhemiri/plant-disease-detection/plantdisease/amplify/backend/function/invokeSGMEndpoint/src/reqlib-metadata\src.egg-info\top_level.txt
INFO:root:writing manifest file 'C:/Users/rkhemiri/plant-disease-detection/plantdisease/amplify/backend/function/invokeSGMEndpoint/src/reqlib-metadata\src.egg-info\SOURCES.txt'
[== ] Locking...INFO:root:reading manifest file 'C:/Users/rkhemiri/plant-disease-detection/plantdisease/amplify/backend/function/invokeSGMEndpoint/src/reqlib-metadata\src.egg-info\SOURCES.txt'
INFO:root:writing manifest file 'C:/Users/rkhemiri/plant-disease-detection/plantdisease/amplify/backend/function/invokeSGMEndpoint/src/reqlib-metadata\src.egg-info\SOURCES.txt'
Resolving dependencies...
Locking Failed!
[=== ] Locking...
No Python at '"C:\Users\rkhemiri\AppData\Local\Programs\Python\Python311\python.exe'

Traceback (most recent call last):
File "C:\Users\rkhemiri\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\rkhemiri\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
exec(code, run_globals)
File "C:\Users\rkhemiri\AppData\Local\Programs\Python\Python310\Scripts\pipenv.exe_main.py", line 7, in <module>
```` 

### Environment

- Operating System: Windows 
- Python Version: 3.10.10
- Amplify CLI Version:: 12.1.1

### Additional Information

I have downgraded Python from version 3.11 to 3.10 and updated the environmental variables accordingly. I have also made sure to delete the path to the older version of Python in my environment variables (both user and system variables). However, the error still persists.  It seems that Amplify is looking for Python in the wrong path `No Python at 
 C:\Users\rkhemiri\AppData\Local\Programs\Python\Python311\python.exe` even though this path doesn't exist anymore.. 

### Pipfile : 
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.10"
python_full_version = "3.10.10"
```
There are two Pipfiles, one in the root directory and another in the directory of the lambda function (under amplify/backed/function/my_function/ directory) 

Please let me know if you need any further information. Thank you!

**Comment by ranyakhemiri** [comment]
For anyone facing a similar issue, it was solved by delete the Pipfile and the lock files. (deleting the lock file only didn't work for me)
