### ISSUE TITLE
AWS Amplify giving me "internal server error" after succesfull builds and deployement

### ISSUE THREAD

**Issue by maazoly1** [aws-amplify/amplify-hosting#3613]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dhedao702xk3q

### Region

ap-northeast-1:724873498244

### Step

Hosting next js Web app

### Status

Failed

### Issue or question

Iam using nextjs version 13.4.1

Sir I have set Environment Variables,
I have set environment variables in my next.config.js
All builds successfull with no errors

But still getting "internal server error"
Why ?

### Error message

This is my build logs
[log.txt](https://github.com/aws-amplify/amplify-hosting/files/12147939/log.txt)

and this is the error
![WhatsApp Image 2023-07-24 at 9 50 06 PM](https://github.com/aws-amplify/amplify-hosting/assets/87696644/fb98dd7a-02fd-4b7d-a7e4-d23556c904b9)

**Comment by ferdingler** [comment]
Have you checked your SSR compute logs? You should see a CloudWatch Log Group `/aws/amplify/dhedao702xk3q` in your account.

**Comment by maazoly1** [comment]
@ferdingler Yes Sir i have watched the cloud watch logs it is always giving me "Typeerror : handler is not a function"

This our my latest compute logs :

INIT_START Runtime Version: nodejs:16.v16	Runtime Version ARN: arn:aws:lambda:ap-northeast-1::runtime:c1983f4e9ce3930d3093fa38128e12edac2324f4fe99adfb8e0d5fb6b6afadbc

LOGS	Name: bootstrap	State: Subscribed	Types: [Platform, Function]

START RequestId: 513a9d76-01f8-4ff3-99b8-17e08be2b504 Version: $LATEST

TypeError: handler is not a function

at Server.<anonymous> (/tmp/app/server.js:29:11)

at Server.emit (node:events:513:28)

at parserOnIncoming (node:_http_server:998:12)

at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)

REPORT RequestId: 513a9d76-01f8-4ff3-99b8-17e08be2b504	Duration: 59.12 ms	Billed Duration: 60 ms	Memory Size: 1024 MB	Max Memory Used: 79 MB	Init Duration: 219.53 ms	

START RequestId: 64be01c5-81c6-4d94-89e0-29bed8f2fe61 Version: $LATEST

TypeError: handler is not a function

at Server.<anonymous> (/tmp/app/server.js:29:11)

at Server.emit (node:events:513:28)

at parserOnIncoming (node:_http_server:998:12)

at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)

REPORT RequestId: 64be01c5-81c6-4d94-89e0-29bed8f2fe61	Duration: 5.83 ms	Billed Duration: 6 ms	Memory Size: 1024 MB	Max Memory Used: 80 MB

And From Here i have given you above logs
![WhatsApp Image 2023-07-25 at 9 41 33 AM](https://github.com/aws-amplify/amplify-hosting/assets/87696644/9352450c-6bfc-42a2-836f-cd988f002d05)

**Comment by victorccccc** [comment]
Hi @maazoly1, it looks like your website is correctly serving the content now. Please let us know if issue persists. Thanks

**Comment by HeresMyQuestion** [comment]
Hello. I would appreciate it if someone could explain to me the meaning of "The verification file must be served as a 200".
