### ISSUE TITLE
Preview URLs throwing Internal Server Error

### ISSUE THREAD

**Issue by DarkPhoenix2704** [aws-amplify/amplify-hosting#3726]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2fyqg2qu4w861

### AWS Region

ap-southeast-2

### Amplify Hosting feature

Web previews

### Frontend framework

Next.js

### Next.js version

13.4.9

### Next.js router

Pages Router

### Describe the bug

![image](https://github.com/aws-amplify/amplify-hosting/assets/64391274/869a062d-2760-4f33-a139-2abd04144ca3)

Preview URLs gives Internal Server error

### Expected behavior

Website should load

### Reproduction steps

Create a preview URL

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @DarkPhoenix2704 👋 , thanks for raising this!

Have you reviewed the [hosting compute logs](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-CloudWatch-logs.html) that Amplify delivers to Amazon CloudWatch in regards to the compute runtime? The logs should be present under the log group named as `/aws/amplify/{app-id}`. These logs should highlight any errors that may have occurred in the runtime.

**Comment by DarkPhoenix2704** [comment]
2023-09-26T09:15:50.722+05:30	INIT_START Runtime Version: nodejs:16.v19 Runtime Version ARN: arn:aws:lambda:ap-southeast-2::runtime:d1151b12ca57ae5a7756c59d01d400082fbc5866d3a96d51cf4839c32c5d2a7e

2023-09-26T09:15:50.769+05:30	LOGS Name: bootstrap State: Subscribed Types: [Platform, Function]

2023-09-26T09:15:51.285+05:30	- ready started server on 127.0.0.1:3000, url: http://127.0.0.1:3000

2023-09-26T09:15:51.298+05:30	START RequestId: d884c5b4-2a20-485e-8882-a31a0cc9c613 Version: $LATEST

2023-09-26T09:15:54.117+05:30	Warning - Configuring `keepAlive: false` is deprecated. Use `{ headers: { connection: "close" } }` instead.

2023-09-26T09:15:57.546+05:30	TypeError: Cannot read properties of null (reading 'useEffect')

2023-09-26T09:15:57.546+05:30	at Module.exports.useEffect (/var/task/node_modules/react/cjs/react.production.min.js:24:292)

2023-09-26T09:15:57.546+05:30	at QueryClientProvider (file:///var/task/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:46:9)

2023-09-26T09:15:57.546+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:111:274)

2023-09-26T09:15:57.546+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:91)

2023-09-26T09:15:57.546+05:30	at hg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:155)

2023-09-26T09:15:57.546+05:30	at jg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:100)

2023-09-26T09:15:57.546+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:222)

2023-09-26T09:15:57.546+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:113:196)

2023-09-26T09:15:57.546+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:91)

2023-09-26T09:15:57.546+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:9)

2023-09-26T09:15:57.546+05:30	TypeError: Cannot read properties of null (reading 'useEffect')

2023-09-26T09:15:57.546+05:30	at Module.exports.useEffect (/var/task/node_modules/react/cjs/react.production.min.js:24:292)

2023-09-26T09:15:57.546+05:30	at QueryClientProvider (file:///var/task/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:46:9)

2023-09-26T09:15:57.546+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:111:274)

2023-09-26T09:15:57.546+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:91)

2023-09-26T09:15:57.546+05:30	at hg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:155)

2023-09-26T09:15:57.546+05:30	at jg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:100)

2023-09-26T09:15:57.546+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:222)

2023-09-26T09:15:57.546+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:113:196)

2023-09-26T09:15:57.546+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:91)

2023-09-26T09:15:57.546+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:9)

2023-09-26T09:15:57.558+05:30	TypeError: Cannot read properties of null (reading 'useEffect')

2023-09-26T09:15:57.558+05:30	at Module.exports.useEffect (/var/task/node_modules/react/cjs/react.production.min.js:24:292)

2023-09-26T09:15:57.558+05:30	at QueryClientProvider (file:///var/task/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:46:9)

2023-09-26T09:15:57.558+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:111:274)

2023-09-26T09:15:57.558+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:91)

2023-09-26T09:15:57.558+05:30	at hg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:155)

2023-09-26T09:15:57.558+05:30	at jg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:100)

2023-09-26T09:15:57.558+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:222)

2023-09-26T09:15:57.558+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:113:196)

2023-09-26T09:15:57.558+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:91)

2023-09-26T09:15:57.558+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:9)

2023-09-26T09:15:57.559+05:30	TypeError: Cannot read properties of null (reading 'useEffect')

2023-09-26T09:15:57.559+05:30	at Module.exports.useEffect (/var/task/node_modules/react/cjs/react.production.min.js:24:292)

2023-09-26T09:15:57.559+05:30	at QueryClientProvider (file:///var/task/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:46:9)

2023-09-26T09:15:57.559+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:111:274)

2023-09-26T09:15:57.559+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:91)

2023-09-26T09:15:57.559+05:30	at hg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:120:155)

2023-09-26T09:15:57.559+05:30	at jg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:119:100)

2023-09-26T09:15:57.559+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:222)

2023-09-26T09:15:57.559+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:113:196)

2023-09-26T09:15:57.559+05:30	at Y (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:117:91)

2023-09-26T09:15:57.559+05:30	at gg (/var/task/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.production.min.js:112:9)

2023-09-26T09:15:57.582+05:30	REPORT RequestId: d884c5b4-2a20-485e-8882-a31a0cc9c613 Duration: 6284.78 ms Billed Duration: 6285 ms Memory Size: 1024 MB Max Memory Used: 334 MB Init Duration: 575.00 ms

2023-09-26T09:15:58.760+05:30	START RequestId: ca923083-ceb7-4aab-b0a5-d72566078890 Version: $LATEST

2023-09-26T09:15:58.779+05:30	REPORT RequestId: ca923083-ceb7-4aab-b0a5-d72566078890 Duration: 18.61 ms Billed Duration: 19 ms Memory Size: 1024 MB Max Memory Used: 335 MB

**Comment by Jay2113** [comment]
@DarkPhoenix2704 Are you observing these errors even when building locally using `npm run build` ?
