### ISSUE TITLE
Webpack 5 build stuck on AWS Amplify

### ISSUE THREAD

**Issue by andraspatka-dev** [aws-amplify/amplify-hosting#3778]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1ibz1zzj8f3a3

### AWS Region

eu-west-2

### Amplify Hosting feature

Frontend builds

### Frontend framework

Next.js

### Next.js version

13.5.4

### Next.js router

App Router

### Describe the bug

I'm trying to integrate storybook into a large nextjs application. I added all of the required configurations (devDependencies, scripts in package.json, storybook configs under .storybook and stories).

The first time building the app, it took about 5 minutes and was deployed without any issues.

I made a change to the application (added some new storybook stories) and pushed, but that time the build got stuck at a certain point.

I'm running `storybook build` which takes about `20s` on my local machine, but gets stuck after a couple of seconds on AWS amplify. It gets stuck at different percentages. No errors are getting thrown, the build is just unresponsive.

I have cancelled and restarted the build about 8 times. I also tried rebuilding the commit which worked previously but that one also got stuck.

### Expected behavior

The build should finish in about 5 minutes and should generate all of the required static files.

### Reproduction steps

1. Add storybook to your nextjs app
2. Setup AWS Amplify app for hosting storybook
3. Push and start build

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build-storybook
  artifacts:
    baseDirectory: storybook-static
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
 # Executing command: yarn run build-storybook
2023-10-30T16:40:55.224Z [INFO]: yarn run v1.22.19
2023-10-30T16:40:55.249Z [INFO]: $ storybook build
2023-10-30T16:40:56.554Z [INFO]: @storybook/cli v7.5.2
2023-10-30T16:40:56.559Z [INFO]: info => Cleaning outputDir: /storybook-static
2023-10-30T16:40:57.065Z [INFO]: info
2023-10-30T16:40:57.065Z [INFO]: => Loading presets
2023-10-30T16:40:57.375Z [INFO]: info
2023-10-30T16:40:57.375Z [INFO]: => Building manager..
2023-10-30T16:40:57.671Z [INFO]: info
2023-10-30T16:40:57.671Z [INFO]: => Manager built (296 ms)
2023-10-30T16:40:57.677Z [INFO]: info => Building preview..
2023-10-30T16:40:58.058Z [INFO]: info
2023-10-30T16:40:58.059Z [INFO]: => Copying static files: /codebuild/output/src1264709282/src/redacted/node_modules/@storybook/manager/static at /codebuild/output/src1264709282/src/redacted/storybook-static/sb-common-assets
2023-10-30T16:40:58.069Z [INFO]: WARN
2023-10-30T16:40:58.069Z [INFO]: No story files found for the specified pattern: stories.@(js|jsx|mjs|ts|tsx)
2023-10-30T16:40:58.218Z [INFO]: info Addon-docs: using MDX2
2023-10-30T16:40:58.232Z [INFO]: info => Using implicit CSS loaders
2023-10-30T16:40:58.689Z [INFO]: info
2023-10-30T16:40:58.690Z [INFO]: => Using default Webpack5 setup
2023-10-30T16:40:58.896Z [WARNING]: <s> [webpack.Progress] 0%
2023-10-30T16:40:58.897Z [WARNING]: <s> [webpack.Progress] 1% setup before run
                                    <s> [webpack.Progress] 1% setup before run NodeEnvironmentPlugin
2023-10-30T16:40:58.897Z [WARNING]: <s> [webpack.Progress] 1% setup before run
2023-10-30T16:40:58.897Z [WARNING]: <s> [webpack.Progress] 2% setup run
2023-10-30T16:40:58.897Z [WARNING]: <s> [webpack.Progress] 2% setup run
2023-10-30T16:40:58.900Z [WARNING]: <s> [webpack.Progress] 4% setup normal module factory
2023-10-30T16:40:58.901Z [WARNING]: <s> [webpack.Progress] 4% setup normal module factory CaseSensitivePathsPlugin
                                    <s> [webpack.Progress] 4% setup normal module factory IgnorePlugin
                                    <s> [webpack.Progress] 4% setup normal module factory
2023-10-30T16:40:58.901Z [WARNING]: <s> [webpack.Progress] 5% setup context module factory
2023-10-30T16:40:58.901Z [WARNING]: <s> [webpack.Progress] 5% setup context module factory IgnorePlugin
                                    <s> [webpack.Progress] 5% setup context module factory
2023-10-30T16:40:58.901Z [WARNING]: <s> [webpack.Progress] 6% setup before compile
                                    <s> [webpack.Progress] 6% setup before compile ProgressPlugin
2023-10-30T16:40:58.902Z [WARNING]: <s> [webpack.Progress] 6% setup before compile
2023-10-30T16:40:58.902Z [WARNING]: <s> [webpack.Progress] 7% setup compile
2023-10-30T16:40:58.902Z [WARNING]: <s> [webpack.Progress] 7% setup compile ExternalsPlugin
2023-10-30T16:40:58.902Z [WARNING]: <s> [webpack.Progress] 7% setup compile ExternalsPlugin
                                    <s> [webpack.Progress] 7% setup compile
2023-10-30T16:40:58.912Z [WARNING]: <s> [webpack.Progress] 8% setup compilation
2023-10-30T16:40:58.913Z [WARNING]: <s> [webpack.Progress] 8% setup compilation unplugin-csf
                                    <s> [webpack.Progress] 8% setup compilation ArrayPushCallbackChunkFormatPlugin
2023-10-30T16:40:58.913Z [WARNING]: <s> [webpack.Progress] 8% setup compilation JsonpChunkLoadingPlugin
2023-10-30T16:40:58.913Z [WARNING]: <s> [webpack.Progress] 8% setup compilation StartupChunkDependenciesPlugin
2023-10-30T16:40:58.913Z [WARNING]: <s> [webpack.Progress] 8% setup compilation ImportScriptsChunkLoadingPlugin
2023-10-30T16:40:58.913Z [WARNING]: <s> [webpack.Progress] 8% setup compilation FetchCompileWasmPlugin
                                    <s> [webpack.Progress] 8% setup compilation FetchCompileAsyncWasmPlugin
2023-10-30T16:40:58.913Z [WARNING]: <s> [webpack.Progress] 8% setup compilation WorkerPlugin
2023-10-30T16:40:58.914Z [WARNING]: <s> [webpack.Progress] 8% setup compilation SplitChunksPlugin
2023-10-30T16:40:58.914Z [WARNING]: <s> [webpack.Progress] 8% setup compilation RuntimeChunkPlugin
2023-10-30T16:40:58.914Z [WARNING]: <s> [webpack.Progress] 8% setup compilation ResolverCachePlugin
                                    <s> [webpack.Progress] 8% setup compilation HtmlWebpackPlugin
2023-10-30T16:40:58.915Z [WARNING]: <s> [webpack.Progress] 8% setup compilation
2023-10-30T16:40:58.915Z [WARNING]: <s> [webpack.Progress] 9% setup compilation
2023-10-30T16:40:58.915Z [WARNING]: <s> [webpack.Progress] 9% setup compilation DefinePlugin
2023-10-30T16:40:58.918Z [WARNING]: <s> [webpack.Progress] 9% setup compilation ProvidePlugin
2023-10-30T16:40:58.918Z [WARNING]: <s> [webpack.Progress] 9% setup compilation ProgressPlugin
2023-10-30T16:40:58.919Z [WARNING]: <s> [webpack.Progress] 9% setup compilation DocGenPlugin
2023-10-30T16:40:58.920Z [WARNING]: <s> [webpack.Progress] 9% setup compilation DefinePlugin
2023-10-30T16:40:58.920Z [WARNING]: <s> [webpack.Progress] 9% setup compilation DefinePlugin
                                    <s> [webpack.Progress] 9% setup compilation ProvidePlugin
2023-10-30T16:40:58.920Z [WARNING]: <s> [webpack.Progress] 9% setup compilation ChunkPrefetchPreloadPlugin
2023-10-30T16:40:58.920Z [WARNING]: <s> [webpack.Progress] 9% setup compilation SourceMapDevToolPlugin
2023-10-30T16:40:58.921Z [WARNING]: <s> [webpack.Progress] 9% setup compilation JavascriptModulesPlugin
2023-10-30T16:40:58.921Z [WARNING]: <s> [webpack.Progress] 9% setup compilation JsonModulesPlugin
2023-10-30T16:40:58.921Z [WARNING]: <s> [webpack.Progress] 9% setup compilation AssetModulesPlugin
2023-10-30T16:40:58.921Z [WARNING]: <s> [webpack.Progress] 9% setup compilation EntryPlugin
2023-10-30T16:40:58.921Z [WARNING]: <s> [webpack.Progress] 9% setup compilation RuntimePlugin
2023-10-30T16:40:58.922Z [WARNING]: <s> [webpack.Progress] 9% setup compilation InferAsyncModulesPlugin
2023-10-30T16:40:58.922Z [WARNING]: <s> [webpack.Progress] 9% setup compilation DataUriPlugin
2023-10-30T16:40:58.922Z [WARNING]: <s> [webpack.Progress] 9% setup compilation FileUriPlugin
2023-10-30T16:40:58.922Z [WARNING]: <s> [webpack.Progress] 9% setup compilation CompatibilityPlugin
2023-10-30T16:40:58.922Z [WARNING]: <s> [webpack.Progress] 9% setup compilation HarmonyModulesPlugin
2023-10-30T16:40:58.923Z [WARNING]: <s> [webpack.Progress] 9% setup compilation AMDPlugin
2023-10-30T16:40:58.923Z [WARNING]: <s> [webpack.Progress] 9% setup compilation RequireJsStuffPlugin
2023-10-30T16:40:58.923Z [WARNING]: <s> [webpack.Progress] 9% setup compilation CommonJsPlugin
2023-10-30T16:40:58.923Z [WARNING]: <s> [webpack.Progress] 9% setup compilation LoaderPlugin
2023-10-30T16:40:58.923Z [WARNING]: <s> [webpack.Progress] 9% setup compilation LoaderPlugin
2023-10-30T16:40:58.924Z [WARNING]: <s> [webpack.Progress] 9% setup compilation NodeStuffPlugin
2023-10-30T16:40:58.924Z [WARNING]: <s> [webpack.Progress] 9% setup compilation APIPlugin
2023-10-30T16:40:58.924Z [WARNING]: <s> [webpack.Progress] 9% setup compilation ExportsInfoApiPlugin
2023-10-30T16:40:58.924Z [WARNING]: <s> [webpack.Progress] 9% setup compilation WebpackIsIncludedPlugin
2023-10-30T16:40:58.924Z [WARNING]: <s> [webpack.Progress] 9% setup compilation ConstPlugin
2023-10-30T16:40:58.925Z [WARNING]: <s> [webpack.Progress] 9% setup compilation UseStrictPlugin
2023-10-30T16:40:58.925Z [WARNING]: <s> [webpack.Progress] 9% setup compilation RequireIncludePlugin
2023-10-30T16:40:58.925Z [WARNING]: <s> [webpack.Progress] 9% setup compilation RequireEnsurePlugin
2023-10-30T16:40:58.925Z [WARNING]: <s> [webpack.Progress] 9% setup compilation RequireContextPlugin
2023-10-30T16:40:58.925Z [WARNING]: <s> [webpack.Progress] 9% setup compilation ImportPlugin
2023-10-30T16:40:58.925Z [WARNING]: <s> [webpack.Progress] 9% setup compilation ImportMetaContextPlugin
2023-10-30T16:40:58.925Z [WARNING]: <s> [webpack.Progress] 9% setup compilation SystemPlugin
2023-10-30T16:40:58.925Z [WARNING]: <s> [webpack.Progress] 9% setup compilation ImportMetaPlugin
2023-10-30T16:40:58.925Z [WARNING]: <s> [webpack.Progress] 9% setup compilation URLPlugin
2023-10-30T16:40:58.925Z [WARNING]: <s> [webpack.Progress] 9% setup compilation DefaultStatsFactoryPlugin
2023-10-30T16:40:58.926Z [WARNING]: <s> [webpack.Progress] 9% setup compilation DefaultStatsPresetPlugin
2023-10-30T16:40:58.926Z [WARNING]: <s> [webpack.Progress] 9% setup compilation DefaultStatsPrinterPlugin
2023-10-30T16:40:58.926Z [WARNING]: <s> [webpack.Progress] 9% setup compilation JavascriptMetaInfoPlugin
2023-10-30T16:40:58.926Z [WARNING]: <s> [webpack.Progress] 9% setup compilation EnsureChunkConditionsPlugin
2023-10-30T16:40:58.926Z [WARNING]: <s> [webpack.Progress] 9% setup compilation RemoveEmptyChunksPlugin
2023-10-30T16:40:58.926Z [WARNING]: <s> [webpack.Progress] 9% setup compilation MergeDuplicateChunksPlugin
2023-10-30T16:40:58.926Z [WARNING]: <s> [webpack.Progress] 9% setup compilation FlagIncludedChunksPlugin
2023-10-30T16:40:58.926Z [WARNING]: <s> [webpack.Progress] 9% setup compilation SideEffectsFlagPlugin
2023-10-30T16:40:58.927Z [WARNING]: <s> [webpack.Progress] 9% setup compilation FlagDependencyExportsPlugin
2023-10-30T16:40:58.927Z [WARNING]: <s> [webpack.Progress] 9% setup compilation FlagDependencyUsagePlugin
2023-10-30T16:40:58.927Z [WARNING]: <s> [webpack.Progress] 9% setup compilation InnerGraphPlugin
2023-10-30T16:40:58.927Z [WARNING]: <s> [webpack.Progress] 9% setup compilation MangleExportsPlugin
2023-10-30T16:40:58.927Z [WARNING]: <s> [webpack.Progress] 9% setup compilation ModuleConcatenationPlugin
2023-10-30T16:40:58.928Z [WARNING]: <s> [webpack.Progress] 9% setup compilation NoEmitOnErrorsPlugin
2023-10-30T16:40:58.928Z [WARNING]: <s> [webpack.Progress] 9% setup compilation RealContentHashPlugin
                                    <s> [webpack.Progress] 9% setup compilation WasmFinalizeExportsPlugin
2023-10-30T16:40:58.928Z [WARNING]: <s> [webpack.Progress] 9% setup compilation NamedModuleIdsPlugin
                                    <s> [webpack.Progress] 9% setup compilation DeterministicChunkIdsPlugin
                                    <s> [webpack.Progress] 9% setup compilation DefinePlugin
2023-10-30T16:40:58.929Z [WARNING]: <s> [webpack.Progress] 9% setup compilation TerserPlugin
2023-10-30T16:40:58.931Z [WARNING]: <s> [webpack.Progress] 9% setup compilation TemplatedPathPlugin
2023-10-30T16:40:58.931Z [WARNING]: <s> [webpack.Progress] 9% setup compilation RecordIdsPlugin
2023-10-30T16:40:58.931Z [WARNING]: <s> [webpack.Progress] 9% setup compilation WarnCaseSensitiveModulesPlugin
                                    <s> [webpack.Progress] 9% setup compilation IgnoreWarningsPlugin
                                    <s> [webpack.Progress] 9% setup compilation
2023-10-30T16:40:58.932Z [WARNING]: <s> [webpack.Progress] 10% building
2023-10-30T16:40:58.932Z [WARNING]: <s> [webpack.Progress] 10% building 0/1 entries 0/0 dependencies 0/0 modules
2023-10-30T16:40:59.771Z [WARNING]: <s> [webpack.Progress] 10% building 0/1 entries 8/21 dependencies 3/8 modules
2023-10-30T16:41:01.879Z [WARNING]: <s> [webpack.Progress] 10% building 0/1 entries 9/22 dependencies 3/8 modules
2023-10-30T16:41:01.887Z [WARNING]: <s> [webpack.Progress] 10% building import loader ./node_modules/@storybook/mdx2-csf/loader.js
2023-10-30T16:41:02.047Z [WARNING]: <s> [webpack.Progress] 10% building 0/1 entries 9/22 dependencies 3/9 modules
2023-10-30T16:41:02.627Z [WARNING]: <s> [webpack.Progress] 10% building 0/1 entries 10/22 dependencies 3/9 modules
2023-10-30T16:41:03.224Z [WARNING]: <s> [webpack.Progress] 10% building 0/1 entries 10/23 dependencies 3/10 modules
2023-10-30T16:41:03.469Z [WARNING]: <s> [webpack.Progress] 10% building import loader ./node_modules/@storybook/nextjs/dist/next-image-loader-stub.js
2023-10-30T16:41:03.478Z [WARNING]: <s> [webpack.Progress] 10% building 0/1 entries 33/42 dependencies 3/33 modules
2023-10-30T16:41:03.523Z [WARNING]: <s> [webpack.Progress] 10% building import loader ./node_modules/babel-loader/lib/index.js
2023-10-30T16:41:03.528Z [WARNING]: <s> [webpack.Progress] 10% building 0/1 entries 34/42 dependencies 3/34 modules
2023-10-30T16:41:03.707Z [WARNING]: <s> [webpack.Progress] 10% building import loader ./node_modules/unplugin/dist/webpack/loaders/load.js
2023-10-30T16:41:03.709Z [WARNING]: <s> [webpack.Progress] 10% building 0/1 entries 45/68 dependencies 14/41 modules
2023-10-30T16:41:04.980Z [WARNING]: <s> [webpack.Progress] 10% building 0/1 entries 48/85 dependencies 18/42 modules
2023-10-30T16:41:05.945Z [WARNING]: <s> [webpack.Progress] 11% building 0/1 entries 58/99 dependencies 21/44 modules
2023-10-30T16:41:07.209Z [WARNING]: <s> [webpack.Progress] 11% building 0/1 entries 58/100 dependencies 22/44 modules
2023-10-30T16:41:07.919Z [WARNING]: <s> [webpack.Progress] 11% building 0/1 entries 100/109 dependencies 24/76 modules
2023-10-30T16:41:07.994Z [WARNING]: <s> [webpack.Progress] 11% building import loader ./node_modules/style-loader/dist/cjs.js
2023-10-30T16:41:07.996Z [WARNING]: <s> [webpack.Progress] 11% building import loader ./node_modules/css-loader/dist/cjs.js
2023-10-30T16:41:08.046Z [WARNING]: <s> [webpack.Progress] 11% building import loader ./node_modules/postcss-loader/dist/cjs.js
2023-10-30T16:41:08.051Z [WARNING]: <s> [webpack.Progress] 11% building 0/1 entries 109/118 dependencies 25/85 modules
2023-10-30T16:41:08.676Z [WARNING]: <s> [webpack.Progress] 11% building 0/1 entries 177/179 dependencies 33/147 modules
2023-10-30T16:41:10.345Z [WARNING]: <s> [webpack.Progress] 11% building 0/1 entries 239/300 dependencies 33/196 modules
2023-10-30T16:41:10.775Z [WARNING]: Browserslist: caniuse-lite is outdated. Please run:
                                    npx update-browserslist-db@latest
                                    Why you should do it regularly: https://github.com/browserslist/update-db#readme
2023-10-30T16:41:11.385Z [WARNING]: <s> [webpack.Progress] 12% building 0/1 entries 400/553 dependencies 38/221 modules
2023-10-30T16:41:11.905Z [WARNING]: <s> [webpack.Progress] 12% building 0/1 entries 719/800 dependencies 54/303 modules
2023-10-30T16:41:12.624Z [WARNING]: <s> [webpack.Progress] 13% building 0/1 entries 884/900 dependencies 57/386 modules
2023-10-30T16:41:13.340Z [WARNING]: <s> [webpack.Progress] 13% building 0/1 entries 967/1000 dependencies 58/413 modules
2023-10-30T16:41:13.914Z [WARNING]: <s> [webpack.Progress] 14% building 0/1 entries 1073/1100 dependencies 74/428 modules
2023-10-30T16:41:15.269Z [WARNING]: <s> [webpack.Progress] 15% building 0/1 entries 1260/1300 dependencies 106/465 modules
2023-10-30T16:41:15.853Z [WARNING]: <s> [webpack.Progress] 17% building 0/1 entries 1590/1600 dependencies 134/586 modules
2023-10-30T16:41:16.551Z [WARNING]: <s> [webpack.Progress] 17% building 0/1 entries 1700/1724 dependencies 145/633 modules
2023-10-30T16:41:17.232Z [WARNING]: <s> [webpack.Progress] 18% building 0/1 entries 1800/1857 dependencies 155/656 modules
2023-10-30T16:41:17.975Z [WARNING]: <s> [webpack.Progress] 26% building 0/1 entries 2162/2186 dependencies 300/780 modules
2023-10-30T16:41:18.518Z [WARNING]: <s> [webpack.Progress] 27% building 0/1 entries 2400/2565 dependencies 311/966 modules
2023-10-30T16:41:19.170Z [WARNING]: <s> [webpack.Progress] 27% building 0/1 entries 2799/2900 dependencies 363/1147 modules
2023-10-30T16:41:19.879Z [WARNING]: <s> [webpack.Progress] 27% building 0/1 entries 3672/3700 dependencies 414/1299 modules
2023-10-30T16:41:20.441Z [WARNING]: <s> [webpack.Progress] 46% building 0/1 entries 4107/4158 dependencies 900/1371 modules
```

</details>

### Additional information

I tried rebuilding another AWS Amplify app that I have which also uses nextjs. The build finished without issues, so I'm assuming it's not caused by a general AWS Amplify build outage.

Docker image that is used for the build is: `public.ecr.aws/docker/library/node:16`

Platform being used is `Web`.

Error message in the console is 
```
Build failed to complete successfully. Reason: Build timed out
```

**Comment by andraspatka-dev** [comment]
I recreated the application, new id is d11xtko56oucks. Issue still exists.

**Comment by andraspatka-dev** [comment]
Okay so it turns out it was an error in the application itself. It was related to this issue: https://github.com/diegomura/react-pdf/issues/1678

But it's not clear why the build logs didn't show the output. It's probably because storybook asks for consent to send telemetry after an error:

```
=> Failed to build the preview
SB_BUILDER-WEBPACK5_0002 (WebpackInvocationError): Module not found: Error: Can't resolve './zlib_bindings' in './node_modules/zlib/lib'
    at ./node_modules/@storybook/builder-webpack5/dist/index.js:1:7584
    at ./node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (./node_modules/webpack/lib/Cache.js:150:23)
    at ./node_modules/webpack/lib/Compiler.js:1229:15
    at Hook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (./node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (./node_modules/webpack/lib/Compiler.js:1222:23)
    at ./node_modules/@storybook/builder-webpack5/dist/index.js:1:7569
    at finalCallback (./node_modules/webpack/lib/Compiler.js:441:32)
    at onCompiled (./node_modules/webpack/lib/Compiler.js:450:20)
    at ./node_modules/webpack/lib/Compiler.js:1177:21
    at eval (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at ./node_modules/webpack/lib/EntryPlugin.js:49:5
    at ./node_modules/webpack/lib/Compilation.js:2198:13
    at ./node_modules/webpack/lib/Compilation.js:2090:6
    at ./node_modules/webpack/lib/Compilation.js:1952:13
    at ./node_modules/webpack/lib/util/AsyncQueue.js:346:6
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
✔ Would you like to help improve Storybook by sending anonymous crash reports?
```

To debug the issue in AWS Amplify, I added the --disable-telemetry option which then allowed the build to spit out the actual error logs.

The fix in the end turned out to be to update my `package.json` scripts to fix the zlib error and also disable telemetry:

```
"build-storybook": "cp ./node_modules/zlib/lib/zlib.js ./node_modules/zlib/lib/zlib_bindings.js && storybook build --disable-telemetry"
```
