### ISSUE TITLE
pnpm file protocol linkage not working

### ISSUE THREAD

**Issue by Lezzio** [aws-amplify/amplify-hosting#3788]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3q127va4gyote

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments, Frontend builds, Monorepo

### Frontend framework

Next.js

### Next.js version

13.1.5

### Next.js router

Pages Router

### Describe the bug

We're using a NX monorepo to build a NextJS application. This NextJS application depends on local packages within the monorepo. To add the dependencies we tried using the pnpm file protocol in the package.json as such:
```
    "@hcp-portal-app/frontend-shared": "file:../shared",
    "@hcp-portal-app/logger": "file:../../packages/logger",
```

The logger package itself depends on dependency-injector this way:
`"@hcp-portal-app/dependency-injector": "file:../dependency-injector"`

It builds and works perfectly locally. However, on Amplify, we get an exception "cannot find module..." when the first package resolution using this protocol takes place (see the logs)

### Expected behavior

We expect the file protocol to work for dependency resolution

### Reproduction steps

1. Create a NextJS app with pnpm
2. Add a file protocol dependency in the package.json (see bug description)
3. Run on Amplify

### Build Settings

```yaml
version: "1.0"
applications:
  - appRoot: apps/campus
    frontend:
      phases:
        preBuild:
          commands:
            - echo "node-linker=hoisted" >> .npmrc
            - echo "//npm.pkg.github.com/:_authToken=[GITHUB_TOKEN]" >> .npmrc
            - corepack enable
            - corepack prepare pnpm@8.3.1 --activate
            - export NODE_OPTIONS=--max-old-space-size=8192
            - pnpm install --shamefully-hoist --ignore-script
            - cd ../..
            - pnpm package
            - cd apps/campus
        build:
          commands:
            - env | grep -E '[SENSITIVE_VARIABLES]' >> .env.production
            - pnpm build --no-lint
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
        discard-paths: "yes"
        exclude-paths:
          - "**/cache/**/*"
```

### Log output

<details>

```
# Put your logs below this line
                                 # Starting phase: preBuild
2023-11-06T11:26:15.524Z [INFO]: # Executing command: echo "node-linker=hoisted" >> .npmrc
                                 # Executing command: echo "//npm.pkg.github.com/:_authToken=***" >> .npmrc
                                 # Executing command: corepack enable
2023-11-06T11:26:15.600Z [INFO]: # Executing command: corepack prepare pnpm@8.3.1 --activate
2023-11-06T11:26:15.671Z [INFO]: Preparing pnpm@8.3.1 for immediate activation...
2023-11-06T11:26:16.105Z [INFO]: # Executing command: export NODE_OPTIONS=--max-old-space-size=8192
2023-11-06T11:26:16.106Z [INFO]: # Executing command: pnpm install --shamefully-hoist --ignore-script
2023-11-06T11:26:16.713Z [INFO]: Scope: all 21 workspace projects
2023-11-06T11:26:17.747Z [INFO]: ../..                                    |    +3709 ++++++++++++++++++++++++++++
2023-11-06T11:26:18.020Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1, added 0
2023-11-06T11:26:18.113Z [INFO]: Packages are hard linked from the content-addressable store to the virtual store.
                                 Content-addressable store is at: /codebuild/output/.pnpm-store/v3
                                 Virtual store is at:             ../../node_modules/.pnpm
2023-11-06T11:26:19.026Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 53, added 42
2023-11-06T11:26:20.027Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 100, added 124
2023-11-06T11:26:21.026Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 173, added 200
2023-11-06T11:26:22.030Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 279, added 407
2023-11-06T11:26:23.036Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 306, added 437
2023-11-06T11:26:24.037Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 335, added 459
2023-11-06T11:26:25.039Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 351, added 483
2023-11-06T11:26:26.043Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 400, added 544
2023-11-06T11:26:27.045Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 422, added 579
2023-11-06T11:26:28.046Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 444, added 597
2023-11-06T11:26:29.047Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 465, added 616
2023-11-06T11:26:30.047Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 508, added 659
2023-11-06T11:26:31.047Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 546, added 705
2023-11-06T11:26:32.047Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 579, added 736
2023-11-06T11:26:33.048Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 610, added 806
2023-11-06T11:26:34.048Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 630, added 865
2023-11-06T11:26:35.049Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 664, added 912
2023-11-06T11:26:36.049Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 711, added 1030
2023-11-06T11:26:37.053Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 753, added 1081
2023-11-06T11:26:38.054Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 793, added 1109
2023-11-06T11:26:39.055Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 815, added 1164
2023-11-06T11:26:40.054Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 882, added 1250
2023-11-06T11:26:41.055Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 895, added 1264
2023-11-06T11:26:42.056Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 938, added 1315
2023-11-06T11:26:43.065Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1018, added 1465
2023-11-06T11:26:44.066Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1087, added 1538
2023-11-06T11:26:45.070Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1144, added 1602
2023-11-06T11:26:46.081Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1224, added 1717
2023-11-06T11:26:47.085Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1265, added 1762
2023-11-06T11:26:48.087Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1307, added 1820
2023-11-06T11:26:49.101Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1353, added 1890
2023-11-06T11:26:50.126Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1472, added 2012
2023-11-06T11:26:51.127Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1532, added 2100
2023-11-06T11:26:52.129Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1556, added 2184
2023-11-06T11:26:53.130Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1606, added 2262
2023-11-06T11:26:54.140Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1632, added 2294
2023-11-06T11:26:55.142Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1705, added 2369
2023-11-06T11:26:56.142Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1765, added 2446
2023-11-06T11:26:57.142Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1862, added 2547
2023-11-06T11:26:58.142Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1920, added 2625
2023-11-06T11:26:59.143Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1932, added 2639
2023-11-06T11:27:00.145Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 1974, added 2681
2023-11-06T11:27:01.145Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2068, added 2796
2023-11-06T11:27:02.148Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2132, added 2858
2023-11-06T11:27:03.148Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2220, added 2963
2023-11-06T11:27:04.149Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2232, added 2991
2023-11-06T11:27:05.152Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2300, added 3061
2023-11-06T11:27:06.282Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2391, added 3166
2023-11-06T11:27:07.282Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2439, added 3209
2023-11-06T11:27:08.282Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2482, added 3269
2023-11-06T11:27:09.282Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2501, added 3309
2023-11-06T11:27:10.282Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2504, added 3321
2023-11-06T11:27:11.283Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2508, added 3327
2023-11-06T11:27:12.283Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2511, added 3331
2023-11-06T11:27:13.282Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2513, added 3336
2023-11-06T11:27:14.283Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2517, added 3338
2023-11-06T11:27:15.288Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2530, added 3363
2023-11-06T11:27:16.289Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2536, added 3375
2023-11-06T11:27:17.289Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2541, added 3384
2023-11-06T11:27:18.289Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2554, added 3410
2023-11-06T11:27:19.292Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2557, added 3413
2023-11-06T11:27:20.294Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2565, added 3436
2023-11-06T11:27:21.294Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2572, added 3446
2023-11-06T11:27:24.261Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2573, added 3446
2023-11-06T11:27:25.261Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2577, added 3451
2023-11-06T11:27:26.262Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2581, added 3454
2023-11-06T11:27:27.262Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2597, added 3485
2023-11-06T11:27:28.262Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2605, added 3500
2023-11-06T11:27:29.278Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2610, added 3507
2023-11-06T11:27:30.278Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2626, added 3533
2023-11-06T11:27:31.278Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2648, added 3564
2023-11-06T11:27:32.278Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2677, added 3597
2023-11-06T11:27:33.279Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2720, added 3652
2023-11-06T11:27:34.279Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2748, added 3687
2023-11-06T11:27:35.281Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2751, added 3693
2023-11-06T11:27:36.897Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2752, added 3693
2023-11-06T11:27:37.898Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2752, added 3695
2023-11-06T11:27:38.935Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2753, added 3695
2023-11-06T11:27:39.936Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2754, added 3698
2023-11-06T11:27:41.061Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2755, added 3700
2023-11-06T11:27:42.652Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2756, added 3700
2023-11-06T11:27:43.795Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2756, added 3701
2023-11-06T11:27:44.795Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2758, added 3701
2023-11-06T11:27:47.478Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2759, added 3701
2023-11-06T11:27:48.694Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2760, added 3704
2023-11-06T11:27:49.694Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2761, added 3706
2023-11-06T11:27:50.695Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2762, added 3706
2023-11-06T11:27:51.717Z [INFO]: ../..                                    | Progress: resolved 0, reused 0, downloaded 2762, added 3709, done
2023-11-06T11:27:52.394Z [INFO]: devDependencies:
                                 + @hcp-portal-app/frontend-hosting 1.0.0 <- ../../packages/hosting
                                 + eslint-config-custom 0.0.0 <- ../../packages/eslint-config-custom
                                 + tsconfig 0.0.0 <- ../../packages/tsconfig
2023-11-06T11:27:52.396Z [INFO]: Done in 1m 36.1s
2023-11-06T11:27:52.458Z [INFO]: # Executing command: cd ../..
2023-11-06T11:27:52.458Z [INFO]: # Executing command: pnpm package
2023-11-06T11:27:52.880Z [INFO]: > @hcp-portal-app/root@1.0.0 package /codebuild/output/src898595868/src/hcpportal-front-web
                                 > nx run-many --target=package --all --parallel=4
2023-11-06T11:27:56.450Z [INFO]: 
2023-11-06T11:27:56.451Z [INFO]: >  NX   Running target package for 12 project(s):
                                 - akamai-client
                                 - consumer
                                 - dependency-injector
                                 - frontend-hosting
                                 - frontend-shared
                                 - http-handler
                                 - icare-client
                                 - logger
                                 - magnolia
                                 - nestjs-logger
                                 - public-shared
                                 - segment-client
                                 
2023-11-06T11:28:04.421Z [INFO]: > nx run magnolia:package
                                 > @hcp-portal-app/magnolia@1.0.0 package /codebuild/output/src898595868/src/hcpportal-front-web/packages/magnolia
                                 > tsup --config ./tsup.config.ts
                                 [34mCLI[39m Building entry: src/magnolia.ts
                                 [34mCLI[39m Using tsconfig: tsconfig.json
                                 [34mCLI[39m tsup v7.2.0
                                 [34mCLI[39m Using tsup config: /codebuild/output/src898595868/src/hcpportal-front-web/packages/magnolia/tsup.config.ts
                                 [34mCLI[39m Target: node16
                                 [34mCLI[39m Cleaning output folder
                                 [34mESM[39m Build start
                                 [34mCJS[39m Build start
                                 [32mCJS[39m [1mdist/magnolia.js [22m[32m1.08 KB[39m
                                 [32mCJS[39m ⚡️ Build success in 50ms
                                 [32mESM[39m [1mdist/magnolia.mjs [22m[32m93.00 B[39m
                                 [32mESM[39m ⚡️ Build success in 61ms
                                 [34mDTS[39m Build start
                                 [32mDTS[39m ⚡️ Build success in 4989ms
                                 [32mDTS[39m [1mdist/magnolia.d.mts [22m[32m60.00 B[39m
                                 [32mDTS[39m [1mdist/magnolia.d.ts  [22m[32m60.00 B[39m
2023-11-06T11:28:07.113Z [INFO]: > nx run frontend-shared:package
                                 > @hcp-portal-app/frontend-shared@1.0.0 package /codebuild/output/src898595868/src/hcpportal-front-web/apps/shared
                                 > tsup --config ./tsup.config.ts
                                 [34mCLI[39m Building entry: src/index.ts
                                 [34mCLI[39m Using tsconfig: tsconfig.json
                                 [34mCLI[39m tsup v7.2.0
                                 [34mCLI[39m Using tsup config: /codebuild/output/src898595868/src/hcpportal-front-web/apps/shared/tsup.config.ts
                                 [34mCLI[39m Target: esnext
                                 [34mCLI[39m Cleaning output folder
                                 [34mESM[39m Build start
                                 [34mCJS[39m Build start
                                 [32mCJS[39m [1mdist/index.cjs.js [22m[32m34.84 KB[39m
                                 [32mCJS[39m ⚡️ Build success in 91ms
                                 [32mESM[39m [1mdist/index.esm.js [22m[32m30.73 KB[39m
                                 [32mESM[39m ⚡️ Build success in 93ms
                                 [34mDTS[39m Build start
                                 [32mDTS[39m ⚡️ Build success in 7503ms
                                 [32mDTS[39m [1mdist/index.d.mts [22m[32m18.17 KB[39m
                                 [32mDTS[39m [1mdist/index.d.ts  [22m[32m18.17 KB[39m
2023-11-06T11:28:08.573Z [INFO]: > nx run dependency-injector:package
                                 > @hcp-portal-app/dependency-injector@0.0.0 package /codebuild/output/src898595868/src/hcpportal-front-web/packages/dependency-injector
                                 > tsup src/index.ts --config ../../tsup.config.ts
                                 [34mCLI[39m Building entry: src/index.ts
                                 [34mCLI[39m Using tsconfig: tsconfig.json
                                 [34mCLI[39m tsup v7.2.0
                                 [34mCLI[39m Using tsup config: /codebuild/output/src898595868/src/hcpportal-front-web/tsup.config.ts
                                 [34mCLI[39m Target: es2021
                                 [34mCLI[39m Cleaning output folder
                                 [34mESM[39m Build start
                                 [34mCJS[39m Build start
                                 [32mESM[39m [1mdist/index.mjs [22m[32m2.71 KB[39m
                                 [32mESM[39m ⚡️ Build success in 63ms
                                 [32mCJS[39m [1mdist/index.js [22m[32m3.92 KB[39m
                                 [32mCJS[39m ⚡️ Build success in 64ms
                                 [34mDTS[39m Build start
                                 [32mDTS[39m ⚡️ Build success in 9176ms
                                 [32mDTS[39m [1mdist/index.d.mts [22m[32m985.00 B[39m
                                 [32mDTS[39m [1mdist/index.d.ts  [22m[32m985.00 B[39m
2023-11-06T11:28:18.032Z [INFO]: > nx run logger:package
2023-11-06T11:28:18.034Z [INFO]: > @hcp-portal-app/logger@1.0.0 package /codebuild/output/src898595868/src/hcpportal-front-web/packages/logger
                                 > tsup --config ./tsup.config.ts
                                 [34mCLI[39m Building entry: src/index.ts, src/pino-pretty-transport.ts
                                 [34mCLI[39m Using tsconfig: tsconfig.json
                                 [34mCLI[39m tsup v7.2.0
                                 [34mCLI[39m Using tsup config: /codebuild/output/src898595868/src/hcpportal-front-web/packages/logger/tsup.config.ts
                                 [34mCLI[39m Target: esnext
                                 [34mCLI[39m Cleaning output folder
                                 [34mESM[39m Build start
                                 [34mCJS[39m Build start
                                 [32mESM[39m [1mdist/index.mjs                 [22m[32m2.71 KB[39m
                                 [32mESM[39m [1mdist/pino-pretty-transport.mjs [22m[32m1.04 KB[39m
                                 [32mESM[39m [1mdist/thread-stream-worker.mjs  [22m[32m3.66 KB[39m
                                 [32mESM[39m [1mdist/pino-worker.mjs           [22m[32m1.80 KB[39m
                                 [32mESM[39m [1mdist/pino-pipeline-worker.mjs  [22m[32m1.21 KB[39m
                                 [32mESM[39m [1mdist/chunk-J6BYY373.mjs        [22m[32m1.48 KB[39m
                                 [32mESM[39m [1mdist/chunk-5KN6W42P.mjs        [22m[32m597.00 B[39m
                                 [32mESM[39m [1mdist/pino-file.mjs             [22m[32m721.00 B[39m
                                 [32mESM[39m [1mdist/chunk-TP6NUV33.mjs        [22m[32m112.82 KB[39m
                                 [32mESM[39m [1mdist/chunk-BJWEJA2L.mjs        [22m[32m2.10 KB[39m
                                 [32mESM[39m [1mdist/pino-pretty.mjs           [22m[32m193.00 B[39m
                                 [32mESM[39m [1mdist/chunk-WGBGXNRC.mjs        [22m[32m246.96 KB[39m
                                 [32mESM[39m [1mdist/chunk-6XLIENS4.mjs        [22m[32m201.34 KB[39m
                                 [32mESM[39m [1mdist/chunk-NG5NZASM.mjs        [22m[32m19.02 KB[39m
                                 [32mESM[39m [1mdist/chunk-QHOBBTS4.mjs        [22m[32m1.70 KB[39m
                                 [32mESM[39m ⚡️ Build success in 800ms
                                 [32mCJS[39m [1mdist/index.js                 [22m[32m4.47 KB[39m
                                 [32mCJS[39m [1mdist/pino-pretty-transport.js [22m[32m469.63 KB[39m
                                 [32mCJS[39m [1mdist/thread-stream-worker.js  [22m[32m6.27 KB[39m
                                 [32mCJS[39m [1mdist/pino-worker.js           [22m[32m338.08 KB[39m
                                 [32mCJS[39m [1mdist/pino-pipeline-worker.js  [22m[32m2.83 KB[39m
                                 [32mCJS[39m [1mdist/pino-file.js             [22m[32m134.09 KB[39m
                                 [32mCJS[39m [1mdist/pino-pretty.js           [22m[32m466.80 KB[39m
                                 [32mCJS[39m ⚡️ Build success in 801ms
                                 [34mDTS[39m Build start
                                 src/logger.ts(1,42): error TS2307: Cannot find module '@hcp-portal-app/dependency-injector' or its corresponding type declarations.
                                 [31mError: error occured in dts build
                                 at Worker.<anonymous> (/codebuild/output/src898595868/src/hcpportal-front-web/node_modules/tsup/dist/index.js:2294:26)
                                 at Worker.emit (node:events:513:28)
                                 at MessagePort.<anonymous> (node:internal/worker:233:53)
                                 at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
                                 at exports.emitMessage (node:internal/per_context/messageport:23:28)[39m
                                 [31mDTS[39m [31mBuild error[39m
                                 [31mRollupError: Failed to compile. Check the logs above.
                                 at error (/codebuild/output/src898595868/src/hcpportal-front-web/node_modules/rollup/dist/shared/rollup.js:353:30)
                                 at Object.error (/codebuild/output/src898595868/src/hcpportal-front-web/node_modules/rollup/dist/shared/rollup.js:1720:20)
                                 at Object.error (/codebuild/output/src898595868/src/hcpportal-front-web/node_modules/rollup/dist/shared/rollup.js:25543:42)
                                 at generateDtsFromTs (/codebuild/output/src898595868/src/hcpportal-front-web/node_modules/tsup/dist/rollup.js:7512:22)
                                 at /codebuild/output/src898595868/src/hcpportal-front-web/node_modules/tsup/dist/rollup.js:7519:59
                                 at _nullishCoalesce (/codebuild/output/src898595868/src/hcpportal-front-web/node_modules/tsup/dist/rollup.js:1:198)
                                 at Object.transform (/codebuild/output/src898595868/src/hcpportal-front-web/node_modules/tsup/dist/rollup.js:7519:18)
                                 at /codebuild/output/src898595868/src/hcpportal-front-web/node_modules/rollup/dist/shared/rollup.js:1913:40[39m
                                 src/base-logger.ts(1,30): error TS2307: Cannot find module '@hcp-portal-app/dependency-injector' or its corresponding type declarations.
                                 [41m[30m ELIFECYCLE [39m[49m [31mCommand failed with exit code 1.[39m
2023-11-06T11:28:18.364Z [INFO]: > nx run public-shared:package
                                 > @hcp-portal-app/public-shared@1.0.0 package /codebuild/output/src898595868/src/hcpportal-front-web/packages/public-shared
                                 > pnpm build
                                 > @hcp-portal-app/public-shared@1.0.0 build /codebuild/output/src898595868/src/hcpportal-front-web/packages/public-shared
                                 > tsup src/index.ts
                                 [34mCLI[39m Building entry: src/index.ts
                                 [34mCLI[39m Using tsconfig: tsconfig.json
                                 [34mCLI[39m tsup v7.2.0
                                 [34mCLI[39m Using tsup config: /codebuild/output/src898595868/src/hcpportal-front-web/packages/public-shared/tsup.config.ts
                                 [34mCLI[39m Target: esnext
                                 [34mCLI[39m Cleaning output folder
                                 [34mESM[39m Build start
                                 [34mCJS[39m Build start
                                 [32mESM[39m [1mdist/index.js      [22m[32m3.34 KB[39m
                                 [32mESM[39m [1mdist/index.css     [22m[32m743.00 B[39m
                                 [32mESM[39m [1mdist/index.js.map  [22m[32m8.37 KB[39m
                                 [32mESM[39m [1mdist/index.css.map [22m[32m1.14 KB[39m
                                 [32mESM[39m ⚡️ Build success in 328ms
                                 [32mCJS[39m [1mdist/index.cjs     [22m[32m5.59 KB[39m
                                 [32mCJS[39m [1mdist/index.css     [22m[32m743.00 B[39m
                                 [32mCJS[39m [1mdist/index.cjs.map [22m[32m8.83 KB[39m
                                 [32mCJS[39m [1mdist/index.css.map [22m[32m1.14 KB[39m
                                 [32mCJS[39m ⚡️ Build success in 328ms
                                 [34mDTS[39m Build start
                                 [32mDTS[39m ⚡️ Build success in 7474ms
                                 [32mDTS[39m [1mdist/index.d.ts  [22m[32m2.08 KB[39m
                                 [32mDTS[39m [1mdist/index.d.cts [22m[32m2.08 KB[39m
2023-11-06T11:28:21.301Z [INFO]: > nx run frontend-hosting:package
                                 > @hcp-portal-app/frontend-hosting@1.0.0 package /codebuild/output/src898595868/src/hcpportal-front-web/packages/hosting
                                 > tsup --config ./tsup.config.ts
                                 [34mCLI[39m Building entry: src/index.ts, src/build-notifier/index.ts, src/cache-purger/index.ts
                                 [34mCLI[39m Using tsconfig: tsconfig.json
                                 [34mCLI[39m tsup v7.2.0
                                 [34mCLI[39m Using tsup config: /codebuild/output/src898595868/src/hcpportal-front-web/packages/hosting/tsup.config.ts
                                 [34mCLI[39m Target: es2021
                                 [34mCLI[39m Cleaning output folder
                                 [34mESM[39m Build start
                                 [34mCJS[39m Build start
                                 [34mDTS[39m Build start
                                 [32mCJS[39m [1mdist/build-notifier/index.js [22m[32m1.41 KB[39m
                                 [32mCJS[39m [1mdist/cache-purger/index.js   [22m[32m377.91 KB[39m
                                 [32mCJS[39m [1mdist/index.js                [22m[32m47.76 MB[39m
                                 [32mCJS[39m ⚡️ Build success in 17350ms
                                 [32mESM[39m [1mdist/build-notifier/index.mjs [22m[32m442.00 B[39m
                                 [32mESM[39m [1mdist/cache-purger/index.mjs   [22m[32m375.80 KB[39m
                                 [32mESM[39m [1mdist/chunk-FSROKAF3.mjs       [22m[32m2.07 KB[39m
                                 [32mESM[39m [1mdist/index.mjs                [22m[32m47.76 MB[39m
                                 [32mESM[39m ⚡️ Build success in 17368ms
                                 [32mDTS[39m ⚡️ Build success in 21886ms
                                 [32mDTS[39m [1mdist/index.d.mts                [22m[32m1.67 KB[39m
                                 [32mDTS[39m [1mdist/build-notifier/index.d.mts [22m[32m65.00 B[39m
                                 [32mDTS[39m [1mdist/cache-purger/index.d.mts   [22m[32m65.00 B[39m
                                 [32mDTS[39m [1mdist/index.d.ts                 [22m[32m1.67 KB[39m
                                 [32mDTS[39m [1mdist/build-notifier/index.d.ts  [22m[32m65.00 B[39m
                                 [32mDTS[39m [1mdist/cache-purger/index.d.ts    [22m[32m65.00 B[39m
2023-11-06T11:28:21.367Z [INFO]: 
2023-11-06T11:28:21.367Z [INFO]: 
                                 >  NX   Running target "package" failed
                                 Tasks not run because their dependencies failed or --nx-bail=true:
                                 
                                 - akamai-client:package
                                 - consumer:package
                                 - http-handler:package
                                 - icare-client:package
                                 - nestjs-logger:package
                                 - segment-client:package
                                 
                                 Failed tasks:
                                 
                                 - logger:package
2023-11-06T11:28:21.379Z [INFO]: ELIFECYCLE  Command failed with exit code 1.
2023-11-06T11:28:21.394Z [ERROR]: !!! Build failed
2023-11-06T11:28:21.395Z [INFO]: Please check the supported SSR features to find if your build failure is related to an unsupported feature: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-Amplify-support.html#supported-unsupported-features. You may also find this troubleshooting guide useful: https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html
2023-11-06T11:28:21.395Z [ERROR]: !!! Non-Zero Exit Code detected
2023-11-06T11:28:21.395Z [INFO]: # Starting environment caching...
2023-11-06T11:28:21.395Z [INFO]: # Environment caching completed
Terminating logging...

```

</details>

### Additional information

We also tried changing the file tracing (maybe it could solve monorepo issues):
`outputFileTracingRoot: path.join(__dirname, '../../')`

**Comment by josefaidt** [comment]
Hey @Lezzio :wave: thanks for raising this! Looking through the logs I noticed this error, where it appears the `logger` package may be missing a dependency on `@hcp-portal-app/dependency-injector`:

```
src/logger.ts(1,42): error TS2307: Cannot find module '@hcp-portal-app/dependency-injector' or its corresponding type declarations.
                                 �[31mError: error occured in dts build
```

Can you confirm whether `logger:package` has the dependency declared in its package.json?

I also created a small demo to help alleviate some of the dependency installs and settings I noticed in the buildspec/`amplify.yml` file.

```yml
version: 1
# backend:
#   phases:
#     build:
#       - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        # use custom build image for later versions of Node.js 18.x
        # - nvm use 18
        - corepack enable
        - pnpm install
    build:
      commands:
        # build the entire workspace
        - pnpm run build
        # deploy just our marketing-site
        - pnpm deploy --filter ./apps/marketing-site --prod --ignore-scripts ./out
  artifacts:
    # specify the pnpm deploy output folder and associated app's distribution directory
    baseDirectory: ./out/dist
    files:
      - "**/*"
  cache:
    paths:
      - $(pnpm store path)
```
https://github.com/josefaidt/amplify-hosting-monorepo-with-pnpm/blob/main/amplify.yml

Here we can use `corepack enable` and lean on [`package.json#packageManager`](https://github.com/josefaidt/amplify-hosting-monorepo-with-pnpm/blob/main/package.json#L15) to resolve the proper version of pnpm, which also works locally as you move between projects.

What makes this possible without specifying an `appRoot`, though, is [`pnpm deploy`](https://pnpm.io/cli/deploy)

> All dependencies of the deployed package, including dependencies from the workspace, are installed inside an isolated node_modules directory at the target directory. The target directory will contain a portable package that can be copied to a server and executed without additional steps.

```
pnpm deploy --filter ./apps/marketing-site --prod --ignore-scripts ./out
```

This will copy the folder/package specified with `--filter` to the specified target directory `./out`, where the `node_modules` and associated pnpm store are preloaded with the relevant production dependencies, including [any unpublished packages in your monorepo](https://github.com/josefaidt/amplify-hosting-monorepo-with-pnpm/blob/main/apps/marketing-site/package.json#L14-L15).

- `--filter <package-selector>` specify the package you want to run this command in
- `--prod` install dependencies only
- `--ignore-scripts` to ignore `prepare`, `postinstall`, etc.
- `./out` the deployment folder

Please note `pnpm deploy` also reads and filters using the localized gitignore. Be sure to move your frontend app's output directory to the gitignore in the project root.

Let me know if this works for you or if I can provide any additional clarity! 
Here's the app deployed from the sample repo 🙂 https://main.d3fega0fup6elr.amplifyapp.com/?name=Amplify
