### ISSUE TITLE
Build fails on amplify for node

### ISSUE THREAD

**Issue by pankajsoni19** [aws-amplify/amplify-hosting#3818]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dnjuytvw4f7zx

### Region

ap-southeast-1

### Environment name

production

### Describe the bug

Next Js build is failing with no changes done in code. Seems to be amplify internal error

build settings are >
amplify.yml
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run deploy
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
```

build image default, 
nodeJS override > 16

error log

https://ap-southeast-1.console.aws.amazon.com/amplify/home?region=ap-southeast-1#/dnjuytvw4f7zx/master/29

```
2023-11-18T15:11:07.567Z [ERROR]: InvalidParameterValueException: The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions.
                                  at Object.extractError (/root/./-patch.2/node_modules/aws-sdk/lib/protocol/json.js:80:27)
                                  at Request.extractError (/root/./-patch.2/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8)
                                  at Request.callListeners (/root/./-patch.2/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                  at Request.emit (/root/./-patch.2/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                  at Request.emit (/root/./-patch.2/node_modules/aws-sdk/lib/request.js:686:14)
                                  at Request.transition (/root/./-patch.2/node_modules/aws-sdk/lib/request.js:22:10)
                                  at AcceptorStateMachine.runTo (/root/./-patch.2/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                  at /root/./-patch.2/node_modules/aws-sdk/lib/state_machine.js:26:10
                                  at Request.<anonymous> (/root/./-patch.2/node_modules/aws-sdk/lib/request.js:38:9)
                                  at Request.<anonymous> (/root/./-patch.2/node_modules/aws-sdk/lib/request.js:688:12) {
                                  code: 'InvalidParameterValueException',
                                  '[Type]': 'See error.Type for details.',
                                  time: 2023-11-18T15:11:07.300Z,
                                  requestId: '349983a8-0381-4793-a278-72350d1428d4',
                                  statusCode: 400,
                                  retryable: false,
                                  retryDelay: 79.52183539506083
                                  }
2023-11-18T15:11:07.569Z [ERROR]: [G[?25h[G[J
                                  147s › dnjuytvw4f7zx › InvalidParameterValueException: The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions.
                                  [G[?25h
Terminating logging...
```

### Expected behavior

Build should compile as before about 4 months ago.

### Reproduction steps

1. Git push
2. triggers build
3. next js build succeeds
4. fails on ssr signalling some dependency on AWS Lambda. there is no lambda in our code, so something internal is breaking

**Comment by Jay2113** [comment]
Hi @pankajsoni19 👋 , thanks for reaching out. I observed that your Amplify app `dnjuytvw4f7zx` has been deleted. Based on the logs that you shared it seems that your app was using Amplify's Classic SSR platform (Next.js 11 only). To give you some context, with Amplify's Classic SSR platform some app resources such as Lambda@Edge functions, CloudFront distributions, etc. are deployed in your AWS account. This particular error seems to have occurred since the Lambda@Edge functions for your app were using the Node 12 runtime which has been deprecated: https://docs.aws.amazon.com/id_id/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy. 

Today, if you create an Amplify app using our Classic SSR platform the Lambda@Edge functions for your app will use the Node 16 runtime and you should no longer see this error. That being said, we strongly recommend that you migrate your Next.js 11 apps to the Amplify Hosting compute managed SSR platform. For more information on how to migrate your classic app, refer to this documentation: https://docs.aws.amazon.com/amplify/latest/userguide/update-app-nextjs-version.html.
