### ISSUE TITLE
Frontend build failed after upgrading to version 6 of @aws-amplify/ui-react

### ISSUE THREAD

**Issue by phreitom** [aws-amplify/amplify-hosting#3867]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1vtcqqxsqn607

### AWS Region

us-west-2

### Amplify Hosting feature

Frontend builds

### Frontend framework

React

### Next.js version

N/A

### Next.js router

App Router

### Describe the bug

I upgraded to version 6 of @aws-amplify/ui-react
My app is running fine on my local environment.
I kicked off a new build and it failed on the front end build portion.

                                    npm ERR! g++: error: unrecognized command line option ‘-std=c++2a’; did you mean ‘-std=c++03’?
                                    npm ERR! make: *** [Release/obj.target/re2/lib/addon.o] Error 1
                                    npm ERR! gyp ERR! build error
                                    npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
2023-12-20T01:14:00.793Z [WARNING]: npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/codebuild/output/src4045285886/src/rhyteit/node_modules/node-gyp/lib/build.js:209:23)
                                    npm ERR! gyp ERR! System Linux 4.14.291-218.527.amzn2.x86_64
                                    npm ERR! gyp ERR! command "/root/.nvm/versions/node/v16.19.0/bin/node" "/codebuild/output/src4045285886/src/rhyteit/node_modules/.bin/node-gyp" "rebuild"
                                    npm ERR! gyp ERR! cwd /codebuild/output/src4045285886/src/rhyteit/node_modules/re2
                                    npm ERR! gyp ERR! node -v v16.19.0
                                    npm ERR! gyp ERR! node-gyp -v v10.0.1
                                    npm ERR! gyp ERR! not ok
                                    npm ERR! node:internal/process/promises:279
                                    npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
                                    npm ERR!             ^
                                    npm
2023-12-20T01:14:00.793Z [WARNING]: ERR!
                                    npm ERR! [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1".] {
                                    npm ERR!   code: 'ERR_UNHANDLED_REJECTION'
                                    npm ERR! }
                                    npm ERR! gyp info it worked if it ends with ok
                                    npm ERR! gyp info using node-gyp@10.0.1

                                    npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
                                    npm ERR! g++: error: unrecognized command line option ‘-std=c++2a’; did you mean ‘-std=c++03’?
                                    npm ERR! make: *** [Release/obj.target/re2/lib/addon.o] Error 1
                                    npm ERR! gyp ERR! build error
                                    npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
                                    npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/codebuild/output/src4045285886/src/rhyteit/node_modules/node-gyp/lib/build.js:209:23)
                                    npm ERR! gyp ERR! System Linux 4.14.291-218.527.amzn2.x86_64
                                    npm ERR! gyp ERR! command "/root/.nvm/versions/node/v16.19.0/bin/node" "/codebuild/output/src4045285886/src/rhyteit/node_modules/.bin/node-gyp" "rebuild"
                                    npm ERR! gyp ERR! cwd /codebuild/output/src4045285886/src/rhyteit/node_modules/re2
                                    npm ERR! gyp ERR! node -v v16.19.0
                                    npm ERR! gyp ERR! node-gyp -v v10.0.1
                                    npm ERR! gyp ERR! not ok

To be honest...I don't even know where to begin to look on this one.front-end

### Expected behavior

I expected the front-end build to succeed and my code to be pushed to production.

### Reproduction steps

Upgrade from @aws-amplify/ui-react v4 to v6.
I went through all the code migrations and tested everything to make sure that the application worked properly.
Kick off the build process by checking in code from Visual Code.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
        - /usr/local/bin/pip3.8 install --user pipenv
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
# Put your logs below this line
I uploaded the build log
[BuildLog_122023_1014.txt](https://github.com/aws-amplify/amplify-hosting/files/13729935/BuildLog_122023_1014.txt)

```

</details>

### Additional information

None

**Comment by phreitom** [comment]
Hi :))....help :))

**Comment by phreitom** [comment]
Hi just trying to make sure this doesn't migrate to the bottom of the list. I have no idea what to do on this one. Need help.

**Comment by phreitom** [comment]
On the Build Image Settings, I tried setting the Node.js version to 18. Now, the build process keeps failing telling me that the There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again. I rehook it up and it fails again with same "Reconnect..." message. If I remove Node JS version from Build Image Settings...then I am back to square one with original error
